/***
	colors.cpp

	Color functions.

	For color space conversion functions, check out space.cpp.

	Copyright (c) 2014-2022 Chris Street
***/

#include "libcodehappy.h"
#include <math.h>

#define	COLORNAME(name, clr)	{	name, clr	},

const ColorNames rgbcolor_names[] = {
COLORNAME("above the world", CL_ABOVE_THE_WORLD)
COLORNAME("acid green", X_ACID_GREEN)
COLORNAME("acqua", CL_ACQUA)
COLORNAME("adobe", X_ADOBE)
COLORNAME("agate grey", RAL_AGATE_GREY)
COLORNAME("aglet", CL_AGLET)
COLORNAME("air force blue", L_AIR_FORCE_BLUE)
COLORNAME("alert", CL_ALERT)
COLORNAME("algae", X_ALGAE)
COLORNAME("algae green", X_ALGAE_GREEN)
COLORNAME("alice blue", H_ALICE_BLUE)
COLORNAME("alice in freezeland", CL_ALICE_IN_FREEZELAND)
COLORNAME("alizarin", L_ALIZARIN)
COLORNAME("all cs", CL_ALL_CS)
COLORNAME("allergic to lobster", CL_ALLERGIC_TO_LOBSTER)
COLORNAME("almond", L_ALMOND)
COLORNAME("almost black", X_ALMOST_BLACK)
COLORNAME("almost white", CL_ALMOST_WHITE)
COLORNAME("amaranth", L_AMARANTH)
COLORNAME("amber", L_AMBER)
COLORNAME("amber sae", L_AMBER_SAE)
COLORNAME("american rose", L_AMERICAN_ROSE)
COLORNAME("amethyst", L_AMETHYST)
COLORNAME("anthracite grey", RAL_ANTHRACITE_GREY)
COLORNAME("antiflash white", L_ANTIFLASH_WHITE)
COLORNAME("antique brass", L_ANTIQUE_BRASS)
COLORNAME("antique fuchsia", L_ANTIQUE_FUCHSIA)
COLORNAME("antique pink", RAL_ANTIQUE_PINK)
COLORNAME("antique white", H_ANTIQUE_WHITE)
COLORNAME("ao", L_AO)
COLORNAME("ao english", L_AO_ENGLISH)
COLORNAME("apple", X_APPLE)
COLORNAME("apple chic", CL_APPLE_CHIC)
COLORNAME("apple green", L_APPLE_GREEN)
COLORNAME("apricot", L_APRICOT)
COLORNAME("apricot pink", CL_APRICOT_PINK)
COLORNAME("aqua", H_AQUA)
COLORNAME("aqua blue", X_AQUA_BLUE)
COLORNAME("aqua green", X_AQUA_GREEN)
COLORNAME("aqua marine", X_AQUA_MARINE)
COLORNAME("aquamarine", H_AQUAMARINE)
COLORNAME("arabesque", CL_ARABESQUE)
COLORNAME("army green", L_ARMY_GREEN)
COLORNAME("arsenic", L_ARSENIC)
COLORNAME("arylide yellow", L_ARYLIDE_YELLOW)
COLORNAME("ash grey", L_ASH_GREY)
COLORNAME("asian red", CL_ASIAN_RED)
COLORNAME("asparagus", L_ASPARAGUS)
COLORNAME("ass", CL_ASS)
COLORNAME("atomic tangerine", L_ATOMIC_TANGERINE)
COLORNAME("aubergine", X_AUBERGINE)
COLORNAME("auburn", L_AUBURN)
COLORNAME("aureolin", L_AUREOLIN)
COLORNAME("auro metal saurus", L_AURO_METAL_SAURUS)
COLORNAME("avocado", X_AVOCADO)
COLORNAME("avocado green", X_AVOCADO_GREEN)
COLORNAME("awesome", L_AWESOME)
COLORNAME("azul", X_AZUL)
COLORNAME("azure", H_AZURE)
COLORNAME("azure blue", RAL_AZURE_BLUE)
COLORNAME("azure mist", L_AZURE_MIST)
COLORNAME("baby blue", L_BABY_BLUE)
COLORNAME("baby blue eyes", L_BABY_BLUE_EYES)
COLORNAME("baby green", X_BABY_GREEN)
COLORNAME("baby pink", L_BABY_PINK)
COLORNAME("baby poo", X_BABY_POO)
COLORNAME("baby poop", X_BABY_POOP)
COLORNAME("baby poop green", X_BABY_POOP_GREEN)
COLORNAME("baby puke green", X_BABY_PUKE_GREEN)
COLORNAME("baby purple", X_BABY_PURPLE)
COLORNAME("baby shit brown", X_BABY_SHIT_BROWN)
COLORNAME("baby shit green", X_BABY_SHIT_GREEN)
COLORNAME("ball blue", L_BALL_BLUE)
COLORNAME("banana", X_BANANA)
COLORNAME("banana mania", L_BANANA_MANIA)
COLORNAME("banana yellow", L_BANANA_YELLOW)
COLORNAME("barbie pink", X_BARBIE_PINK)
COLORNAME("barbie world", CL_BARBIE_WORLD)
COLORNAME("barf green", X_BARF_GREEN)
COLORNAME("barney", X_BARNEY)
COLORNAME("barney purple", X_BARNEY_PURPLE)
COLORNAME("basalt grey", RAL_BASALT_GREY)
COLORNAME("batman black", CL_BATMAN_BLACK)
COLORNAME("battleship grey", L_BATTLESHIP_GREY)
COLORNAME("bazaar", L_BAZAAR)
COLORNAME("beatle suits", CL_BEATLE_SUITS)
COLORNAME("beau blue", L_BEAU_BLUE)
COLORNAME("beaver", L_BEAVER)
COLORNAME("bee", CL_BEE)
COLORNAME("beige", H_BEIGE)
COLORNAME("beige brown", RAL_BEIGE_BROWN)
COLORNAME("beige grey", RAL_BEIGE_GREY)
COLORNAME("beige red", RAL_BEIGE_RED)
COLORNAME("berry", X_BERRY)
COLORNAME("big foots delight", CL_BIG_FOOTS_DELIGHT)
COLORNAME("bile", X_BILE)
COLORNAME("bisque", H_BISQUE)
COLORNAME("bistre", L_BISTRE)
COLORNAME("bittersweet", L_BITTERSWEET)
COLORNAME("black", C_BLACK)
COLORNAME("black blue", RAL_BLACK_BLUE)
COLORNAME("black brown", RAL_BLACK_BROWN)
COLORNAME("black green", RAL_BLACK_GREEN)
COLORNAME("black grey", RAL_BLACK_GREY)
COLORNAME("black olive", RAL_BLACK_OLIVE)
COLORNAME("black raspberry", CL_BLACK_RASPBERRY)
COLORNAME("black red", RAL_BLACK_RED)
COLORNAME("black tulip", CL_BLACK_TULIP)
COLORNAME("black wool", CL_BLACK_WOOL)
COLORNAME("blanched almond", H_BLANCHED_ALMOND)
COLORNAME("bland", X_BLAND)
COLORNAME("blaze orange", L_BLAZE_ORANGE)
COLORNAME("bleu de france", L_BLEU_DE_FRANCE)
COLORNAME("blizzard blue", L_BLIZZARD_BLUE)
COLORNAME("blond", L_BLOND)
COLORNAME("blood", X_BLOOD)
COLORNAME("blood orange", X_BLOOD_ORANGE)
COLORNAME("blood red", X_BLOOD_RED)
COLORNAME("bloons", CL_BLOONS)
COLORNAME("blue", C_BLUE)
COLORNAME("blue bell", L_BLUE_BELL)
COLORNAME("blue blue", X_BLUE_BLUE)
COLORNAME("blue gray", L_BLUE_GRAY)
COLORNAME("blue green", L_BLUE_GREEN)
COLORNAME("blue green1", X_BLUE_GREEN1)
COLORNAME("blue grey", RAL_BLUE_GREY)
COLORNAME("blue grey1", X_BLUE_GREY1)
COLORNAME("blue lilac", RAL_BLUE_LILAC)
COLORNAME("blue munsell", L_BLUE_MUNSELL)
COLORNAME("blue ncs", L_BLUE_NCS)
COLORNAME("blue pigment", L_BLUE_PIGMENT)
COLORNAME("blue purple", X_BLUE_PURPLE)
COLORNAME("blue purple1", X_BLUE_PURPLE1)
COLORNAME("blue ryb", L_BLUE_RYB)
COLORNAME("blue violet", H_BLUE_VIOLET)
COLORNAME("blue with a hint of purple", X_BLUE_WITH_A_HINT_OF_PURPLE)
COLORNAME("blueberry", X_BLUEBERRY)
COLORNAME("bluegreen", X_BLUEGREEN)
COLORNAME("bluegrey", X_BLUEGREY)
COLORNAME("bluey green", X_BLUEY_GREEN)
COLORNAME("bluey grey", X_BLUEY_GREY)
COLORNAME("bluey purple", X_BLUEY_PURPLE)
COLORNAME("bluish", X_BLUISH)
COLORNAME("bluish green", X_BLUISH_GREEN)
COLORNAME("bluish grey", X_BLUISH_GREY)
COLORNAME("bluish purple", X_BLUISH_PURPLE)
COLORNAME("blurple", X_BLURPLE)
COLORNAME("blush", L_BLUSH)
COLORNAME("blush pink", X_BLUSH_PINK)
COLORNAME("bole", L_BOLE)
COLORNAME("bollywood", CL_BOLLYWOOD)
COLORNAME("bondi blue", L_BONDI_BLUE)
COLORNAME("booger", X_BOOGER)
COLORNAME("booger green", X_BOOGER_GREEN)
COLORNAME("bordeaux", X_BORDEAUX)
COLORNAME("boring green", X_BORING_GREEN)
COLORNAME("boston university red", L_BOSTON_UNIVERSITY_RED)
COLORNAME("bottle green", X_BOTTLE_GREEN)
COLORNAME("brandeis blue", L_BRANDEIS_BLUE)
COLORNAME("brass", L_BRASS)
COLORNAME("brick", X_BRICK)
COLORNAME("brick orange", X_BRICK_ORANGE)
COLORNAME("brick red", L_BRICK_RED)
COLORNAME("brides blush", CL_BRIDES_BLUSH)
COLORNAME("bright aqua", X_BRIGHT_AQUA)
COLORNAME("bright blue", X_BRIGHT_BLUE)
COLORNAME("bright cerulean", L_BRIGHT_CERULEAN)
COLORNAME("bright cyan", X_BRIGHT_CYAN)
COLORNAME("bright green", C_BRIGHT_GREEN)
COLORNAME("bright lavender", L_BRIGHT_LAVENDER)
COLORNAME("bright light blue", X_BRIGHT_LIGHT_BLUE)
COLORNAME("bright light green", X_BRIGHT_LIGHT_GREEN)
COLORNAME("bright lilac", X_BRIGHT_LILAC)
COLORNAME("bright lime", X_BRIGHT_LIME)
COLORNAME("bright lime green", X_BRIGHT_LIME_GREEN)
COLORNAME("bright magenta", X_BRIGHT_MAGENTA)
COLORNAME("bright maroon", L_BRIGHT_MAROON)
COLORNAME("bright olive", X_BRIGHT_OLIVE)
COLORNAME("bright orange", X_BRIGHT_ORANGE)
COLORNAME("bright pink", L_BRIGHT_PINK)
COLORNAME("bright purple", X_BRIGHT_PURPLE)
COLORNAME("bright red", X_BRIGHT_RED)
COLORNAME("bright red orange", RAL_BRIGHT_RED_ORANGE)
COLORNAME("bright sea green", X_BRIGHT_SEA_GREEN)
COLORNAME("bright sky blue", X_BRIGHT_SKY_BLUE)
COLORNAME("bright teal", X_BRIGHT_TEAL)
COLORNAME("bright turquoise", L_BRIGHT_TURQUOISE)
COLORNAME("bright ube", L_BRIGHT_UBE)
COLORNAME("bright violet", X_BRIGHT_VIOLET)
COLORNAME("bright yellow", X_BRIGHT_YELLOW)
COLORNAME("bright yellow green", X_BRIGHT_YELLOW_GREEN)
COLORNAME("brilliant blue", RAL_BRILLIANT_BLUE)
COLORNAME("brilliant lavender", L_BRILLIANT_LAVENDER)
COLORNAME("brilliant rose", L_BRILLIANT_ROSE)
COLORNAME("brink pink", L_BRINK_PINK)
COLORNAME("british racing green", L_BRITISH_RACING_GREEN)
COLORNAME("broken brick", CL_BROKEN_BRICK)
COLORNAME("broken white", CL_BROKEN_WHITE)
COLORNAME("bronze", L_BRONZE)
COLORNAME("broom yellow", RAL_BROOM_YELLOW)
COLORNAME("brown", H_BROWN)
COLORNAME("brown beige", RAL_BROWN_BEIGE)
COLORNAME("brown green", X_BROWN_GREEN)
COLORNAME("brown grey", RAL_BROWN_GREY)
COLORNAME("brown orange", X_BROWN_ORANGE)
COLORNAME("brown red", X_BROWN_RED)
COLORNAME("brown web", L_BROWN_WEB)
COLORNAME("brown yellow", X_BROWN_YELLOW)
COLORNAME("brownish", X_BROWNISH)
COLORNAME("brownish green", X_BROWNISH_GREEN)
COLORNAME("brownish grey", X_BROWNISH_GREY)
COLORNAME("brownish orange", X_BROWNISH_ORANGE)
COLORNAME("brownish pink", X_BROWNISH_PINK)
COLORNAME("brownish purple", X_BROWNISH_PURPLE)
COLORNAME("brownish red", X_BROWNISH_RED)
COLORNAME("brownish yellow", X_BROWNISH_YELLOW)
COLORNAME("browny green", X_BROWNY_GREEN)
COLORNAME("browny orange", X_BROWNY_ORANGE)
COLORNAME("bruise", X_BRUISE)
COLORNAME("bubble gum", L_BUBBLE_GUM)
COLORNAME("bubble gum pink", X_BUBBLE_GUM_PINK)
COLORNAME("bubblegum", X_BUBBLEGUM)
COLORNAME("bubblegum pink", X_BUBBLEGUM_PINK)
COLORNAME("bubbles", L_BUBBLES)
COLORNAME("buff", L_BUFF)
COLORNAME("bulgarian rose", L_BULGARIAN_ROSE)
COLORNAME("burgundy", L_BURGUNDY)
COLORNAME("burly wood", H_BURLY_WOOD)
COLORNAME("burlywood", L_BURLYWOOD)
COLORNAME("burnt orange", L_BURNT_ORANGE)
COLORNAME("burnt red", X_BURNT_RED)
COLORNAME("burnt siena", X_BURNT_SIENA)
COLORNAME("burnt sienna", L_BURNT_SIENNA)
COLORNAME("burnt umber", L_BURNT_UMBER)
COLORNAME("burnt yellow", X_BURNT_YELLOW)
COLORNAME("burple", X_BURPLE)
COLORNAME("butter", X_BUTTER)
COLORNAME("butter yellow", X_BUTTER_YELLOW)
COLORNAME("butterscotch", X_BUTTERSCOTCH)
COLORNAME("byzantine", L_BYZANTINE)
COLORNAME("byzantium", L_BYZANTIUM)
COLORNAME("cadet", L_CADET)
COLORNAME("cadet blue", H_CADET_BLUE)
COLORNAME("cadet grey", L_CADET_GREY)
COLORNAME("cadmium green", L_CADMIUM_GREEN)
COLORNAME("cadmium orange", L_CADMIUM_ORANGE)
COLORNAME("cadmium red", L_CADMIUM_RED)
COLORNAME("cadmium yellow", L_CADMIUM_YELLOW)
COLORNAME("cal poly pomona green", L_CAL_POLY_POMONA_GREEN)
COLORNAME("cambridge blue", L_CAMBRIDGE_BLUE)
COLORNAME("camel", L_CAMEL)
COLORNAME("camo", X_CAMO)
COLORNAME("camo green", X_CAMO_GREEN)
COLORNAME("camoflauge green", L_CAMOFLAUGE_GREEN)
COLORNAME("camouflage green", X_CAMOUFLAGE_GREEN)
COLORNAME("canary", X_CANARY)
COLORNAME("canary yellow", L_CANARY_YELLOW)
COLORNAME("candy apple red", L_CANDY_APPLE_RED)
COLORNAME("candy pink", L_CANDY_PINK)
COLORNAME("capri", L_CAPRI)
COLORNAME("capri blue", RAL_CAPRI_BLUE)
COLORNAME("caput mortuum", L_CAPUT_MORTUUM)
COLORNAME("caramel", X_CARAMEL)
COLORNAME("cardinal", L_CARDINAL)
COLORNAME("caribbean green", L_CARIBBEAN_GREEN)
COLORNAME("carmine", L_CARMINE)
COLORNAME("carmine pink", L_CARMINE_PINK)
COLORNAME("carmine red", L_CARMINE_RED)
COLORNAME("carnation", X_CARNATION)
COLORNAME("carnation pink", L_CARNATION_PINK)
COLORNAME("carnelian", L_CARNELIAN)
COLORNAME("carolina blue", L_CAROLINA_BLUE)
COLORNAME("carrot orange", L_CARROT_ORANGE)
COLORNAME("ceil", L_CEIL)
COLORNAME("celadon", L_CELADON)
COLORNAME("celery", X_CELERY)
COLORNAME("celestial blue", L_CELESTIAL_BLUE)
COLORNAME("cement", X_CEMENT)
COLORNAME("cement grey", RAL_CEMENT_GREY)
COLORNAME("cerise", L_CERISE)
COLORNAME("cerise pink", L_CERISE_PINK)
COLORNAME("certain frogs", CL_CERTAIN_FROGS)
COLORNAME("cerulean", L_CERULEAN)
COLORNAME("cerulean blue", L_CERULEAN_BLUE)
COLORNAME("chamoisee", L_CHAMOISEE)
COLORNAME("champagne", L_CHAMPAGNE)
COLORNAME("charcoal", L_CHARCOAL)
COLORNAME("charcoal grey", X_CHARCOAL_GREY)
COLORNAME("chartreuse", H_CHARTREUSE)
COLORNAME("chartreuse traditional", L_CHARTREUSE_TRADITIONAL)
COLORNAME("chartreuse web", L_CHARTREUSE_WEB)
COLORNAME("cheery pink", CL_CHEERY_PINK)
COLORNAME("cherry", X_CHERRY)
COLORNAME("cherry blossom pink", L_CHERRY_BLOSSOM_PINK)
COLORNAME("cherry red", X_CHERRY_RED)
COLORNAME("chestnut", L_CHESTNUT)
COLORNAME("chestnut brown", RAL_CHESTNUT_BROWN)
COLORNAME("chocolate", H_CHOCOLATE)
COLORNAME("chocolate brown", X_CHOCOLATE_BROWN)
COLORNAME("chocolate traditional", L_CHOCOLATE_TRADITIONAL)
COLORNAME("chocolate web", L_CHOCOLATE_WEB)
COLORNAME("christmas blue", CL_CHRISTMAS_BLUE)
COLORNAME("chrome green", RAL_CHROME_GREEN)
COLORNAME("chrome yellow", L_CHROME_YELLOW)
COLORNAME("cinereous", L_CINEREOUS)
COLORNAME("cinnabar", L_CINNABAR)
COLORNAME("cinnamon", L_CINNAMON)
COLORNAME("citrine", L_CITRINE)
COLORNAME("claret", X_CLARET)
COLORNAME("claret violet", RAL_CLARET_VIOLET)
COLORNAME("classic rose", L_CLASSIC_ROSE)
COLORNAME("clay", X_CLAY)
COLORNAME("clay brown", RAL_CLAY_BROWN)
COLORNAME("clean pondwater", CL_CLEAN_PONDWATER)
COLORNAME("clear blue", X_CLEAR_BLUE)
COLORNAME("clockwork orange", CL_CLOCKWORK_ORANGE)
COLORNAME("cloudy blue", X_CLOUDY_BLUE)
COLORNAME("cobalt", L_COBALT)
COLORNAME("cobalt blue", X_COBALT_BLUE)
COLORNAME("cocoa", X_COCOA)
COLORNAME("cocoa brown", L_COCOA_BROWN)
COLORNAME("coffee", X_COFFEE)
COLORNAME("color", INVALID_COLOR)
COLORNAME("columbia blue", L_COLUMBIA_BLUE)
COLORNAME("concrete grey", RAL_CONCRETE_GREY)
COLORNAME("conrad gold", CL_CONRAD_GOLD)
COLORNAME("cool black", L_COOL_BLACK)
COLORNAME("cool blue", X_COOL_BLUE)
COLORNAME("cool green", X_COOL_GREEN)
COLORNAME("cool grey", L_COOL_GREY)
COLORNAME("copper", L_COPPER)
COLORNAME("copper brown", RAL_COPPER_BROWN)
COLORNAME("copper rose", L_COPPER_ROSE)
COLORNAME("coquelicot", L_COQUELICOT)
COLORNAME("coral", H_CORAL)
COLORNAME("coral pink", L_CORAL_PINK)
COLORNAME("coral red", L_CORAL_RED)
COLORNAME("cordovan", L_CORDOVAN)
COLORNAME("corn", L_CORN)
COLORNAME("cornell red", L_CORNELL_RED)
COLORNAME("cornflower", X_CORNFLOWER)
COLORNAME("cornflower blue", H_CORNFLOWER_BLUE)
COLORNAME("cornsilk", H_CORNSILK)
COLORNAME("cosmic latte", L_COSMIC_LATTE)
COLORNAME("cotton candy", L_COTTON_CANDY)
COLORNAME("cranberry", X_CRANBERRY)
COLORNAME("cream", L_CREAM)
COLORNAME("creep", CL_CREEP)
COLORNAME("creme", X_CREME)
COLORNAME("crimson", H_CRIMSON)
COLORNAME("crimson glory", L_CRIMSON_GLORY)
COLORNAME("curry yellow", RAL_CURRY_YELLOW)
COLORNAME("custard", X_CUSTARD)
COLORNAME("cyan", H_CYAN)
COLORNAME("cyan process", L_CYAN_PROCESS)
COLORNAME("daffodil", L_DAFFODIL)
COLORNAME("daffodil yellow", RAL_DAFFODIL_YELLOW)
COLORNAME("dahlia yellow", RAL_DAHLIA_YELLOW)
COLORNAME("dandelion", L_DANDELION)
COLORNAME("dark", X_DARK)
COLORNAME("dark aqua", X_DARK_AQUA)
COLORNAME("dark aquamarine", X_DARK_AQUAMARINE)
COLORNAME("dark beige", X_DARK_BEIGE)
COLORNAME("dark blue", H_DARK_BLUE)
COLORNAME("dark blue green", X_DARK_BLUE_GREEN)
COLORNAME("dark blue grey", X_DARK_BLUE_GREY)
COLORNAME("dark brown", L_DARK_BROWN)
COLORNAME("dark byzantium", L_DARK_BYZANTIUM)
COLORNAME("dark candy apple red", L_DARK_CANDY_APPLE_RED)
COLORNAME("dark cerulean", L_DARK_CERULEAN)
COLORNAME("dark champagne", L_DARK_CHAMPAGNE)
COLORNAME("dark chestnut", L_DARK_CHESTNUT)
COLORNAME("dark coral", L_DARK_CORAL)
COLORNAME("dark cream", X_DARK_CREAM)
COLORNAME("dark cyan", H_DARK_CYAN)
COLORNAME("dark electric blue", L_DARK_ELECTRIC_BLUE)
COLORNAME("dark forest green", X_DARK_FOREST_GREEN)
COLORNAME("dark fuchsia", X_DARK_FUCHSIA)
COLORNAME("dark gold", X_DARK_GOLD)
COLORNAME("dark goldenrod", H_DARK_GOLDENROD)
COLORNAME("dark grass green", X_DARK_GRASS_GREEN)
COLORNAME("dark gray", H_DARK_GRAY)
COLORNAME("dark green", H_DARK_GREEN)
COLORNAME("dark green blue", X_DARK_GREEN_BLUE)
COLORNAME("dark grey", H_DARK_GREY)
COLORNAME("dark grey blue", X_DARK_GREY_BLUE)
COLORNAME("dark hot pink", X_DARK_HOT_PINK)
COLORNAME("dark indigo", X_DARK_INDIGO)
COLORNAME("dark jungle green", L_DARK_JUNGLE_GREEN)
COLORNAME("dark khaki", H_DARK_KHAKI)
COLORNAME("dark lava", L_DARK_LAVA)
COLORNAME("dark lavender", L_DARK_LAVENDER)
COLORNAME("dark lilac", X_DARK_LILAC)
COLORNAME("dark lime", X_DARK_LIME)
COLORNAME("dark lime green", X_DARK_LIME_GREEN)
COLORNAME("dark magenta", H_DARK_MAGENTA)
COLORNAME("dark maroon", X_DARK_MAROON)
COLORNAME("dark mauve", X_DARK_MAUVE)
COLORNAME("dark midnight blue", L_DARK_MIDNIGHT_BLUE)
COLORNAME("dark mint", X_DARK_MINT)
COLORNAME("dark mint green", X_DARK_MINT_GREEN)
COLORNAME("dark mustard", X_DARK_MUSTARD)
COLORNAME("dark navy", X_DARK_NAVY)
COLORNAME("dark navy blue", X_DARK_NAVY_BLUE)
COLORNAME("dark olive", X_DARK_OLIVE)
COLORNAME("dark olive green", H_DARK_OLIVE_GREEN)
COLORNAME("dark orange", H_DARK_ORANGE)
COLORNAME("dark orchid", H_DARK_ORCHID)
COLORNAME("dark pastel blue", L_DARK_PASTEL_BLUE)
COLORNAME("dark pastel green", L_DARK_PASTEL_GREEN)
COLORNAME("dark pastel purple", L_DARK_PASTEL_PURPLE)
COLORNAME("dark pastel red", L_DARK_PASTEL_RED)
COLORNAME("dark peach", X_DARK_PEACH)
COLORNAME("dark periwinkle", X_DARK_PERIWINKLE)
COLORNAME("dark pink", L_DARK_PINK)
COLORNAME("dark plum", X_DARK_PLUM)
COLORNAME("dark powder blue", L_DARK_POWDER_BLUE)
COLORNAME("dark purple", X_DARK_PURPLE)
COLORNAME("dark raspberry", L_DARK_RASPBERRY)
COLORNAME("dark red", H_DARK_RED)
COLORNAME("dark rose", X_DARK_ROSE)
COLORNAME("dark royal blue", X_DARK_ROYAL_BLUE)
COLORNAME("dark sage", X_DARK_SAGE)
COLORNAME("dark salmon", H_DARK_SALMON)
COLORNAME("dark sand", X_DARK_SAND)
COLORNAME("dark scarlet", L_DARK_SCARLET)
COLORNAME("dark sea green", H_DARK_SEA_GREEN)
COLORNAME("dark seafoam", X_DARK_SEAFOAM)
COLORNAME("dark seafoam green", X_DARK_SEAFOAM_GREEN)
COLORNAME("dark sienna", L_DARK_SIENNA)
COLORNAME("dark sky blue", X_DARK_SKY_BLUE)
COLORNAME("dark slate blue", H_DARK_SLATE_BLUE)
COLORNAME("dark slate gray", H_DARK_SLATE_GRAY)
COLORNAME("dark slate grey", H_DARK_SLATE_GREY)
COLORNAME("dark spring green", L_DARK_SPRING_GREEN)
COLORNAME("dark tan", L_DARK_TAN)
COLORNAME("dark tangerine", L_DARK_TANGERINE)
COLORNAME("dark taupe", L_DARK_TAUPE)
COLORNAME("dark teal", X_DARK_TEAL)
COLORNAME("dark terra cotta", L_DARK_TERRA_COTTA)
COLORNAME("dark turquoise", H_DARK_TURQUOISE)
COLORNAME("dark violet", H_DARK_VIOLET)
COLORNAME("dark yellow", X_DARK_YELLOW)
COLORNAME("dark yellow green", X_DARK_YELLOW_GREEN)
COLORNAME("darkblue", X_DARKBLUE)
COLORNAME("darkgreen", X_DARKGREEN)
COLORNAME("darkish blue", X_DARKISH_BLUE)
COLORNAME("darkish green", X_DARKISH_GREEN)
COLORNAME("darkish pink", X_DARKISH_PINK)
COLORNAME("darkish purple", X_DARKISH_PURPLE)
COLORNAME("darkish red", X_DARKISH_RED)
COLORNAME("darth gray", CL_DARTH_GRAY)
COLORNAME("dartmouth green", L_DARTMOUTH_GREEN)
COLORNAME("davys grey", L_DAVYS_GREY)
COLORNAME("debian red", L_DEBIAN_RED)
COLORNAME("deep aqua", X_DEEP_AQUA)
COLORNAME("deep blue", X_DEEP_BLUE)
COLORNAME("deep brown", X_DEEP_BROWN)
COLORNAME("deep carmine", L_DEEP_CARMINE)
COLORNAME("deep carmine pink", L_DEEP_CARMINE_PINK)
COLORNAME("deep carrot orange", L_DEEP_CARROT_ORANGE)
COLORNAME("deep cerise", L_DEEP_CERISE)
COLORNAME("deep champagne", L_DEEP_CHAMPAGNE)
COLORNAME("deep chestnut", L_DEEP_CHESTNUT)
COLORNAME("deep fuchsia", L_DEEP_FUCHSIA)
COLORNAME("deep green", X_DEEP_GREEN)
COLORNAME("deep jungle green", L_DEEP_JUNGLE_GREEN)
COLORNAME("deep lavender", X_DEEP_LAVENDER)
COLORNAME("deep lilac", L_DEEP_LILAC)
COLORNAME("deep magenta", L_DEEP_MAGENTA)
COLORNAME("deep orange", X_DEEP_ORANGE)
COLORNAME("deep peach", L_DEEP_PEACH)
COLORNAME("deep pink", H_DEEP_PINK)
COLORNAME("deep purple", X_DEEP_PURPLE)
COLORNAME("deep red", X_DEEP_RED)
COLORNAME("deep rose", X_DEEP_ROSE)
COLORNAME("deep saffron", L_DEEP_SAFFRON)
COLORNAME("deep sea blue", X_DEEP_SEA_BLUE)
COLORNAME("deep sky blue", H_DEEP_SKY_BLUE)
COLORNAME("deep teal", X_DEEP_TEAL)
COLORNAME("deep turquoise", X_DEEP_TURQUOISE)
COLORNAME("deep violet", X_DEEP_VIOLET)
COLORNAME("denim", L_DENIM)
COLORNAME("denim blue", X_DENIM_BLUE)
COLORNAME("desert", L_DESERT)
COLORNAME("desert sand", L_DESERT_SAND)
COLORNAME("diamond girl", CL_DIAMOND_GIRL)
COLORNAME("diarrhea", X_DIARRHEA)
COLORNAME("dim gray", H_DIM_GRAY)
COLORNAME("dim grey", H_DIM_GREY)
COLORNAME("dirt", X_DIRT)
COLORNAME("dirt brown", X_DIRT_BROWN)
COLORNAME("dirty blue", X_DIRTY_BLUE)
COLORNAME("dirty green", X_DIRTY_GREEN)
COLORNAME("dirty orange", X_DIRTY_ORANGE)
COLORNAME("dirty pink", X_DIRTY_PINK)
COLORNAME("dirty purple", X_DIRTY_PURPLE)
COLORNAME("dirty yellow", X_DIRTY_YELLOW)
COLORNAME("distant blue", RAL_DISTANT_BLUE)
COLORNAME("dk blue", H_DK_BLUE)
COLORNAME("dk cyan", H_DK_CYAN)
COLORNAME("dk goldenrod", H_DK_GOLDENROD)
COLORNAME("dk gray", H_DK_GRAY)
COLORNAME("dk green", H_DK_GREEN)
COLORNAME("dk grey", H_DK_GREY)
COLORNAME("dk khaki", H_DK_KHAKI)
COLORNAME("dk magenta", H_DK_MAGENTA)
COLORNAME("dk olive green", H_DK_OLIVE_GREEN)
COLORNAME("dk orange", H_DK_ORANGE)
COLORNAME("dk orchid", H_DK_ORCHID)
COLORNAME("dk red", H_DK_RED)
COLORNAME("dk salmon", H_DK_SALMON)
COLORNAME("dk sea green", H_DK_SEA_GREEN)
COLORNAME("dk slate blue", H_DK_SLATE_BLUE)
COLORNAME("dk slate gray", H_DK_SLATE_GRAY)
COLORNAME("dk slate grey", H_DK_SLATE_GREY)
COLORNAME("dk turquoise", H_DK_TURQUOISE)
COLORNAME("dk violet", H_DK_VIOLET)
COLORNAME("dodger blue", H_DODGER_BLUE)
COLORNAME("dogwood rose", L_DOGWOOD_ROSE)
COLORNAME("dollar bill", L_DOLLAR_BILL)
COLORNAME("drab", L_DRAB)
COLORNAME("drab green", X_DRAB_GREEN)
COLORNAME("dried blood", X_DRIED_BLOOD)
COLORNAME("dried sage", CL_DRIED_SAGE)
COLORNAME("duck egg blue", X_DUCK_EGG_BLUE)
COLORNAME("duke blue", L_DUKE_BLUE)
COLORNAME("dull blue", X_DULL_BLUE)
COLORNAME("dull brown", X_DULL_BROWN)
COLORNAME("dull green", X_DULL_GREEN)
COLORNAME("dull orange", X_DULL_ORANGE)
COLORNAME("dull pink", X_DULL_PINK)
COLORNAME("dull purple", X_DULL_PURPLE)
COLORNAME("dull red", X_DULL_RED)
COLORNAME("dull teal", X_DULL_TEAL)
COLORNAME("dull yellow", X_DULL_YELLOW)
COLORNAME("dusk", X_DUSK)
COLORNAME("dusk blue", X_DUSK_BLUE)
COLORNAME("dusky blue", X_DUSKY_BLUE)
COLORNAME("dusky pink", X_DUSKY_PINK)
COLORNAME("dusky purple", X_DUSKY_PURPLE)
COLORNAME("dusky rose", X_DUSKY_ROSE)
COLORNAME("dust", X_DUST)
COLORNAME("dusty blue", X_DUSTY_BLUE)
COLORNAME("dusty green", X_DUSTY_GREEN)
COLORNAME("dusty grey", RAL_DUSTY_GREY)
COLORNAME("dusty lavender", X_DUSTY_LAVENDER)
COLORNAME("dusty orange", X_DUSTY_ORANGE)
COLORNAME("dusty pink", X_DUSTY_PINK)
COLORNAME("dusty purple", X_DUSTY_PURPLE)
COLORNAME("dusty red", X_DUSTY_RED)
COLORNAME("dusty rose", X_DUSTY_ROSE)
COLORNAME("dusty teal", X_DUSTY_TEAL)
COLORNAME("dutch teal", CL_DUTCH_TEAL)
COLORNAME("earth", X_EARTH)
COLORNAME("earth yellow", L_EARTH_YELLOW)
COLORNAME("easter green", X_EASTER_GREEN)
COLORNAME("easter purple", X_EASTER_PURPLE)
COLORNAME("ecru", L_ECRU)
COLORNAME("eden shining", CL_EDEN_SHINING)
COLORNAME("egg shell", X_EGG_SHELL)
COLORNAME("eggplant", L_EGGPLANT)
COLORNAME("eggplant purple", X_EGGPLANT_PURPLE)
COLORNAME("eggshell", L_EGGSHELL)
COLORNAME("eggshell blue", X_EGGSHELL_BLUE)
COLORNAME("ego", CL_EGO)
COLORNAME("egyptian blue", L_EGYPTIAN_BLUE)
COLORNAME("electric blue", L_ELECTRIC_BLUE)
COLORNAME("electric crimson", L_ELECTRIC_CRIMSON)
COLORNAME("electric cyan", L_ELECTRIC_CYAN)
COLORNAME("electric green", L_ELECTRIC_GREEN)
COLORNAME("electric indigo", L_ELECTRIC_INDIGO)
COLORNAME("electric lavender", L_ELECTRIC_LAVENDER)
COLORNAME("electric lime", L_ELECTRIC_LIME)
COLORNAME("electric pink", X_ELECTRIC_PINK)
COLORNAME("electric purple", L_ELECTRIC_PURPLE)
COLORNAME("electric ultramarine", L_ELECTRIC_ULTRAMARINE)
COLORNAME("electric violet", L_ELECTRIC_VIOLET)
COLORNAME("electric yellow", L_ELECTRIC_YELLOW)
COLORNAME("elle etait belle", CL_ELLE_ETAIT_BELLE)
COLORNAME("emerald", L_EMERALD)
COLORNAME("emerald green", X_EMERALD_GREEN)
COLORNAME("eton blue", L_ETON_BLUE)
COLORNAME("evergreen", X_EVERGREEN)
COLORNAME("everyday valentine", CL_EVERYDAY_VALENTINE)
COLORNAME("faded blue", X_FADED_BLUE)
COLORNAME("faded green", X_FADED_GREEN)
COLORNAME("faded orange", X_FADED_ORANGE)
COLORNAME("faded pink", X_FADED_PINK)
COLORNAME("faded purple", X_FADED_PURPLE)
COLORNAME("faded red", X_FADED_RED)
COLORNAME("faded yellow", X_FADED_YELLOW)
COLORNAME("fallow", L_FALLOW)
COLORNAME("falu red", L_FALU_RED)
COLORNAME("fandango", L_FANDANGO)
COLORNAME("fashion fuchsia", L_FASHION_FUCHSIA)
COLORNAME("fawn", L_FAWN)
COLORNAME("fawn brown", RAL_FAWN_BROWN)
COLORNAME("feldgrau", L_FELDGRAU)
COLORNAME("fern", X_FERN)
COLORNAME("fern green", L_FERN_GREEN)
COLORNAME("ferrari red", L_FERRARI_RED)
COLORNAME("field drab", L_FIELD_DRAB)
COLORNAME("fir green", RAL_FIR_GREEN)
COLORNAME("fire brick", H_FIRE_BRICK)
COLORNAME("fire engine red", L_FIRE_ENGINE_RED)
COLORNAME("firebrick", L_FIREBRICK)
COLORNAME("flame", L_FLAME)
COLORNAME("flame red", RAL_FLAME_RED)
COLORNAME("flamingo pink", L_FLAMINGO_PINK)
COLORNAME("flat blue", X_FLAT_BLUE)
COLORNAME("flat green", X_FLAT_GREEN)
COLORNAME("flavescent", L_FLAVESCENT)
COLORNAME("flax", L_FLAX)
COLORNAME("floral white", H_FLORAL_WHITE)
COLORNAME("fluorescent green", X_FLUORESCENT_GREEN)
COLORNAME("fluorescent orange", L_FLUORESCENT_ORANGE)
COLORNAME("fluorescent pink", L_FLUORESCENT_PINK)
COLORNAME("fluorescent yellow", L_FLUORESCENT_YELLOW)
COLORNAME("fluro green", X_FLURO_GREEN)
COLORNAME("foam", CL_FOAM)
COLORNAME("foam green", X_FOAM_GREEN)
COLORNAME("fog", CL_FOG)
COLORNAME("folly", L_FOLLY)
COLORNAME("forest", X_FOREST)
COLORNAME("forest green", H_FOREST_GREEN)
COLORNAME("forest green traditional", L_FOREST_GREEN_TRADITIONAL)
COLORNAME("forest green web", L_FOREST_GREEN_WEB)
COLORNAME("forrest green", X_FORREST_GREEN)
COLORNAME("french beige", L_FRENCH_BEIGE)
COLORNAME("french blue", L_FRENCH_BLUE)
COLORNAME("french lilac", L_FRENCH_LILAC)
COLORNAME("french rose", L_FRENCH_ROSE)
COLORNAME("fresh", CL_FRESH)
COLORNAME("fresh green", X_FRESH_GREEN)
COLORNAME("frog green", X_FROG_GREEN)
COLORNAME("fuchsia", H_FUCHSIA)
COLORNAME("fuchsia pink", L_FUCHSIA_PINK)
COLORNAME("fulvous", L_FULVOUS)
COLORNAME("fun in the sun", CL_FUN_IN_THE_SUN)
COLORNAME("fuzzy wuzzy", L_FUZZY_WUZZY)
COLORNAME("gainsboro", H_GAINSBORO)
COLORNAME("gamboge", L_GAMBOGE)
COLORNAME("gasping peach", CL_GASPING_PEACH)
COLORNAME("gentian blue", RAL_GENTIAN_BLUE)
COLORNAME("georgia peach", CL_GEORGIA_PEACH)
COLORNAME("ghost white", H_GHOST_WHITE)
COLORNAME("giant goldfish", CL_GIANT_GOLDFISH)
COLORNAME("ginger", L_GINGER)
COLORNAME("glaucous", L_GLAUCOUS)
COLORNAME("gold", H_GOLD)
COLORNAME("gold metallic", L_GOLD_METALLIC)
COLORNAME("gold watch", CL_GOLD_WATCH)
COLORNAME("gold web", L_GOLD_WEB)
COLORNAME("golden", X_GOLDEN)
COLORNAME("golden brown", L_GOLDEN_BROWN)
COLORNAME("golden poppy", L_GOLDEN_POPPY)
COLORNAME("golden rod", X_GOLDEN_ROD)
COLORNAME("golden yellow", RAL_GOLDEN_YELLOW)
COLORNAME("goldenrod", H_GOLDENROD)
COLORNAME("grand ink", CL_GRAND_INK)
COLORNAME("granite grey", RAL_GRANITE_GREY)
COLORNAME("granny smith apple", L_GRANNY_SMITH_APPLE)
COLORNAME("grape", X_GRAPE)
COLORNAME("grape purple", X_GRAPE_PURPLE)
COLORNAME("grapefruit", X_GRAPEFRUIT)
COLORNAME("graphite black", RAL_GRAPHITE_BLACK)
COLORNAME("graphite grey", RAL_GRAPHITE_GREY)
COLORNAME("grass", X_GRASS)
COLORNAME("grass green", X_GRASS_GREEN)
COLORNAME("grassy green", X_GRASSY_GREEN)
COLORNAME("gray", C_GRAY)
COLORNAME("gray asparagus", L_GRAY_ASPARAGUS)
COLORNAME("gray beige", RAL_GRAY_BEIGE)
COLORNAME("gray web", L_GRAY_WEB)
COLORNAME("gray x11", L_GRAY_X11)
COLORNAME("green", H_GREEN)
COLORNAME("green apple", X_GREEN_APPLE)
COLORNAME("green beige", RAL_GREEN_BEIGE)
COLORNAME("green blue", RAL_GREEN_BLUE)
COLORNAME("green blue1", X_GREEN_BLUE1)
COLORNAME("green brown", RAL_GREEN_BROWN)
COLORNAME("green grey", X_GREEN_GREY)
COLORNAME("green munsell", L_GREEN_MUNSELL)
COLORNAME("green ncs", L_GREEN_NCS)
COLORNAME("green pigment", L_GREEN_PIGMENT)
COLORNAME("green ryb", L_GREEN_RYB)
COLORNAME("green tea", CL_GREEN_TEA)
COLORNAME("green teal", X_GREEN_TEAL)
COLORNAME("green web", L_GREEN_WEB)
COLORNAME("green x11", L_GREEN_X11)
COLORNAME("green yellow", H_GREEN_YELLOW)
COLORNAME("green yellow1", X_GREEN_YELLOW1)
COLORNAME("greenblue", X_GREENBLUE)
COLORNAME("greenish", X_GREENISH)
COLORNAME("greenish beige", X_GREENISH_BEIGE)
COLORNAME("greenish blue", X_GREENISH_BLUE)
COLORNAME("greenish brown", X_GREENISH_BROWN)
COLORNAME("greenish cyan", X_GREENISH_CYAN)
COLORNAME("greenish grey", X_GREENISH_GREY)
COLORNAME("greenish tan", X_GREENISH_TAN)
COLORNAME("greenish teal", X_GREENISH_TEAL)
COLORNAME("greenish turquoise", X_GREENISH_TURQUOISE)
COLORNAME("greenish yellow", X_GREENISH_YELLOW)
COLORNAME("greeny blue", X_GREENY_BLUE)
COLORNAME("greeny brown", X_GREENY_BROWN)
COLORNAME("greeny grey", X_GREENY_GREY)
COLORNAME("greeny yellow", X_GREENY_YELLOW)
COLORNAME("grey", C_GREY)
COLORNAME("grey aluminium", RAL_GREY_ALUMINIUM)
COLORNAME("grey blue", RAL_GREY_BLUE)
COLORNAME("grey blue1", X_GREY_BLUE1)
COLORNAME("grey brown", RAL_GREY_BROWN)
COLORNAME("grey green", X_GREY_GREEN)
COLORNAME("grey green1", X_GREY_GREEN1)
COLORNAME("grey olive", RAL_GREY_OLIVE)
COLORNAME("grey pink", X_GREY_PINK)
COLORNAME("grey purple", X_GREY_PURPLE)
COLORNAME("grey teal", X_GREY_TEAL)
COLORNAME("grey white", RAL_GREY_WHITE)
COLORNAME("greyblue", X_GREYBLUE)
COLORNAME("greyish", X_GREYISH)
COLORNAME("greyish blue", X_GREYISH_BLUE)
COLORNAME("greyish brown", X_GREYISH_BROWN)
COLORNAME("greyish green", X_GREYISH_GREEN)
COLORNAME("greyish pink", X_GREYISH_PINK)
COLORNAME("greyish purple", X_GREYISH_PURPLE)
COLORNAME("greyish teal", X_GREYISH_TEAL)
COLORNAME("grooms teal", CL_GROOMS_TEAL)
COLORNAME("gross green", X_GROSS_GREEN)
COLORNAME("grr ey", CL_GRR_EY)
COLORNAME("grullo", L_GRULLO)
COLORNAME("gunmetal", X_GUNMETAL)
COLORNAME("guppie green", L_GUPPIE_GREEN)
COLORNAME("halaya ube", L_HALAYA_UBE)
COLORNAME("han blue", L_HAN_BLUE)
COLORNAME("han purple", L_HAN_PURPLE)
COLORNAME("hansa yellow", L_HANSA_YELLOW)
COLORNAME("happy balloons", CL_HAPPY_BALLOONS)
COLORNAME("harlequin", L_HARLEQUIN)
COLORNAME("harvard crimson", L_HARVARD_CRIMSON)
COLORNAME("harvest gold", L_HARVEST_GOLD)
COLORNAME("haunted milk", CL_HAUNTED_MILK)
COLORNAME("hazel", X_HAZEL)
COLORNAME("heart gold", L_HEART_GOLD)
COLORNAME("heart of gold", CL_HEART_OF_GOLD)
COLORNAME("heather", X_HEATHER)
COLORNAME("heather violet", RAL_HEATHER_VIOLET)
COLORNAME("heirloom hydrangea", CL_HEIRLOOM_HYDRANGEA)
COLORNAME("heliotrope", L_HELIOTROPE)
COLORNAME("high heel", CL_HIGH_HEEL)
COLORNAME("high sky blue", CL_HIGH_SKY_BLUE)
COLORNAME("highlighter green", X_HIGHLIGHTER_GREEN)
COLORNAME("hipster", CL_HIPSTER)
COLORNAME("hollywood cerise", L_HOLLYWOOD_CERISE)
COLORNAME("honey yellow", RAL_HONEY_YELLOW)
COLORNAME("honeydew", H_HONEYDEW)
COLORNAME("hookers green", L_HOOKERS_GREEN)
COLORNAME("hospital green", X_HOSPITAL_GREEN)
COLORNAME("hot green", X_HOT_GREEN)
COLORNAME("hot magenta", L_HOT_MAGENTA)
COLORNAME("hot pink", H_HOT_PINK)
COLORNAME("hot purple", X_HOT_PURPLE)
COLORNAME("hue 35 degrees", CL_HUE_35_DEGREES)
COLORNAME("hunter green", L_HUNTER_GREEN)
COLORNAME("ice", X_ICE)
COLORNAME("ice blue", X_ICE_BLUE)
COLORNAME("iceberg", L_ICEBERG)
COLORNAME("icky green", X_ICKY_GREEN)
COLORNAME("icterine", L_ICTERINE)
COLORNAME("imagine roses", CL_IMAGINE_ROSES)
COLORNAME("inchworm", L_INCHWORM)
COLORNAME("incorrigible tease", CL_INCORRIGIBLE_TEASE)
COLORNAME("india green", L_INDIA_GREEN)
COLORNAME("indian red", H_INDIAN_RED)
COLORNAME("indian yellow", L_INDIAN_YELLOW)
COLORNAME("indigo", H_INDIGO)
COLORNAME("indigo blue", X_INDIGO_BLUE)
COLORNAME("indigo dye", L_INDIGO_DYE)
COLORNAME("indigo web", L_INDIGO_WEB)
COLORNAME("international klein blue", L_INTERNATIONAL_KLEIN_BLUE)
COLORNAME("international orange", L_INTERNATIONAL_ORANGE)
COLORNAME("invisible", CL_INVISIBLE)
COLORNAME("iris", L_IRIS)
COLORNAME("irish green", X_IRISH_GREEN)
COLORNAME("irish sea", CL_IRISH_SEA)
COLORNAME("iron grey", RAL_IRON_GREY)
COLORNAME("isabelline", L_ISABELLINE)
COLORNAME("islamic green", L_ISLAMIC_GREEN)
COLORNAME("its a girl", CL_ITS_A_GIRL)
COLORNAME("ivory", H_IVORY)
COLORNAME("jade", L_JADE)
COLORNAME("jade green", X_JADE_GREEN)
COLORNAME("jasper", L_JASPER)
COLORNAME("jazzberry jam", L_JAZZBERRY_JAM)
COLORNAME("jet black", RAL_JET_BLACK)
COLORNAME("jonquil", L_JONQUIL)
COLORNAME("juicy pink", CL_JUICY_PINK)
COLORNAME("june bud", L_JUNE_BUD)
COLORNAME("jungle green", L_JUNGLE_GREEN)
COLORNAME("kai", CL_KAI)
COLORNAME("kelley green", X_KELLEY_GREEN)
COLORNAME("kelly green", L_KELLY_GREEN)
COLORNAME("kermit green", X_KERMIT_GREEN)
COLORNAME("key lime", X_KEY_LIME)
COLORNAME("khaki", H_KHAKI)
COLORNAME("khaki green", X_KHAKI_GREEN)
COLORNAME("khaki grey", RAL_KHAKI_GREY)
COLORNAME("khaki web", L_KHAKI_WEB)
COLORNAME("khaki x11", L_KHAKI_X11)
COLORNAME("kind giant", CL_KIND_GIANT)
COLORNAME("kings only daughter", CL_KINGS_ONLY_DAUGHTER)
COLORNAME("kitten nose", CL_KITTEN_NOSE)
COLORNAME("kiwi", X_KIWI)
COLORNAME("kiwi green", X_KIWI_GREEN)
COLORNAME("kolding", CL_KOLDING)
COLORNAME("kool aid", CL_KOOL_AID)
COLORNAME("la salle green", L_LA_SALLE_GREEN)
COLORNAME("languid lavender", L_LANGUID_LAVENDER)
COLORNAME("lapis lazuli", L_LAPIS_LAZULI)
COLORNAME("laser lemon", L_LASER_LEMON)
COLORNAME("lava", L_LAVA)
COLORNAME("lavender", H_LAVENDER)
COLORNAME("lavender blue", L_LAVENDER_BLUE)
COLORNAME("lavender blush", H_LAVENDER_BLUSH)
COLORNAME("lavender floral", L_LAVENDER_FLORAL)
COLORNAME("lavender grey", L_LAVENDER_GREY)
COLORNAME("lavender indigo", L_LAVENDER_INDIGO)
COLORNAME("lavender magenta", L_LAVENDER_MAGENTA)
COLORNAME("lavender mist", L_LAVENDER_MIST)
COLORNAME("lavender pink", L_LAVENDER_PINK)
COLORNAME("lavender purple", L_LAVENDER_PURPLE)
COLORNAME("lavender rose", L_LAVENDER_ROSE)
COLORNAME("lavender web", L_LAVENDER_WEB)
COLORNAME("lawn green", H_LAWN_GREEN)
COLORNAME("leaf", X_LEAF)
COLORNAME("leaf green", RAL_LEAF_GREEN)
COLORNAME("leafy green", X_LEAFY_GREEN)
COLORNAME("leather", X_LEATHER)
COLORNAME("lemon", L_LEMON)
COLORNAME("lemon chiffon", H_LEMON_CHIFFON)
COLORNAME("lemon green", X_LEMON_GREEN)
COLORNAME("lemon lime", X_LEMON_LIME)
COLORNAME("lemon yellow", X_LEMON_YELLOW)
COLORNAME("lemoncholy", CL_LEMONCHOLY)
COLORNAME("lichen", X_LICHEN)
COLORNAME("lickable lips", CL_LICKABLE_LIPS)
COLORNAME("light apricot", L_LIGHT_APRICOT)
COLORNAME("light aqua", X_LIGHT_AQUA)
COLORNAME("light aquamarine", X_LIGHT_AQUAMARINE)
COLORNAME("light beige", X_LIGHT_BEIGE)
COLORNAME("light blue", H_LIGHT_BLUE)
COLORNAME("light blue green", X_LIGHT_BLUE_GREEN)
COLORNAME("light blue grey", X_LIGHT_BLUE_GREY)
COLORNAME("light bluish green", X_LIGHT_BLUISH_GREEN)
COLORNAME("light bright green", X_LIGHT_BRIGHT_GREEN)
COLORNAME("light brown", L_LIGHT_BROWN)
COLORNAME("light burgundy", X_LIGHT_BURGUNDY)
COLORNAME("light carmine pink", L_LIGHT_CARMINE_PINK)
COLORNAME("light coral", H_LIGHT_CORAL)
COLORNAME("light cornflower blue", L_LIGHT_CORNFLOWER_BLUE)
COLORNAME("light cyan", H_LIGHT_CYAN)
COLORNAME("light eggplant", X_LIGHT_EGGPLANT)
COLORNAME("light forest green", X_LIGHT_FOREST_GREEN)
COLORNAME("light fuchsia pink", L_LIGHT_FUCHSIA_PINK)
COLORNAME("light gold", X_LIGHT_GOLD)
COLORNAME("light goldenrod yellow", H_LIGHT_GOLDENROD_YELLOW)
COLORNAME("light grass green", X_LIGHT_GRASS_GREEN)
COLORNAME("light gray", H_LIGHT_GRAY)
COLORNAME("light green", H_LIGHT_GREEN)
COLORNAME("light green blue", X_LIGHT_GREEN_BLUE)
COLORNAME("light greenish blue", X_LIGHT_GREENISH_BLUE)
COLORNAME("light grey", RAL_LIGHT_GREY)
COLORNAME("light grey blue", X_LIGHT_GREY_BLUE)
COLORNAME("light grey green", X_LIGHT_GREY_GREEN)
COLORNAME("light indigo", X_LIGHT_INDIGO)
COLORNAME("light ivory", RAL_LIGHT_IVORY)
COLORNAME("light khaki", L_LIGHT_KHAKI)
COLORNAME("light lavendar", X_LIGHT_LAVENDAR)
COLORNAME("light lavender", X_LIGHT_LAVENDER)
COLORNAME("light light blue", X_LIGHT_LIGHT_BLUE)
COLORNAME("light light green", X_LIGHT_LIGHT_GREEN)
COLORNAME("light lilac", X_LIGHT_LILAC)
COLORNAME("light lime", X_LIGHT_LIME)
COLORNAME("light lime green", X_LIGHT_LIME_GREEN)
COLORNAME("light magenta", X_LIGHT_MAGENTA)
COLORNAME("light maroon", X_LIGHT_MAROON)
COLORNAME("light mauve", L_LIGHT_MAUVE)
COLORNAME("light mint", X_LIGHT_MINT)
COLORNAME("light mint green", X_LIGHT_MINT_GREEN)
COLORNAME("light moss green", X_LIGHT_MOSS_GREEN)
COLORNAME("light mustard", X_LIGHT_MUSTARD)
COLORNAME("light navy", X_LIGHT_NAVY)
COLORNAME("light navy blue", X_LIGHT_NAVY_BLUE)
COLORNAME("light neon green", X_LIGHT_NEON_GREEN)
COLORNAME("light olive", X_LIGHT_OLIVE)
COLORNAME("light olive green", X_LIGHT_OLIVE_GREEN)
COLORNAME("light orange", X_LIGHT_ORANGE)
COLORNAME("light pastel green", X_LIGHT_PASTEL_GREEN)
COLORNAME("light pastel purple", L_LIGHT_PASTEL_PURPLE)
COLORNAME("light pea green", X_LIGHT_PEA_GREEN)
COLORNAME("light peach", X_LIGHT_PEACH)
COLORNAME("light periwinkle", X_LIGHT_PERIWINKLE)
COLORNAME("light pink", H_LIGHT_PINK)
COLORNAME("light plum", X_LIGHT_PLUM)
COLORNAME("light purple", X_LIGHT_PURPLE)
COLORNAME("light red", X_LIGHT_RED)
COLORNAME("light rose", X_LIGHT_ROSE)
COLORNAME("light royal blue", X_LIGHT_ROYAL_BLUE)
COLORNAME("light sage", X_LIGHT_SAGE)
COLORNAME("light salmon", H_LIGHT_SALMON)
COLORNAME("light salmon pink", L_LIGHT_SALMON_PINK)
COLORNAME("light sea green", H_LIGHT_SEA_GREEN)
COLORNAME("light seafoam", X_LIGHT_SEAFOAM)
COLORNAME("light seafoam green", X_LIGHT_SEAFOAM_GREEN)
COLORNAME("light sky blue", H_LIGHT_SKY_BLUE)
COLORNAME("light slate gray", H_LIGHT_SLATE_GRAY)
COLORNAME("light steel blue", H_LIGHT_STEEL_BLUE)
COLORNAME("light tan", X_LIGHT_TAN)
COLORNAME("light taupe", L_LIGHT_TAUPE)
COLORNAME("light teal", X_LIGHT_TEAL)
COLORNAME("light thulian pink", L_LIGHT_THULIAN_PINK)
COLORNAME("light turquoise", X_LIGHT_TURQUOISE)
COLORNAME("light urple", X_LIGHT_URPLE)
COLORNAME("light violet", X_LIGHT_VIOLET)
COLORNAME("light yellow", H_LIGHT_YELLOW)
COLORNAME("light yellow green", X_LIGHT_YELLOW_GREEN)
COLORNAME("light yellowish green", X_LIGHT_YELLOWISH_GREEN)
COLORNAME("lightblue", X_LIGHTBLUE)
COLORNAME("lighter green", X_LIGHTER_GREEN)
COLORNAME("lighter purple", X_LIGHTER_PURPLE)
COLORNAME("lightgreen", X_LIGHTGREEN)
COLORNAME("lightish blue", X_LIGHTISH_BLUE)
COLORNAME("lightish green", X_LIGHTISH_GREEN)
COLORNAME("lightish purple", X_LIGHTISH_PURPLE)
COLORNAME("lightish red", X_LIGHTISH_RED)
COLORNAME("lightness", CL_LIGHTNESS)
COLORNAME("lilac", L_LILAC)
COLORNAME("liliac", X_LILIAC)
COLORNAME("lime", H_LIME)
COLORNAME("lime green", H_LIME_GREEN)
COLORNAME("lime web", L_LIME_WEB)
COLORNAME("lime yellow", X_LIME_YELLOW)
COLORNAME("lincoln green", L_LINCOLN_GREEN)
COLORNAME("linen", H_LINEN)
COLORNAME("lipgloss boost", CL_LIPGLOSS_BOOST)
COLORNAME("lipstick", X_LIPSTICK)
COLORNAME("lipstick red", X_LIPSTICK_RED)
COLORNAME("liver", L_LIVER)
COLORNAME("looking through you", CL_LOOKING_THROUGH_YOU)
COLORNAME("love affair", CL_LOVE_AFFAIR)
COLORNAME("lovers red", CL_LOVERS_RED)
COLORNAME("lovliest", CL_LOVLIEST)
COLORNAME("lt blue", H_LT_BLUE)
COLORNAME("lt coral", H_LT_CORAL)
COLORNAME("lt cyan", H_LT_CYAN)
COLORNAME("lt goldenrod yellow", H_LT_GOLDENROD_YELLOW)
COLORNAME("lt gray", H_LT_GRAY)
COLORNAME("lt green", H_LT_GREEN)
COLORNAME("lt grey", H_LT_GREY)
COLORNAME("lt pink", H_LT_PINK)
COLORNAME("lt salmon", H_LT_SALMON)
COLORNAME("lt sea green", H_LT_SEA_GREEN)
COLORNAME("lt sky blue", H_LT_SKY_BLUE)
COLORNAME("lt slate gray", H_LT_SLATE_GRAY)
COLORNAME("lt slate grey", H_LT_SLATE_GREY)
COLORNAME("lt steel blue", H_LT_STEEL_BLUE)
COLORNAME("lt yellow", H_LT_YELLOW)
COLORNAME("luminous bright orange", RAL_LUMINOUS_BRIGHT_ORANGE)
COLORNAME("luminous bright red", RAL_LUMINOUS_BRIGHT_RED)
COLORNAME("luminous green", RAL_LUMINOUS_GREEN)
COLORNAME("luminous orange", RAL_LUMINOUS_ORANGE)
COLORNAME("luminous red", RAL_LUMINOUS_RED)
COLORNAME("luminous yellow", RAL_LUMINOUS_YELLOW)
COLORNAME("lust", L_LUST)
COLORNAME("macaroni and cheese", L_MACARONI_AND_CHEESE)
COLORNAME("magenta", H_MAGENTA)
COLORNAME("magenta dye", L_MAGENTA_DYE)
COLORNAME("magenta process", L_MAGENTA_PROCESS)
COLORNAME("magenta velvet", CL_MAGENTA_VELVET)
COLORNAME("magic mint", L_MAGIC_MINT)
COLORNAME("magnolia", L_MAGNOLIA)
COLORNAME("mahogany", L_MAHOGANY)
COLORNAME("mahogany brown", RAL_MAHOGANY_BROWN)
COLORNAME("maize", L_MAIZE)
COLORNAME("maize yellow", RAL_MAIZE_YELLOW)
COLORNAME("majorelle blue", L_MAJORELLE_BLUE)
COLORNAME("malachite", L_MALACHITE)
COLORNAME("manatee", L_MANATEE)
COLORNAME("mango", X_MANGO)
COLORNAME("mango tango", L_MANGO_TANGO)
COLORNAME("manilla", X_MANILLA)
COLORNAME("marigold", X_MARIGOLD)
COLORNAME("marine", X_MARINE)
COLORNAME("marine blue", X_MARINE_BLUE)
COLORNAME("maroon", H_MAROON)
COLORNAME("maroon web", L_MAROON_WEB)
COLORNAME("maroon x11", L_MAROON_X11)
COLORNAME("mauve", L_MAUVE)
COLORNAME("mauve taupe", L_MAUVE_TAUPE)
COLORNAME("mauvelous", L_MAUVELOUS)
COLORNAME("may green", RAL_MAY_GREEN)
COLORNAME("maya blue", L_MAYA_BLUE)
COLORNAME("maybe green", CL_MAYBE_GREEN)
COLORNAME("meat brown", L_MEAT_BROWN)
COLORNAME("medium aquamarine", H_MEDIUM_AQUAMARINE)
COLORNAME("medium blue", H_MEDIUM_BLUE)
COLORNAME("medium brown", X_MEDIUM_BROWN)
COLORNAME("medium candy apple red", L_MEDIUM_CANDY_APPLE_RED)
COLORNAME("medium carmine", L_MEDIUM_CARMINE)
COLORNAME("medium champagne", L_MEDIUM_CHAMPAGNE)
COLORNAME("medium electric blue", L_MEDIUM_ELECTRIC_BLUE)
COLORNAME("medium green", X_MEDIUM_GREEN)
COLORNAME("medium grey", X_MEDIUM_GREY)
COLORNAME("medium jungle green", L_MEDIUM_JUNGLE_GREEN)
COLORNAME("medium lavender magenta", L_MEDIUM_LAVENDER_MAGENTA)
COLORNAME("medium orchid", H_MEDIUM_ORCHID)
COLORNAME("medium persian blue", L_MEDIUM_PERSIAN_BLUE)
COLORNAME("medium pink", X_MEDIUM_PINK)
COLORNAME("medium purple", H_MEDIUM_PURPLE)
COLORNAME("medium red violet", L_MEDIUM_RED_VIOLET)
COLORNAME("medium sea green", H_MEDIUM_SEA_GREEN)
COLORNAME("medium slate blue", H_MEDIUM_SLATE_BLUE)
COLORNAME("medium spring bud", L_MEDIUM_SPRING_BUD)
COLORNAME("medium spring green", H_MEDIUM_SPRING_GREEN)
COLORNAME("medium taupe", L_MEDIUM_TAUPE)
COLORNAME("medium teal blue", L_MEDIUM_TEAL_BLUE)
COLORNAME("medium turquoise", H_MEDIUM_TURQUOISE)
COLORNAME("medium violet red", H_MEDIUM_VIOLET_RED)
COLORNAME("melon", L_MELON)
COLORNAME("melon yellow", RAL_MELON_YELLOW)
COLORNAME("merlot", X_MERLOT)
COLORNAME("mermaid pink", CL_MERMAID_PINK)
COLORNAME("metallic blue", X_METALLIC_BLUE)
COLORNAME("metro blue", CL_METRO_BLUE)
COLORNAME("mid blue", X_MID_BLUE)
COLORNAME("mid green", X_MID_GREEN)
COLORNAME("midnight", X_MIDNIGHT)
COLORNAME("midnight blue", H_MIDNIGHT_BLUE)
COLORNAME("midnight green", L_MIDNIGHT_GREEN)
COLORNAME("midnight purple", X_MIDNIGHT_PURPLE)
COLORNAME("mighty slate", CL_MIGHTY_SLATE)
COLORNAME("mikado yellow", L_MIKADO_YELLOW)
COLORNAME("military green", X_MILITARY_GREEN)
COLORNAME("milk chocolate", X_MILK_CHOCOLATE)
COLORNAME("millennial blue", CL_MILLENNIAL_BLUE)
COLORNAME("mint", L_MINT)
COLORNAME("mint cream", H_MINT_CREAM)
COLORNAME("mint flower pinkle", CL_MINT_FLOWER_PINKLE)
COLORNAME("mint green", L_MINT_GREEN)
COLORNAME("mint ice cream", CL_MINT_ICE_CREAM)
COLORNAME("mint turquoise", RAL_MINT_TURQUOISE)
COLORNAME("minted peas", CL_MINTED_PEAS)
COLORNAME("minty green", X_MINTY_GREEN)
COLORNAME("misty rose", H_MISTY_ROSE)
COLORNAME("moccasin", H_MOCCASIN)
COLORNAME("mocha", X_MOCHA)
COLORNAME("mode beige", L_MODE_BEIGE)
COLORNAME("mojito", CL_MOJITO)
COLORNAME("monolith", CL_MONOLITH)
COLORNAME("moon at full", CL_MOON_AT_FULL)
COLORNAME("moon warrior", CL_MOON_WARRIOR)
COLORNAME("moonstone blue", L_MOONSTONE_BLUE)
COLORNAME("mordant red 19", L_MORDANT_RED_19)
COLORNAME("morning lilac", CL_MORNING_LILAC)
COLORNAME("moss", X_MOSS)
COLORNAME("moss green", L_MOSS_GREEN)
COLORNAME("moss grey", RAL_MOSS_GREY)
COLORNAME("mossy green", X_MOSSY_GREEN)
COLORNAME("mountain meadow", L_MOUNTAIN_MEADOW)
COLORNAME("mountbatten pink", L_MOUNTBATTEN_PINK)
COLORNAME("mouse grey", RAL_MOUSE_GREY)
COLORNAME("msu green", L_MSU_GREEN)
COLORNAME("mud", X_MUD)
COLORNAME("mud brown", X_MUD_BROWN)
COLORNAME("mud green", X_MUD_GREEN)
COLORNAME("muddy brown", X_MUDDY_BROWN)
COLORNAME("muddy green", X_MUDDY_GREEN)
COLORNAME("muddy yellow", X_MUDDY_YELLOW)
COLORNAME("mulberry", L_MULBERRY)
COLORNAME("murky green", X_MURKY_GREEN)
COLORNAME("mushroom", X_MUSHROOM)
COLORNAME("mustard", L_MUSTARD)
COLORNAME("mustard brown", X_MUSTARD_BROWN)
COLORNAME("mustard green", X_MUSTARD_GREEN)
COLORNAME("mustard yellow", X_MUSTARD_YELLOW)
COLORNAME("muted blue", X_MUTED_BLUE)
COLORNAME("muted green", X_MUTED_GREEN)
COLORNAME("muted pink", X_MUTED_PINK)
COLORNAME("muted purple", X_MUTED_PURPLE)
COLORNAME("myrtle", L_MYRTLE)
COLORNAME("nadeshinko pink", L_NADESHINKO_PINK)
COLORNAME("napier green", L_NAPIER_GREEN)
COLORNAME("naples yellow", L_NAPLES_YELLOW)
COLORNAME("nasty green", X_NASTY_GREEN)
COLORNAME("navajo white", H_NAVAJO_WHITE)
COLORNAME("navy", H_NAVY)
COLORNAME("navy blue", L_NAVY_BLUE)
COLORNAME("navy green", X_NAVY_GREEN)
COLORNAME("neon blue", X_NEON_BLUE)
COLORNAME("neon carrot", L_NEON_CARROT)
COLORNAME("neon fuchsia", L_NEON_FUCHSIA)
COLORNAME("neon green", L_NEON_GREEN)
COLORNAME("neon pink", X_NEON_PINK)
COLORNAME("neon purple", X_NEON_PURPLE)
COLORNAME("neon red", X_NEON_RED)
COLORNAME("neon yellow", X_NEON_YELLOW)
COLORNAME("new life", CL_NEW_LIFE)
COLORNAME("new yolk city", CL_NEW_YOLK_CITY)
COLORNAME("nice blue", X_NICE_BLUE)
COLORNAME("night blue", RAL_NIGHT_BLUE)
COLORNAME("nonphoto blue", L_NONPHOTO_BLUE)
COLORNAME("norad orange", CL_NORAD_ORANGE)
COLORNAME("not quite black", CL_NOT_QUITE_BLACK)
COLORNAME("not sure azure", CL_NOT_SURE_AZURE)
COLORNAME("nut brown", RAL_NUT_BROWN)
COLORNAME("ocean", X_OCEAN)
COLORNAME("ocean blue", X_OCEAN_BLUE)
COLORNAME("ocean boat blue", L_OCEAN_BOAT_BLUE)
COLORNAME("ocean green", X_OCEAN_GREEN)
COLORNAME("ocher", X_OCHER)
COLORNAME("ochre", L_OCHRE)
COLORNAME("ochre brown", RAL_OCHRE_BROWN)
COLORNAME("ochre yellow", RAL_OCHRE_YELLOW)
COLORNAME("ocre", X_OCRE)
COLORNAME("off blue", X_OFF_BLUE)
COLORNAME("off green", X_OFF_GREEN)
COLORNAME("off white", X_OFF_WHITE)
COLORNAME("off yellow", X_OFF_YELLOW)
COLORNAME("office green", L_OFFICE_GREEN)
COLORNAME("old gold", L_OLD_GOLD)
COLORNAME("old lace", H_OLD_LACE)
COLORNAME("old lavender", L_OLD_LAVENDER)
COLORNAME("old mauve", L_OLD_MAUVE)
COLORNAME("old pink", X_OLD_PINK)
COLORNAME("old rose", L_OLD_ROSE)
COLORNAME("olive", H_OLIVE)
COLORNAME("olive brown", RAL_OLIVE_BROWN)
COLORNAME("olive drab", H_OLIVE_DRAB)
COLORNAME("olive drab 7", L_OLIVE_DRAB_7)
COLORNAME("olive drab web", L_OLIVE_DRAB_WEB)
COLORNAME("olive green", X_OLIVE_GREEN)
COLORNAME("olive grey", RAL_OLIVE_GREY)
COLORNAME("olive yellow", RAL_OLIVE_YELLOW)
COLORNAME("olivine", L_OLIVINE)
COLORNAME("onyx", L_ONYX)
COLORNAME("opal green", RAL_OPAL_GREEN)
COLORNAME("opera mauve", L_OPERA_MAUVE)
COLORNAME("orange", H_ORANGE)
COLORNAME("orange brown", RAL_ORANGE_BROWN)
COLORNAME("orange icing", CL_ORANGE_ICING)
COLORNAME("orange peel", L_ORANGE_PEEL)
COLORNAME("orange pink", X_ORANGE_PINK)
COLORNAME("orange red", H_ORANGE_RED)
COLORNAME("orange ryb", L_ORANGE_RYB)
COLORNAME("orange sherbert", CL_ORANGE_SHERBERT)
COLORNAME("orange web", L_ORANGE_WEB)
COLORNAME("orange yellow", X_ORANGE_YELLOW)
COLORNAME("orangeish", X_ORANGEISH)
COLORNAME("orangered", X_ORANGERED)
COLORNAME("orangey brown", X_ORANGEY_BROWN)
COLORNAME("orangey red", X_ORANGEY_RED)
COLORNAME("orangey yellow", X_ORANGEY_YELLOW)
COLORNAME("orangish", X_ORANGISH)
COLORNAME("orangish brown", X_ORANGISH_BROWN)
COLORNAME("orangish red", X_ORANGISH_RED)
COLORNAME("orchid", H_ORCHID)
COLORNAME("orient red", RAL_ORIENT_RED)
COLORNAME("otter brown", L_OTTER_BROWN)
COLORNAME("ou crimson red", L_OU_CRIMSON_RED)
COLORNAME("outer space", L_OUTER_SPACE)
COLORNAME("outrageous orange", L_OUTRAGEOUS_ORANGE)
COLORNAME("oxford blue", L_OXFORD_BLUE)
COLORNAME("oxide red", RAL_OXIDE_RED)
COLORNAME("oyster white", RAL_OYSTER_WHITE)
COLORNAME("pacifica", CL_PACIFICA)
COLORNAME("pakistan green", L_PAKISTAN_GREEN)
COLORNAME("palatinate blue", L_PALATINATE_BLUE)
COLORNAME("palatinate purple", L_PALATINATE_PURPLE)
COLORNAME("pale", X_PALE)
COLORNAME("pale aqua", L_PALE_AQUA)
COLORNAME("pale blue", L_PALE_BLUE)
COLORNAME("pale brown", RAL_PALE_BROWN)
COLORNAME("pale carmine", L_PALE_CARMINE)
COLORNAME("pale cerulean", L_PALE_CERULEAN)
COLORNAME("pale chestnut", L_PALE_CHESTNUT)
COLORNAME("pale copper", L_PALE_COPPER)
COLORNAME("pale cornflower blue", L_PALE_CORNFLOWER_BLUE)
COLORNAME("pale cyan", X_PALE_CYAN)
COLORNAME("pale gold", L_PALE_GOLD)
COLORNAME("pale goldenrod", H_PALE_GOLDENROD)
COLORNAME("pale green", H_PALE_GREEN)
COLORNAME("pale grey", X_PALE_GREY)
COLORNAME("pale lavender", X_PALE_LAVENDER)
COLORNAME("pale light green", X_PALE_LIGHT_GREEN)
COLORNAME("pale lilac", X_PALE_LILAC)
COLORNAME("pale lime", X_PALE_LIME)
COLORNAME("pale lime green", X_PALE_LIME_GREEN)
COLORNAME("pale magenta", L_PALE_MAGENTA)
COLORNAME("pale mauve", X_PALE_MAUVE)
COLORNAME("pale olive", X_PALE_OLIVE)
COLORNAME("pale olive green", X_PALE_OLIVE_GREEN)
COLORNAME("pale orange", X_PALE_ORANGE)
COLORNAME("pale peach", X_PALE_PEACH)
COLORNAME("pale pink", L_PALE_PINK)
COLORNAME("pale plum", L_PALE_PLUM)
COLORNAME("pale purple", X_PALE_PURPLE)
COLORNAME("pale red", X_PALE_RED)
COLORNAME("pale red violet", L_PALE_RED_VIOLET)
COLORNAME("pale robin egg blue", L_PALE_ROBIN_EGG_BLUE)
COLORNAME("pale rose", X_PALE_ROSE)
COLORNAME("pale salmon", X_PALE_SALMON)
COLORNAME("pale silver", L_PALE_SILVER)
COLORNAME("pale sky blue", X_PALE_SKY_BLUE)
COLORNAME("pale spring bud", L_PALE_SPRING_BUD)
COLORNAME("pale taupe", L_PALE_TAUPE)
COLORNAME("pale teal", X_PALE_TEAL)
COLORNAME("pale turquoise", H_PALE_TURQUOISE)
COLORNAME("pale violet", X_PALE_VIOLET)
COLORNAME("pale violet red", H_PALE_VIOLET_RED)
COLORNAME("pale yellow", X_PALE_YELLOW)
COLORNAME("pansy purple", L_PANSY_PURPLE)
COLORNAME("papaya whip", H_PAPAYA_WHIP)
COLORNAME("papyrus white", RAL_PAPYRUS_WHITE)
COLORNAME("parchment", X_PARCHMENT)
COLORNAME("paris blue", CL_PARIS_BLUE)
COLORNAME("paris green", L_PARIS_GREEN)
COLORNAME("part time super girl", CL_PART_TIME_SUPER_GIRL)
COLORNAME("party confetti", CL_PARTY_CONFETTI)
COLORNAME("pastel blue", L_PASTEL_BLUE)
COLORNAME("pastel brown", L_PASTEL_BROWN)
COLORNAME("pastel gray", L_PASTEL_GRAY)
COLORNAME("pastel green", L_PASTEL_GREEN)
COLORNAME("pastel magenta", L_PASTEL_MAGENTA)
COLORNAME("pastel orange", L_PASTEL_ORANGE)
COLORNAME("pastel pink", L_PASTEL_PINK)
COLORNAME("pastel purple", L_PASTEL_PURPLE)
COLORNAME("pastel red", L_PASTEL_RED)
COLORNAME("pastel turquoise", RAL_PASTEL_TURQUOISE)
COLORNAME("pastel violet", L_PASTEL_VIOLET)
COLORNAME("pastel yellow", L_PASTEL_YELLOW)
COLORNAME("patina green", RAL_PATINA_GREEN)
COLORNAME("patriarch", L_PATRIARCH)
COLORNAME("paynes grey", L_PAYNES_GREY)
COLORNAME("pea", X_PEA)
COLORNAME("pea green", X_PEA_GREEN)
COLORNAME("pea soup", X_PEA_SOUP)
COLORNAME("pea soup green", X_PEA_SOUP_GREEN)
COLORNAME("peach", L_PEACH)
COLORNAME("peach orange", L_PEACH_ORANGE)
COLORNAME("peach puff", H_PEACH_PUFF)
COLORNAME("peach yellow", L_PEACH_YELLOW)
COLORNAME("peachy pink", X_PEACHY_PINK)
COLORNAME("peacock blue", X_PEACOCK_BLUE)
COLORNAME("pear", L_PEAR)
COLORNAME("pearl", L_PEARL)
COLORNAME("pearl beige", RAL_PEARL_BEIGE)
COLORNAME("pearl blackberry", RAL_PEARL_BLACKBERRY)
COLORNAME("pearl copper", RAL_PEARL_COPPER)
COLORNAME("pearl dark grey", RAL_PEARL_DARK_GREY)
COLORNAME("pearl gentian blue", RAL_PEARL_GENTIAN_BLUE)
COLORNAME("pearl green", RAL_PEARL_GREEN)
COLORNAME("pearl light grey", RAL_PEARL_LIGHT_GREY)
COLORNAME("pearl mouse grey", RAL_PEARL_MOUSE_GREY)
COLORNAME("pearl night blue", RAL_PEARL_NIGHT_BLUE)
COLORNAME("pearl opal green", RAL_PEARL_OPAL_GREEN)
COLORNAME("pearl orange", RAL_PEARL_ORANGE)
COLORNAME("pearl pink", RAL_PEARL_PINK)
COLORNAME("pearl ruby red", RAL_PEARL_RUBY_RED)
COLORNAME("pearl violet", RAL_PEARL_VIOLET)
COLORNAME("pebble grey", RAL_PEBBLE_GREY)
COLORNAME("peridot", L_PERIDOT)
COLORNAME("periwinkle", L_PERIWINKLE)
COLORNAME("periwinkle blue", X_PERIWINKLE_BLUE)
COLORNAME("perrywinkle", X_PERRYWINKLE)
COLORNAME("persian blue", L_PERSIAN_BLUE)
COLORNAME("persian green", L_PERSIAN_GREEN)
COLORNAME("persian indigo", L_PERSIAN_INDIGO)
COLORNAME("persian orange", L_PERSIAN_ORANGE)
COLORNAME("persian pink", L_PERSIAN_PINK)
COLORNAME("persian plum", L_PERSIAN_PLUM)
COLORNAME("persian red", L_PERSIAN_RED)
COLORNAME("persian rose", L_PERSIAN_ROSE)
COLORNAME("persimmon", L_PERSIMMON)
COLORNAME("peru", H_PERU)
COLORNAME("petrol", X_PETROL)
COLORNAME("phlox", L_PHLOX)
COLORNAME("phthalo blue", L_PHTHALO_BLUE)
COLORNAME("phthalo green", L_PHTHALO_GREEN)
COLORNAME("pig pink", X_PIG_PINK)
COLORNAME("pigeon blue", RAL_PIGEON_BLUE)
COLORNAME("piggy pink", L_PIGGY_PINK)
COLORNAME("pine", X_PINE)
COLORNAME("pine green", L_PINE_GREEN)
COLORNAME("pink", H_PINK)
COLORNAME("pink cocktail", CL_PINK_COCKTAIL)
COLORNAME("pink orange", L_PINK_ORANGE)
COLORNAME("pink pearl", L_PINK_PEARL)
COLORNAME("pink purple", X_PINK_PURPLE)
COLORNAME("pink purple1", X_PINK_PURPLE1)
COLORNAME("pink red", X_PINK_RED)
COLORNAME("pink rose", CL_PINK_ROSE)
COLORNAME("pink sherbet", L_PINK_SHERBET)
COLORNAME("pink suede", CL_PINK_SUEDE)
COLORNAME("pinkish", X_PINKISH)
COLORNAME("pinkish brown", X_PINKISH_BROWN)
COLORNAME("pinkish grey", X_PINKISH_GREY)
COLORNAME("pinkish orange", X_PINKISH_ORANGE)
COLORNAME("pinkish purple", X_PINKISH_PURPLE)
COLORNAME("pinkish red", X_PINKISH_RED)
COLORNAME("pinkish tan", X_PINKISH_TAN)
COLORNAME("pinky", X_PINKY)
COLORNAME("pinky purple", X_PINKY_PURPLE)
COLORNAME("pinky red", X_PINKY_RED)
COLORNAME("piss yellow", X_PISS_YELLOW)
COLORNAME("pistachio", L_PISTACHIO)
COLORNAME("platinum", L_PLATINUM)
COLORNAME("platinum grey", RAL_PLATINUM_GREY)
COLORNAME("plavix", CL_PLAVIX)
COLORNAME("plum", H_PLUM)
COLORNAME("plum purple", X_PLUM_PURPLE)
COLORNAME("plum traditional", L_PLUM_TRADITIONAL)
COLORNAME("plum web", L_PLUM_WEB)
COLORNAME("pluto skin", CL_PLUTO_SKIN)
COLORNAME("poets and dreamers", CL_POETS_AND_DREAMERS)
COLORNAME("poison green", X_POISON_GREEN)
COLORNAME("poo", X_POO)
COLORNAME("poo brown", X_POO_BROWN)
COLORNAME("poolside", CL_POOLSIDE)
COLORNAME("poop", X_POOP)
COLORNAME("poop brown", X_POOP_BROWN)
COLORNAME("poop green", X_POOP_GREEN)
COLORNAME("poppy red", CL_POPPY_RED)
COLORNAME("portland orange", L_PORTLAND_ORANGE)
COLORNAME("pow", CL_POW)
COLORNAME("powder blue", H_POWDER_BLUE)
COLORNAME("powder blue web", L_POWDER_BLUE_WEB)
COLORNAME("powder pink", X_POWDER_PINK)
COLORNAME("powdered sugar", CL_POWDERED_SUGAR)
COLORNAME("praise", CL_PRAISE)
COLORNAME("present", CL_PRESENT)
COLORNAME("primary blue", X_PRIMARY_BLUE)
COLORNAME("princeton orange", L_PRINCETON_ORANGE)
COLORNAME("prune", L_PRUNE)
COLORNAME("prussian blue", L_PRUSSIAN_BLUE)
COLORNAME("psychedelic purple", L_PSYCHEDELIC_PURPLE)
COLORNAME("puce", L_PUCE)
COLORNAME("puke", X_PUKE)
COLORNAME("puke brown", X_PUKE_BROWN)
COLORNAME("puke green", X_PUKE_GREEN)
COLORNAME("puke yellow", X_PUKE_YELLOW)
COLORNAME("pumpkin", L_PUMPKIN)
COLORNAME("pumpkin orange", X_PUMPKIN_ORANGE)
COLORNAME("pure blue", X_PURE_BLUE)
COLORNAME("pure green", RAL_PURE_GREEN)
COLORNAME("pure orange", RAL_PURE_ORANGE)
COLORNAME("pure red", RAL_PURE_RED)
COLORNAME("pure white", RAL_PURE_WHITE)
COLORNAME("purple", H_PURPLE)
COLORNAME("purple blue", X_PURPLE_BLUE)
COLORNAME("purple blue1", X_PURPLE_BLUE1)
COLORNAME("purple brown", X_PURPLE_BROWN)
COLORNAME("purple grey", X_PURPLE_GREY)
COLORNAME("purple heart", L_PURPLE_HEART)
COLORNAME("purple mountain majesty", L_PURPLE_MOUNTAIN_MAJESTY)
COLORNAME("purple munsell", L_PURPLE_MUNSELL)
COLORNAME("purple pink", X_PURPLE_PINK)
COLORNAME("purple pink1", X_PURPLE_PINK1)
COLORNAME("purple pizzazz", L_PURPLE_PIZZAZZ)
COLORNAME("purple red", X_PURPLE_RED)
COLORNAME("purple taupe", L_PURPLE_TAUPE)
COLORNAME("purple violet", RAL_PURPLE_VIOLET)
COLORNAME("purple web", L_PURPLE_WEB)
COLORNAME("purple x11", L_PURPLE_X11)
COLORNAME("purpleish", X_PURPLEISH)
COLORNAME("purpleish blue", X_PURPLEISH_BLUE)
COLORNAME("purpleish pink", X_PURPLEISH_PINK)
COLORNAME("purpley", X_PURPLEY)
COLORNAME("purpley blue", X_PURPLEY_BLUE)
COLORNAME("purpley grey", X_PURPLEY_GREY)
COLORNAME("purpley pink", X_PURPLEY_PINK)
COLORNAME("purplish", X_PURPLISH)
COLORNAME("purplish blue", X_PURPLISH_BLUE)
COLORNAME("purplish brown", X_PURPLISH_BROWN)
COLORNAME("purplish grey", X_PURPLISH_GREY)
COLORNAME("purplish pink", X_PURPLISH_PINK)
COLORNAME("purplish red", X_PURPLISH_RED)
COLORNAME("purply", X_PURPLY)
COLORNAME("purply blue", X_PURPLY_BLUE)
COLORNAME("purply pink", X_PURPLY_PINK)
COLORNAME("putty", X_PUTTY)
COLORNAME("quartz grey", RAL_QUARTZ_GREY)
COLORNAME("qwhite", CL_QWHITE)
COLORNAME("racing green", X_RACING_GREEN)
COLORNAME("radical red", L_RADICAL_RED)
COLORNAME("radioactive green", X_RADIOACTIVE_GREEN)
COLORNAME("rape yellow", RAL_RAPE_YELLOW)
COLORNAME("raspberry", L_RASPBERRY)
COLORNAME("raspberry glace", L_RASPBERRY_GLACE)
COLORNAME("raspberry lemonade", CL_RASPBERRY_LEMONADE)
COLORNAME("raspberry pink", L_RASPBERRY_PINK)
COLORNAME("raspberry red", RAL_RASPBERRY_RED)
COLORNAME("raspberry rose", L_RASPBERRY_ROSE)
COLORNAME("raspberry sauce", CL_RASPBERRY_SAUCE)
COLORNAME("raw sienna", X_RAW_SIENNA)
COLORNAME("raw umber", L_RAW_UMBER)
COLORNAME("rayne", CL_RAYNE)
COLORNAME("razzle dazzle rose", L_RAZZLE_DAZZLE_ROSE)
COLORNAME("razzmatazz", L_RAZZMATAZZ)
COLORNAME("really light blue", X_REALLY_LIGHT_BLUE)
COLORNAME("rebecca purple", H_REBECCA_PURPLE)
COLORNAME("red", C_RED)
COLORNAME("red brown", L_RED_BROWN)
COLORNAME("red lilac", RAL_RED_LILAC)
COLORNAME("red munsell", L_RED_MUNSELL)
COLORNAME("red ncs", L_RED_NCS)
COLORNAME("red orange", RAL_RED_ORANGE)
COLORNAME("red pigment", L_RED_PIGMENT)
COLORNAME("red pink", X_RED_PINK)
COLORNAME("red purple", X_RED_PURPLE)
COLORNAME("red ryb", L_RED_RYB)
COLORNAME("red violet", L_RED_VIOLET)
COLORNAME("red wine", X_RED_WINE)
COLORNAME("reddish", X_REDDISH)
COLORNAME("reddish brown", X_REDDISH_BROWN)
COLORNAME("reddish grey", X_REDDISH_GREY)
COLORNAME("reddish orange", X_REDDISH_ORANGE)
COLORNAME("reddish pink", X_REDDISH_PINK)
COLORNAME("reddish purple", X_REDDISH_PURPLE)
COLORNAME("reddy brown", X_REDDY_BROWN)
COLORNAME("redwood", L_REDWOOD)
COLORNAME("reed green", RAL_REED_GREEN)
COLORNAME("regalia", L_REGALIA)
COLORNAME("reseda green", RAL_RESEDA_GREEN)
COLORNAME("rich black", L_RICH_BLACK)
COLORNAME("rich blue", X_RICH_BLUE)
COLORNAME("rich brilliant lavender", L_RICH_BRILLIANT_LAVENDER)
COLORNAME("rich carmine", L_RICH_CARMINE)
COLORNAME("rich electric blue", L_RICH_ELECTRIC_BLUE)
COLORNAME("rich lavender", L_RICH_LAVENDER)
COLORNAME("rich lilac", L_RICH_LILAC)
COLORNAME("rich maroon", L_RICH_MAROON)
COLORNAME("rich purple", X_RICH_PURPLE)
COLORNAME("rifle green", L_RIFLE_GREEN)
COLORNAME("riverrun", CL_RIVERRUN)
COLORNAME("robin egg blue", L_ROBIN_EGG_BLUE)
COLORNAME("robin s egg", X_ROBIN_S_EGG)
COLORNAME("robin s egg blue", X_ROBIN_S_EGG_BLUE)
COLORNAME("rosa", X_ROSA)
COLORNAME("rosa vieja", CL_ROSA_VIEJA)
COLORNAME("rose", L_ROSE)
COLORNAME("rose bonbon", L_ROSE_BONBON)
COLORNAME("rose ebony", L_ROSE_EBONY)
COLORNAME("rose gold", L_ROSE_GOLD)
COLORNAME("rose madder", L_ROSE_MADDER)
COLORNAME("rose pink", L_ROSE_PINK)
COLORNAME("rose quartz", L_ROSE_QUARTZ)
COLORNAME("rose red", X_ROSE_RED)
COLORNAME("rose taupe", L_ROSE_TAUPE)
COLORNAME("rose vale", L_ROSE_VALE)
COLORNAME("rosen maiden", CL_ROSEN_MAIDEN)
COLORNAME("rosewood", L_ROSEWOOD)
COLORNAME("rosso corsa", L_ROSSO_CORSA)
COLORNAME("rosso passione", CL_ROSSO_PASSIONE)
COLORNAME("rosy brown", H_ROSY_BROWN)
COLORNAME("rosy pink", X_ROSY_PINK)
COLORNAME("rouge", X_ROUGE)
COLORNAME("rounge", CL_ROUNGE)
COLORNAME("royal", X_ROYAL)
COLORNAME("royal azure", L_ROYAL_AZURE)
COLORNAME("royal blue", H_ROYAL_BLUE)
COLORNAME("royal blue traditional", L_ROYAL_BLUE_TRADITIONAL)
COLORNAME("royal blue web", L_ROYAL_BLUE_WEB)
COLORNAME("royal fuchsia", L_ROYAL_FUCHSIA)
COLORNAME("royal purple", L_ROYAL_PURPLE)
COLORNAME("ruby", L_RUBY)
COLORNAME("ruby red", RAL_RUBY_RED)
COLORNAME("ruddy", L_RUDDY)
COLORNAME("ruddy brown", L_RUDDY_BROWN)
COLORNAME("ruddy pink", L_RUDDY_PINK)
COLORNAME("rufous", L_RUFOUS)
COLORNAME("russet", L_RUSSET)
COLORNAME("rust", L_RUST)
COLORNAME("rust brown", X_RUST_BROWN)
COLORNAME("rust orange", X_RUST_ORANGE)
COLORNAME("rust red", X_RUST_RED)
COLORNAME("rusty orange", X_RUSTY_ORANGE)
COLORNAME("rusty red", X_RUSTY_RED)
COLORNAME("sacramento state green", L_SACRAMENTO_STATE_GREEN)
COLORNAME("saddle brown", H_SADDLE_BROWN)
COLORNAME("saffron", L_SAFFRON)
COLORNAME("saffron yellow", RAL_SAFFRON_YELLOW)
COLORNAME("sage", X_SAGE)
COLORNAME("sage green", X_SAGE_GREEN)
COLORNAME("salmon", H_SALMON)
COLORNAME("salmon orange", RAL_SALMON_ORANGE)
COLORNAME("salmon pink", L_SALMON_PINK)
COLORNAME("sand", L_SAND)
COLORNAME("sand brown", X_SAND_BROWN)
COLORNAME("sand dune", L_SAND_DUNE)
COLORNAME("sand mist", CL_SAND_MIST)
COLORNAME("sand yellow", RAL_SAND_YELLOW)
COLORNAME("sandstone", X_SANDSTONE)
COLORNAME("sandstorm", L_SANDSTORM)
COLORNAME("sandy", X_SANDY)
COLORNAME("sandy brown", H_SANDY_BROWN)
COLORNAME("sandy taupe", L_SANDY_TAUPE)
COLORNAME("sandy yellow", X_SANDY_YELLOW)
COLORNAME("sangria", L_SANGRIA)
COLORNAME("sap green", L_SAP_GREEN)
COLORNAME("sapphire", L_SAPPHIRE)
COLORNAME("sapphire blue", RAL_SAPPHIRE_BLUE)
COLORNAME("satin sheen gold", L_SATIN_SHEEN_GOLD)
COLORNAME("scarlet", L_SCARLET)
COLORNAME("school bus yellow", L_SCHOOL_BUS_YELLOW)
COLORNAME("screamin green", L_SCREAMIN_GREEN)
COLORNAME("sea", X_SEA)
COLORNAME("sea blue", X_SEA_BLUE)
COLORNAME("sea green", H_SEA_GREEN)
COLORNAME("seafoam", X_SEAFOAM)
COLORNAME("seafoam blue", X_SEAFOAM_BLUE)
COLORNAME("seafoam green", X_SEAFOAM_GREEN)
COLORNAME("seal brown", L_SEAL_BROWN)
COLORNAME("seashell", H_SEASHELL)
COLORNAME("seaweed", X_SEAWEED)
COLORNAME("seaweed green", X_SEAWEED_GREEN)
COLORNAME("selective yellow", L_SELECTIVE_YELLOW)
COLORNAME("sepia", L_SEPIA)
COLORNAME("sepia brown", RAL_SEPIA_BROWN)
COLORNAME("serenity is", CL_SERENITY_IS)
COLORNAME("sex on the floor", CL_SEX_ON_THE_FLOOR)
COLORNAME("shadow", L_SHADOW)
COLORNAME("shamrock", X_SHAMROCK)
COLORNAME("shamrock green", L_SHAMROCK_GREEN)
COLORNAME("shit", X_SHIT)
COLORNAME("shit brown", X_SHIT_BROWN)
COLORNAME("shit green", X_SHIT_GREEN)
COLORNAME("shocking pink", L_SHOCKING_PINK)
COLORNAME("shut up and kiss me", CL_SHUT_UP_AND_KISS_ME)
COLORNAME("sick green", X_SICK_GREEN)
COLORNAME("sickly green", X_SICKLY_GREEN)
COLORNAME("sickly yellow", X_SICKLY_YELLOW)
COLORNAME("sienna", H_SIENNA)
COLORNAME("signal black", RAL_SIGNAL_BLACK)
COLORNAME("signal blue", RAL_SIGNAL_BLUE)
COLORNAME("signal brown", RAL_SIGNAL_BROWN)
COLORNAME("signal green", RAL_SIGNAL_GREEN)
COLORNAME("signal grey", RAL_SIGNAL_GREY)
COLORNAME("signal orange", RAL_SIGNAL_ORANGE)
COLORNAME("signal red", RAL_SIGNAL_RED)
COLORNAME("signal violet", RAL_SIGNAL_VIOLET)
COLORNAME("signal white", RAL_SIGNAL_WHITE)
COLORNAME("signal yellow", RAL_SIGNAL_YELLOW)
COLORNAME("silk grey", RAL_SILK_GREY)
COLORNAME("silver", H_SILVER)
COLORNAME("silver grey", RAL_SILVER_GREY)
COLORNAME("silver lining", CL_SILVER_LINING)
COLORNAME("sinopia", L_SINOPIA)
COLORNAME("skobeloff", L_SKOBELOFF)
COLORNAME("sky", X_SKY)
COLORNAME("sky blue", H_SKY_BLUE)
COLORNAME("sky magenta", L_SKY_MAGENTA)
COLORNAME("slate", X_SLATE)
COLORNAME("slate blue", H_SLATE_BLUE)
COLORNAME("slate gray", H_SLATE_GRAY)
COLORNAME("slate green", X_SLATE_GREEN)
COLORNAME("slate grey", H_SLATE_GREY)
COLORNAME("slime green", X_SLIME_GREEN)
COLORNAME("sluggish blue", CL_SLUGGISH_BLUE)
COLORNAME("smalt", L_SMALT)
COLORNAME("smokey topaz", L_SMOKEY_TOPAZ)
COLORNAME("smoky black", L_SMOKY_BLACK)
COLORNAME("smooth sailing", CL_SMOOTH_SAILING)
COLORNAME("snot", X_SNOT)
COLORNAME("snot green", X_SNOT_GREEN)
COLORNAME("snow", H_SNOW)
COLORNAME("snowblind", CL_SNOWBLIND)
COLORNAME("soft blue", X_SOFT_BLUE)
COLORNAME("soft green", X_SOFT_GREEN)
COLORNAME("soft pink", X_SOFT_PINK)
COLORNAME("soft purple", X_SOFT_PURPLE)
COLORNAME("soft reddy pink", CL_SOFT_REDDY_PINK)
COLORNAME("some kind of mint", CL_SOME_KIND_OF_MINT)
COLORNAME("spearmint", X_SPEARMINT)
COLORNAME("spiro disco ball", L_SPIRO_DISCO_BALL)
COLORNAME("splashed white", L_SPLASHED_WHITE)
COLORNAME("spring bud", L_SPRING_BUD)
COLORNAME("spring green", H_SPRING_GREEN)
COLORNAME("spruce", X_SPRUCE)
COLORNAME("squash", X_SQUASH)
COLORNAME("squirrel grey", RAL_SQUIRREL_GREY)
COLORNAME("st patricks blue", L_ST_PATRICKS_BLUE)
COLORNAME("steel", X_STEEL)
COLORNAME("steel blue", H_STEEL_BLUE)
COLORNAME("steel grey", X_STEEL_GREY)
COLORNAME("stil de grain yellow", L_STIL_DE_GRAIN_YELLOW)
COLORNAME("stone", X_STONE)
COLORNAME("stone grey", RAL_STONE_GREY)
COLORNAME("stormy blue", X_STORMY_BLUE)
COLORNAME("straw", L_STRAW)
COLORNAME("strawberry", X_STRAWBERRY)
COLORNAME("strawberry lipgloss", CL_STRAWBERRY_LIPGLOSS)
COLORNAME("strawberry red", RAL_STRAWBERRY_RED)
COLORNAME("strawvery red", CL_STRAWVERY_RED)
COLORNAME("strong blue", X_STRONG_BLUE)
COLORNAME("strong pink", X_STRONG_PINK)
COLORNAME("sugar champagne", CL_SUGAR_CHAMPAGNE)
COLORNAME("sugar hearts you", CL_SUGAR_HEARTS_YOU)
COLORNAME("sugarminuet", CL_SUGARMINUET)
COLORNAME("sulfur yellow", RAL_SULFUR_YELLOW)
COLORNAME("sun yellow", RAL_SUN_YELLOW)
COLORNAME("sunflower", X_SUNFLOWER)
COLORNAME("sunflower yellow", X_SUNFLOWER_YELLOW)
COLORNAME("sunglow", L_SUNGLOW)
COLORNAME("sunny soft yellow", CL_SUNNY_SOFT_YELLOW)
COLORNAME("sunny yellow", X_SUNNY_YELLOW)
COLORNAME("sunset", L_SUNSET)
COLORNAME("sunshine yellow", X_SUNSHINE_YELLOW)
COLORNAME("super swell pink", CL_SUPER_SWELL_PINK)
COLORNAME("swamp", X_SWAMP)
COLORNAME("swamp green", X_SWAMP_GREEN)
COLORNAME("sweet lilac", CL_SWEET_LILAC)
COLORNAME("sweetest goodbye", CL_SWEETEST_GOODBYE)
COLORNAME("tan", H_TAN)
COLORNAME("tan brown", X_TAN_BROWN)
COLORNAME("tan green", X_TAN_GREEN)
COLORNAME("tangelo", L_TANGELO)
COLORNAME("tangerine", L_TANGERINE)
COLORNAME("tangerine yellow", L_TANGERINE_YELLOW)
COLORNAME("tarpaulin grey", RAL_TARPAULIN_GREY)
COLORNAME("taupe", L_TAUPE)
COLORNAME("taupe gray", L_TAUPE_GRAY)
COLORNAME("tawny", L_TAWNY)
COLORNAME("tea", X_TEA)
COLORNAME("tea green", L_TEA_GREEN)
COLORNAME("tea rose", L_TEA_ROSE)
COLORNAME("tea rose orange", L_TEA_ROSE_ORANGE)
COLORNAME("teal", H_TEAL)
COLORNAME("teal blue", L_TEAL_BLUE)
COLORNAME("teal green", L_TEAL_GREEN)
COLORNAME("tealish", X_TEALISH)
COLORNAME("tealish green", X_TEALISH_GREEN)
COLORNAME("telegrey 1", RAL_TELEGREY_1)
COLORNAME("telegrey 2", RAL_TELEGREY_2)
COLORNAME("telegrey 4", RAL_TELEGREY_4)
COLORNAME("telemagenta", RAL_TELEMAGENTA)
COLORNAME("terra brown", RAL_TERRA_BROWN)
COLORNAME("terra cotta", L_TERRA_COTTA)
COLORNAME("terracota", X_TERRACOTA)
COLORNAME("terracotta", X_TERRACOTTA)
COLORNAME("thicket", CL_THICKET)
COLORNAME("thistle", H_THISTLE)
COLORNAME("thulian pink", L_THULIAN_PINK)
COLORNAME("tickle me pink", L_TICKLE_ME_PINK)
COLORNAME("tiffany blue", L_TIFFANY_BLUE)
COLORNAME("tiffany twisted", CL_TIFFANY_TWISTED)
COLORNAME("tigers eye", L_TIGERS_EYE)
COLORNAME("timberwolf", L_TIMBERWOLF)
COLORNAME("titanium yellow", L_TITANIUM_YELLOW)
COLORNAME("tomato", H_TOMATO)
COLORNAME("tomato red", RAL_TOMATO_RED)
COLORNAME("toolbox", L_TOOLBOX)
COLORNAME("topaz", X_TOPAZ)
COLORNAME("toupe", X_TOUPE)
COLORNAME("toxic green", X_TOXIC_GREEN)
COLORNAME("tractor red", L_TRACTOR_RED)
COLORNAME("traffic black", RAL_TRAFFIC_BLACK)
COLORNAME("traffic blue", RAL_TRAFFIC_BLUE)
COLORNAME("traffic green", RAL_TRAFFIC_GREEN)
COLORNAME("traffic grey a", RAL_TRAFFIC_GREY_A)
COLORNAME("traffic grey b", RAL_TRAFFIC_GREY_B)
COLORNAME("traffic orange", RAL_TRAFFIC_ORANGE)
COLORNAME("traffic purple", RAL_TRAFFIC_PURPLE)
COLORNAME("traffic red", RAL_TRAFFIC_RED)
COLORNAME("traffic white", RAL_TRAFFIC_WHITE)
COLORNAME("traffic yellow", RAL_TRAFFIC_YELLOW)
COLORNAME("tree green", X_TREE_GREEN)
COLORNAME("trolley grey", L_TROLLEY_GREY)
COLORNAME("tropical rain forest", L_TROPICAL_RAIN_FOREST)
COLORNAME("true blue", L_TRUE_BLUE)
COLORNAME("true green", X_TRUE_GREEN)
COLORNAME("tufts blue", L_TUFTS_BLUE)
COLORNAME("tumbleweed", L_TUMBLEWEED)
COLORNAME("turkish rose", L_TURKISH_ROSE)
COLORNAME("turquoise", H_TURQUOISE)
COLORNAME("turquoise blue", L_TURQUOISE_BLUE)
COLORNAME("turquoise green", L_TURQUOISE_GREEN)
COLORNAME("turtle green", X_TURTLE_GREEN)
COLORNAME("tuscan red", L_TUSCAN_RED)
COLORNAME("twilight", X_TWILIGHT)
COLORNAME("twilight blue", X_TWILIGHT_BLUE)
COLORNAME("twilight lavender", L_TWILIGHT_LAVENDER)
COLORNAME("tyrian purple", L_TYRIAN_PURPLE)
COLORNAME("ua blue", L_UA_BLUE)
COLORNAME("ua red", L_UA_RED)
COLORNAME("ube", L_UBE)
COLORNAME("ucla blue", L_UCLA_BLUE)
COLORNAME("ucla gold", L_UCLA_GOLD)
COLORNAME("ufo green", L_UFO_GREEN)
COLORNAME("ugly blue", X_UGLY_BLUE)
COLORNAME("ugly brown", X_UGLY_BROWN)
COLORNAME("ugly green", X_UGLY_GREEN)
COLORNAME("ugly pink", X_UGLY_PINK)
COLORNAME("ugly purple", X_UGLY_PURPLE)
COLORNAME("ugly yellow", X_UGLY_YELLOW)
COLORNAME("ultra pink", L_ULTRA_PINK)
COLORNAME("ultramarine", L_ULTRAMARINE)
COLORNAME("ultramarine blue", L_ULTRAMARINE_BLUE)
COLORNAME("umber", L_UMBER)
COLORNAME("umbra grey", RAL_UMBRA_GREY)
COLORNAME("unicorn milk", CL_UNICORN_MILK)
COLORNAME("united nations blue", L_UNITED_NATIONS_BLUE)
COLORNAME("unmellow yellow", L_UNMELLOW_YELLOW)
COLORNAME("up forest green", L_UP_FOREST_GREEN)
COLORNAME("up maroon", L_UP_MAROON)
COLORNAME("upsdell red", L_UPSDELL_RED)
COLORNAME("urobilin", L_UROBILIN)
COLORNAME("usc cardinal", L_USC_CARDINAL)
COLORNAME("usc gold", L_USC_GOLD)
COLORNAME("utah crimson", L_UTAH_CRIMSON)
COLORNAME("vanilla", L_VANILLA)
COLORNAME("vanilla cream", CL_VANILLA_CREAM)
COLORNAME("vegas gold", L_VEGAS_GOLD)
COLORNAME("velvet", X_VELVET)
COLORNAME("venetian red", L_VENETIAN_RED)
COLORNAME("verdigris", L_VERDIGRIS)
COLORNAME("vermilion", L_VERMILION)
COLORNAME("vermillion", RAL_VERMILLION)
COLORNAME("veronica", L_VERONICA)
COLORNAME("very dark blue", X_VERY_DARK_BLUE)
COLORNAME("very dark brown", X_VERY_DARK_BROWN)
COLORNAME("very dark green", X_VERY_DARK_GREEN)
COLORNAME("very dark purple", X_VERY_DARK_PURPLE)
COLORNAME("very light blue", X_VERY_LIGHT_BLUE)
COLORNAME("very light brown", X_VERY_LIGHT_BROWN)
COLORNAME("very light green", X_VERY_LIGHT_GREEN)
COLORNAME("very light pink", X_VERY_LIGHT_PINK)
COLORNAME("very light purple", X_VERY_LIGHT_PURPLE)
COLORNAME("very pale blue", X_VERY_PALE_BLUE)
COLORNAME("very pale green", X_VERY_PALE_GREEN)
COLORNAME("vibrant blue", X_VIBRANT_BLUE)
COLORNAME("vibrant green", X_VIBRANT_GREEN)
COLORNAME("vibrant purple", X_VIBRANT_PURPLE)
COLORNAME("vintage black", CL_VINTAGE_BLACK)
COLORNAME("violet", H_VIOLET)
COLORNAME("violet blue", RAL_VIOLET_BLUE)
COLORNAME("violet color wheel", L_VIOLET_COLOR_WHEEL)
COLORNAME("violet pink", X_VIOLET_PINK)
COLORNAME("violet red", X_VIOLET_RED)
COLORNAME("violet ryb", L_VIOLET_RYB)
COLORNAME("violet web", L_VIOLET_WEB)
COLORNAME("viridian", L_VIRIDIAN)
COLORNAME("vitamin c", CL_VITAMIN_C)
COLORNAME("vivid auburn", L_VIVID_AUBURN)
COLORNAME("vivid blue", X_VIVID_BLUE)
COLORNAME("vivid burgundy", L_VIVID_BURGUNDY)
COLORNAME("vivid cerise", L_VIVID_CERISE)
COLORNAME("vivid green", X_VIVID_GREEN)
COLORNAME("vivid purple", X_VIVID_PURPLE)
COLORNAME("vivid tangerine", L_VIVID_TANGERINE)
COLORNAME("vivid violet", L_VIVID_VIOLET)
COLORNAME("vomit", X_VOMIT)
COLORNAME("vomit green", X_VOMIT_GREEN)
COLORNAME("vomit yellow", X_VOMIT_YELLOW)
COLORNAME("warm black", L_WARM_BLACK)
COLORNAME("warm blue", X_WARM_BLUE)
COLORNAME("warm brown", X_WARM_BROWN)
COLORNAME("warm grey", X_WARM_GREY)
COLORNAME("warm pink", X_WARM_PINK)
COLORNAME("warm purple", X_WARM_PURPLE)
COLORNAME("washed out green", X_WASHED_OUT_GREEN)
COLORNAME("water blue", RAL_WATER_BLUE)
COLORNAME("watermelon", X_WATERMELON)
COLORNAME("watermelon guts", CL_WATERMELON_GUTS)
COLORNAME("watermelon pink", CL_WATERMELON_PINK)
COLORNAME("watermillion", CL_WATERMILLION)
COLORNAME("weak tea", CL_WEAK_TEA)
COLORNAME("wedded passion", CL_WEDDED_PASSION)
COLORNAME("wedding green", CL_WEDDING_GREEN)
COLORNAME("weird green", X_WEIRD_GREEN)
COLORNAME("wenge", L_WENGE)
COLORNAME("wheat", H_WHEAT)
COLORNAME("white", C_WHITE)
COLORNAME("white aluminium", RAL_WHITE_ALUMINIUM)
COLORNAME("white smoke", H_WHITE_SMOKE)
COLORNAME("wild blue yonder", L_WILD_BLUE_YONDER)
COLORNAME("wild strawberry", L_WILD_STRAWBERRY)
COLORNAME("wild watermelon", L_WILD_WATERMELON)
COLORNAME("winamp yellow", CL_WINAMP_YELLOW)
COLORNAME("window grey", RAL_WINDOW_GREY)
COLORNAME("windows blue", X_WINDOWS_BLUE)
COLORNAME("wine", X_WINE)
COLORNAME("wine red", RAL_WINE_RED)
COLORNAME("wintergreen", X_WINTERGREEN)
COLORNAME("wisteria", L_WISTERIA)
COLORNAME("xanadu", L_XANADU)
COLORNAME("yale blue", L_YALE_BLUE)
COLORNAME("yellow", C_YELLOW)
COLORNAME("yellow brown", X_YELLOW_BROWN)
COLORNAME("yellow green", H_YELLOW_GREEN)
COLORNAME("yellow green1", X_YELLOW_GREEN1)
COLORNAME("yellow grey", RAL_YELLOW_GREY)
COLORNAME("yellow munsell", L_YELLOW_MUNSELL)
COLORNAME("yellow ncs", L_YELLOW_NCS)
COLORNAME("yellow ochre", X_YELLOW_OCHRE)
COLORNAME("yellow olive", RAL_YELLOW_OLIVE)
COLORNAME("yellow orange", RAL_YELLOW_ORANGE)
COLORNAME("yellow process", L_YELLOW_PROCESS)
COLORNAME("yellow ryb", L_YELLOW_RYB)
COLORNAME("yellow tan", X_YELLOW_TAN)
COLORNAME("yellowgreen", X_YELLOWGREEN)
COLORNAME("yellowish", X_YELLOWISH)
COLORNAME("yellowish brown", X_YELLOWISH_BROWN)
COLORNAME("yellowish green", X_YELLOWISH_GREEN)
COLORNAME("yellowish orange", X_YELLOWISH_ORANGE)
COLORNAME("yellowish tan", X_YELLOWISH_TAN)
COLORNAME("yellowy brown", X_YELLOWY_BROWN)
COLORNAME("yellowy green", X_YELLOWY_GREEN)
COLORNAME("you really got me", CL_YOU_REALLY_GOT_ME)
COLORNAME("zaffre", L_ZAFFRE)
COLORNAME("zinc yellow", RAL_ZINC_YELLOW)
COLORNAME("zinnwaldite brown", L_ZINNWALDITE_BROWN)
};

#undef COLORNAME

const int number_named_colors = sizeof(rgbcolor_names) / sizeof(rgbcolor_names[0]);

/* check that the color name sort is good -- for debug use */
void debug_verify_color_name_sort(void) {
	int i;

	for (i = 1; i < number_named_colors; ++i) {
		if (strcmp(rgbcolor_names[i - 1].name, rgbcolor_names[i].name) >= 0)
			printf("color names out of order: %s and %s\n",
					rgbcolor_names[i - 1].name,
					rgbcolor_names[i].name);
	}
}

/* get a string name for a color, if we know it */
const char* NameFromRGBColor(RGBColor rgb) {
	int i;
	for (i = number_named_colors - 1; i >= 0; --i) {
		if (rgbcolor_names[i].rgb == rgb)
			return rgbcolor_names[i].name;
	}

	return(NULL);
}

const char* ClosestNameToRGBColor(RGBColor rgb, u32* d_out) {
	u32 dist = 999999999UL;
	const char* ret = nullptr;
	int i;

	for (i = number_named_colors - 1; i >= 0; --i) {
		u32 dc = 0;
		int d;
		d = (int)RGB_RED(rgbcolor_names[i].rgb) - (int)RGB_RED(rgb);
		dc += d * d;
		d = (int)RGB_GREEN(rgbcolor_names[i].rgb) - (int)RGB_GREEN(rgb);
		dc += d * d;
		d = (int)RGB_BLUE(rgbcolor_names[i].rgb) - (int)RGB_BLUE(rgb);
		dc += d * d;
		if (dc < dist) {
			dist = dc;
			ret = rgbcolor_names[i].name;
			if (d_out != nullptr) {
				*d_out = dist;
			}
		}
		if (0 == dist) {
			break;
		}
	}

	return(ret);
}

/*** Helper function for binary search-by-color name ***/
static int __clrname_cmp(const void* strv, const void *cmp) {
	ColorNames *clrname = (ColorNames *)cmp;
	char* str = *((char **)strv);

	return(__stricmp(str, clrname->name));
}


/* get an RGBColor from a string name */
RGBColor RGBColorFromName(const char* name) {
	ColorNames *f;

	f = (ColorNames *)bsearch(&name, rgbcolor_names, array_size(rgbcolor_names), sizeof(rgbcolor_names[0]), __clrname_cmp);
	if (is_null(f))
		return(INVALID_COLOR);

	return f->rgb;
}

/* make an RGBColor lighter or darker */
extern RGBColor RGBColorDarkenBrighten(RGBColor rgb, double factor) {
	double r, g, b;
	r = (double)RGB_RED(rgb);
	g = (double)RGB_GREEN(rgb);
	b = (double)RGB_BLUE(rgb);
	r *= factor;
	g *= factor;
	b *= factor;
	r = COMPONENT_RANGE(r);
	g = COMPONENT_RANGE(g);
	b = COMPONENT_RANGE(b);
	return (RGBColor)RGB_NO_CHECK((u32)floor(r + 0.5),
							(u32)floor(g + 0.5),
							(u32)floor(b + 0.5));
}

/* as above, but avoid floating-point math */
extern RGBColor RGBColorDarkenBrightenRational(RGBColor rgb, u32 num, u32 den) {
	u32 r, g, b;
	r = RGB_RED(rgb);
	g = RGB_GREEN(rgb);
	b = RGB_BLUE(rgb);
	r *= num;
	g *= num;
	b *= num;
	r /= den;
	g /= den;
	b /= den;
	r = COMPONENT_RANGE(r);
	g = COMPONENT_RANGE(g);
	b = COMPONENT_RANGE(b);
	return (RGBColor)RGB_NO_CHECK(r, g, b);
}

/* extract the grayscale level of the given color */
u32 RGBColorGrayscaleLevel(RGBColor rgb) {
	u32 r, g, b;


	r = RGB_RED(rgb);
	g = RGB_GREEN(rgb);
	b = RGB_BLUE(rgb);

	return (r + g + b) / 3UL;
}

/* alternate grayscale level function -- weighted red 33%, green 56%, blue 11%. */
u32 RGBColorGrayscaleLevelWeighted(RGBColor rgb) {
	u32 r, g, b;


	r = RGB_RED(rgb);
	g = RGB_GREEN(rgb);
	b = RGB_BLUE(rgb);

	return (r * 33 + g * 56 + b * 11) / 100UL;
}

/* convert an RGB color to gray scale */
u32 RGBColorToGrayscale(RGBColor rgb) {
	u32 gs = RGBColorGrayscaleLevel(rgb);

	return (RGB_NO_CHECK(gs, gs, gs));
}

/* Alternate grayscale conversion -- weighted red 33%, green 56%, blue 11%. */
u32 RGBColorToGrayscaleWeighted(RGBColor rgb) {
	uint r, g, b;
	uint c;
	r = RGB_RED(rgb);
	g = RGB_GREEN(rgb);
	b = RGB_BLUE(rgb);
	c = (g * 56 + r * 33 + b * 11) / 100UL;
	return (RGB_NO_CHECK(c, c, c));
}

/*** Returns the color for a given temperature (in Kelvin). The most interesting range for imaging purposes is
	about [1500 K, 15000 K]. ***/
RGBColor temperaturecolor(u32 kelvin) {
	double k = (double)kelvin;
	double rr, gg, bb;
	int r, g, b;

	k *= 0.01;
	if (k <= 66.)
		rr = 255.;
	else
		{
		rr = k - 60.;
		rr = 329.698727446 * pow(rr, -0.1332047592);
		}
	if (k <= 66.)
		{
		gg = k;
		gg = 99.4708025861 * log(gg) - 161.1195681661;
		}
	else
		{
		gg = k - 60.;
		gg = 288.1221695283 * pow(gg, -0.0755148492);
		}

	if (k >= 66.)
		bb = 255.;
	else
		{
		if (k <= 19.)
			bb = 0.;
		else
			{
			bb = k - 10.0;
			bb = 138.5177312231 * log(bb) - 305.0447927307;
			}
		}

	r = ROUND_FLOAT_TO_INT(rr);
	g = ROUND_FLOAT_TO_INT(gg);
	b = ROUND_FLOAT_TO_INT(bb);

	r = COMPONENT_RANGE(r);
	g = COMPONENT_RANGE(g);
	b = COMPONENT_RANGE(b);
	
	return RGB_NO_CHECK(r, g, b);
}

/*** Adjust the color so that the highest-intensity component of the color so it is equal to amount (0-255). Preserves alpha channel. ***/
RGBColor modify_intensity(RGBColor c, uint amount) {
	uint r, g, b, a, mx;
	amount = CLAMP(amount, 0x00, 0xFF);
	if (iszero(amount))
		return(C_BLACK);
	r = RGB_RED(c);
	g = RGB_GREEN(c);
	b = RGB_BLUE(c);
	a = RGB_ALPHA(c);
	mx = r;
	if (g > mx)
		mx = g;
	if (b > mx)
		mx = b;
	if (!iszero(mx))
		{
		r *= amount;
		g *= amount;
		b *= amount;
		r /= mx;
		g /= mx;
		b /= mx;
		}
	return RGBA(r, g, b, a);
}

/*** As modify_intensity, but changes the color to maximum intensity ***/
RGBColor full_intensity(RGBColor c) {
	return modify_intensity(c, 0xFF);
}

/*** Ensure that maximum intensity of the color c is at most max_intensity; scale components down evenly if necessary. ***/
RGBColor fade_intensity(RGBColor c, uint max_intensity) {
	uint r, g, b, a, mx;
	max_intensity = CLAMP(max_intensity, 0x00, 0xFF);
	if (iszero(max_intensity))
		return(C_BLACK);
	r = RGB_RED(c);
	g = RGB_GREEN(c);
	b = RGB_BLUE(c);
	a = RGB_ALPHA(c);
	mx = r;
	if (g > mx)
		mx = g;
	if (b > mx)
		mx = b;
	if (mx < max_intensity)
		return(c);
	if (!iszero(mx))
		{
		r *= max_intensity;
		g *= max_intensity;
		b *= max_intensity;
		r /= mx;
		g /= mx;
		b /= mx;
		}
	return RGBA(r, g, b, a);
}


/* end colors.cpp */
