/***

	currcode.cpp

	ISO-4217 three letter currency codes for each nation.

	Copyright (c) 2014-2022 C. M. Street.

***/

#define	CURRENCY(x, y)		{ x, y },
	
/*** Currency codes by nation. ***/
static const char* __currency_iso4217[][2] = {
CURRENCY("Afghanistan", "AFN")
CURRENCY("Albania", "ALL")
CURRENCY("Algeria", "DZD")
CURRENCY("American Samoa", "USD")
CURRENCY("Angola", "AOA")
CURRENCY("Anguilla", "XCD")
CURRENCY("Antigua and Barbuda", "XCD")
CURRENCY("Argentina", "ARS")
CURRENCY("Armenia", "AMD")
CURRENCY("Aruba", "AWG")
CURRENCY("Australia", "AUD")
CURRENCY("Austria", "EUR")
CURRENCY("Azerbaijan", "AZN")
CURRENCY("Bahamas", "BSD")
CURRENCY("Bahrain", "BHD")
CURRENCY("Barbados", "BBD")
CURRENCY("Bangladesh", "BDT")
CURRENCY("BCEAO Franc", "XOF")
CURRENCY("Belarus", "BYR")
CURRENCY("Belgium", "EUR")
CURRENCY("Belize", "BZD")
CURRENCY("Benin", "XOF")
CURRENCY("Bermuda", "BMD")
CURRENCY("Bhutan", "BTN")
CURRENCY("Bolivia", "BOB")
CURRENCY("Bosnia & Herzegovina", "BAM")
CURRENCY("Bosnia and Herzegovina", "BAM")
CURRENCY("Botswana", "BWP")
CURRENCY("Brazil", "BRL")
CURRENCY("British Virgin Islands", "USD")
CURRENCY("Brunei", "BND")
CURRENCY("Brunei Darussalam", "BND")
CURRENCY("Bulgaria", "BGN")
CURRENCY("Burkina Faso", "XOF")
CURRENCY("Burma", "MMK")
CURRENCY("Burundi", "BIF")
CURRENCY("Cambodia", "KHR")
CURRENCY("Cameroon", "XAF")
CURRENCY("Canada", "CAD")
CURRENCY("Cape Verde", "CVE")
CURRENCY("Cayman Islands", "KYD")
CURRENCY("Central African Republic", "XAF")
CURRENCY("CFA Franc", "XAF")
CURRENCY("CFP Franc", "XPF")
CURRENCY("Chad", "XAf")
CURRENCY("Chile", "CLP")
CURRENCY("China", "CNY")
CURRENCY("Colombia", "COP")
CURRENCY("Comoros", "KMF")
CURRENCY("Congo (Brazzaville)", "XAF")
CURRENCY("Congo (Kinshasa)", "CDF")
CURRENCY("Costa Rica", "CRC")
CURRENCY("Croatia", "HRK")
CURRENCY("Cuba", "CUP")
CURRENCY("Cuba (Convertible Peso)", "CUC")
CURRENCY("Cyprus", "EUR")
CURRENCY("Czech Republic", "CZK")
CURRENCY("Denmark", "DKK")
CURRENCY("Djibouti", "DJF")
CURRENCY("Dominica", "XCD")
CURRENCY("Dominican Republic", "DOP")
CURRENCY("East Caribbean Dollar", "XCD")
CURRENCY("East Timor", "USD")
CURRENCY("Ecuador", "USD")
CURRENCY("Egypt", "EGP")
CURRENCY("El Salvador", "SVC")
CURRENCY("Equitorial Guinea", "XAF")
CURRENCY("Eritrea", "ERN")
CURRENCY("Estonia", "EUR")
CURRENCY("Ethiopia", "ETB")
CURRENCY("Eurozone", "EUR")
CURRENCY("Falkland Islands", "FKP")
CURRENCY("Finland", "EUR")
CURRENCY("Fiji", "FJD")
CURRENCY("France", "EUR")
CURRENCY("Gabon", "XAF")
CURRENCY("Gambia", "GMD")
CURRENCY("Georgia", "GEL")
CURRENCY("Germany", "EUR")
CURRENCY("Ghana", "GHS")
CURRENCY("Gibraltar", "GIP")
CURRENCY("Great Britain", "GBP")
CURRENCY("Greece", "EUR")
CURRENCY("Grenada", "XCD")
CURRENCY("Guam", "USD")
CURRENCY("Guatemala", "GTQ")
CURRENCY("Guernsey", "GGP")
CURRENCY("Guinea", "GNF")
CURRENCY("Guinea-Bissau", "XOF")
CURRENCY("Guyana", "GYD")
CURRENCY("Haiti", "HTG")
CURRENCY("Hong Kong", "HKD")
CURRENCY("Honduras", "HNL")
CURRENCY("Hungary", "HUF")
CURRENCY("Iceland", "ISK")
CURRENCY("India", "INR")
CURRENCY("Indonesia", "IDR")
CURRENCY("Iran", "IRR")
CURRENCY("Iraq", "IQD")
CURRENCY("Ireland", "EUR")
CURRENCY("Isle of Man", "IMP")
CURRENCY("Israel", "ILS")
CURRENCY("Italy", "EUR")
CURRENCY("Ivory Coast", "XOF")
CURRENCY("Jamaica", "JMD")
CURRENCY("Japan", "JPY")
CURRENCY("Jersey", "JEP")
CURRENCY("Jordan", "JOD")
CURRENCY("Kazakhstan", "KZT")
CURRENCY("Kenya", "KES")
CURRENCY("Kuwait", "KWD")
CURRENCY("Kyrgyzstan", "KGS")
CURRENCY("Laos", "LAK")
CURRENCY("Latvia", "EUR")
CURRENCY("Lebanon", "LBP")
CURRENCY("Lesotho", "LSL")
CURRENCY("Liberia", "LRD")
CURRENCY("Libya", "LYD")
CURRENCY("Lithuania", "EUR")
CURRENCY("Luxembourg", "EUR")
CURRENCY("Macau", "MOP")
CURRENCY("Macedonia", "MKD")
CURRENCY("Madagascar", "MGA")
CURRENCY("Malawi", "MWK")
CURRENCY("Malaysia", "MYR")
CURRENCY("Maldives", "MVR")
CURRENCY("Mali", "XOF")
CURRENCY("Malta", "EUR")
CURRENCY("Marshall Islands", "USD")
CURRENCY("Mauritania", "MRO")
CURRENCY("Mauritius", "MUR")
CURRENCY("Mexico", "MXN")
CURRENCY("Micronesia", "USD")
CURRENCY("Moldova", "MDL")
CURRENCY("Mongolia", "MTN")
CURRENCY("Montserrat", "XCD")
CURRENCY("Morocco", "MAD")
CURRENCY("Mozambique", "MZN")
CURRENCY("Myanmar", "MMK")
CURRENCY("Namibia", "NAD")
CURRENCY("Nepal", "NPR")
CURRENCY("Netherlands", "EUR")
CURRENCY("New Zealand", "NZD")
CURRENCY("Nicarague", "NIO")
CURRENCY("Niger", "XOF")
CURRENCY("Nigeria", "NGN")
CURRENCY("Netherlands Antilles", "ANG")
CURRENCY("North Korea", "KPW")
CURRENCY("Northern Mariana Islands", "USD")
CURRENCY("Norway", "NOK")
CURRENCY("Oman", "OMR")
CURRENCY("Pakistan", "PKR")
CURRENCY("Palau", "USD")
CURRENCY("Panama", "PAB")
CURRENCY("Papua New Guinea", "PGK")
CURRENCY("Paraguay", "PYG")
CURRENCY("Peru", "PEN")
CURRENCY("Philippines", "PHP")
CURRENCY("Poland", "PLN")
CURRENCY("Portugal", "EUR")
CURRENCY("Puerto Rico", "USD")	
CURRENCY("Qatar", "QAR")
CURRENCY("Romania", "RON")
CURRENCY("Russia", "RUB")
CURRENCY("Rwanda", "RWF")
CURRENCY("Samoa", "WST")
CURRENCY("Sao Tome & Principe", "STD")
CURRENCY("Saudi Arabia", "SAR")
CURRENCY("Senegal", "XOF")
CURRENCY("Serbia", "RSD")
CURRENCY("Seychelles", "SCR")
CURRENCY("Sierra Leone", "SLL")
CURRENCY("Singapore", "SGD")
CURRENCY("Slovakia", "EUR")
CURRENCY("Slovenia", "EUR")
CURRENCY("Solomon Islands", "SBD")
CURRENCY("Somalia", "SOS")
CURRENCY("South Africa", "ZAR")
CURRENCY("South Korea", "KRW")
CURRENCY("Spain", "EUR")
CURRENCY("Sri Lanka", "LKR")
CURRENCY("St. Helena", "SHP")
CURRENCY("St. Kitts and Nevis", "XCD")
CURRENCY("St. Lucia", "XCD")
CURRENCY("St. Thomas and Prince", "STD")
CURRENCY("St. Vincent and the Grenadines", "XCD")
CURRENCY("Sudan", "SDG")
CURRENCY("Suriname", "SRD")
CURRENCY("Swaziland", "SZL")
CURRENCY("Sweden", "SEK")
CURRENCY("Switzerland", "CHF")
CURRENCY("Syria", "SYP")
CURRENCY("Taiwan", "TWD")
CURRENCY("Tajikistan", "TJS")
CURRENCY("Tanzania", "TZS")
CURRENCY("Thailand", "THB")
CURRENCY("Togo", "XOF")
CURRENCY("Tonga", "TOP")
CURRENCY("Trinidad & Tobago", "TTD")
CURRENCY("Trinidad and Tobago", "TTD")
CURRENCY("Tunisia", "TND")
CURRENCY("Turkey", "TRY")
CURRENCY("Turkmenistan", "TMT")
CURRENCY("Tuvalu", "TVD")
CURRENCY("UAE", "AED")
CURRENCY("UK", "GBP")
CURRENCY("USA", "USD")
CURRENCY("Uganda", "UGX")
CURRENCY("Ukraine", "UAH")
CURRENCY("United Arab Emirates", "AED")
CURRENCY("United Kingdom", "GBP")
CURRENCY("United States", "USD")
CURRENCY("Uruguay", "UYU")
CURRENCY("Uzbekistan", "UZS")
CURRENCY("Vanuatu", "VUV")
CURRENCY("Venezuela", "VEF")
CURRENCY("Vietnam", "VND")
CURRENCY("Yemen", "YER")
CURRENCY("Zambia", "ZMW")
CURRENCY("Zimbabwe", "ZWD")
};

#undef CURRENCY

void debug_verify_currency_sort(void)
{
	int la = array_size(__currency_iso4217);
	int e;

	la -= 2;
	for (e = la; e >= 0; --e)
		{
		if (strcmp(__currency_iso4217[e][0], __currency_iso4217[e + 1][0]) >= 0)
			{
			printf("Bad sort: %d %s, %d %s\n", e, __currency_iso4217[e][0],
				(e + 1), __currency_iso4217[e + 1][0]);
			}
		}
}

const char* currency_iso4217_for_country(const char country[])
{
	// reuse __irregular_comp() from plurals.cpp
	extern int __irregular_comp(const void* v1, const void* v2);
	char** c;

	c = (char**)asearch(country, __currency_iso4217, array_size(__currency_iso4217), __irregular_comp);

	if (is_null(c))
		return(NULL);

	return __currency_iso4217[(c - (char**)__currency_iso4217) >> 1][1];
}

/*** end currcode.cpp ***/