/***

	plurals.cpp

	Returns the plural of an English word. Handles a large number of irregular plurals and 
	loanwords. Won't get every case correct, but handles a great many of them.

	Also matches the capitalization of the input. (Simply goes character for character, and 
	if we run out of characters in the input string we stick with the last case.) 

	plural_phrase() is slightly more general as it attempts to understand things like "can 
	of soup", "bagful of marbles", and "slice of life".

	Both functions will fail on input strings greater than 250 characters in length.

	Author: C. M. Street

	Copyright (c) 2014-2022 Chris Street

***/
#include "libcodehappy.h"

#define	IRREGULAR(x, y)		{ x, y },

/*** Just some of the irregular pluralizations found in English. ***/
/*** this must be alphabetized by the singular word ***/
static const char* __irregular_plurals[][2] = {

IRREGULAR("aardwolf", "aardwolves")
IRREGULAR("abdomen", "abdomina")
IRREGULAR("acarus", "acari")
IRREGULAR("accused", "accused")
IRREGULAR("acetum", "aceta")
IRREGULAR("addendum", "addenda")
IRREGULAR("adieu", "adieux")
IRREGULAR("afterlife", "afterlives")
IRREGULAR("agape", "agapai")
IRREGULAR("agenesis", "ageneses")
IRREGULAR("agnomen", "agnomina")
IRREGULAR("agon", "agones")
IRREGULAR("agora", "agorae")
IRREGULAR("airbus", "airbusses")
IRREGULAR("aircraft", "aircraft")
IRREGULAR("albedo", "albedoes")
IRREGULAR("alewife", "alewives")
IRREGULAR("alga", "algae")
IRREGULAR("alkali", "alkalies")
IRREGULAR("alumna", "alumnae")
IRREGULAR("alumnus", "alumni")
IRREGULAR("amicus", "amici")
IRREGULAR("amoeba", "amoebae")
IRREGULAR("analysis", "analyses")
IRREGULAR("animato", "animati")
IRREGULAR("animus", "animi")
IRREGULAR("annulus", "annuli")
IRREGULAR("antenna", "antennae")
IRREGULAR("antihero", "antiheroes")
IRREGULAR("antipasto", "antipasti")
IRREGULAR("antithesis", "antitheses")
IRREGULAR("antrum", "antra")
IRREGULAR("aorta", "aortae")
IRREGULAR("apex", "apices")
IRREGULAR("appendix", "appendices")
IRREGULAR("aquarium", "aquaria")
IRREGULAR("arboretum", "arboreta")
IRREGULAR("arco", "archi")
IRREGULAR("areola", "areolae")
IRREGULAR("argumentum", "argumenta")
IRREGULAR("armful", "armsful")
IRREGULAR("arroz", "arroces")
IRREGULAR("asylum", "asyla")
IRREGULAR("atrium", "atria")
IRREGULAR("att", "att")
IRREGULAR("auditorium", "auditoria")
IRREGULAR("aureus", "aurei")
IRREGULAR("autobahn", "autobahnen")
IRREGULAR("autolysis", "autolyses")
IRREGULAR("automaton", "automata")
IRREGULAR("avgas", "avgasses")
IRREGULAR("aviatrix", "aviatrices")
IRREGULAR("avifauna", "avifaunae")
IRREGULAR("avocado", "avocadoes")
IRREGULAR("axis", "axes")
IRREGULAR("baal", "baalim")
IRREGULAR("bacillus", "bacilli")
IRREGULAR("bacterium", "bacteria")
IRREGULAR("bagful", "bagsful")
IRREGULAR("balista", "balistae")
IRREGULAR("bambino", "bambini")
IRREGULAR("bandeau", "bandeaux")
IRREGULAR("banjo", "banjoes")
IRREGULAR("barricado", "barricadoes")
IRREGULAR("basilica", "basilicae")
IRREGULAR("basis", "bases")
IRREGULAR("bayman", "baymen")
IRREGULAR("beau", "beaux")
IRREGULAR("beefalo", "beefaloes")
IRREGULAR("behalf", "behalves")
IRREGULAR("bendy", "bendys")
IRREGULAR("berceau", "berceaux")
IRREGULAR("bhaji", "bhajia")
IRREGULAR("bhat", "bhat")
IRREGULAR("bialy", "bialys")
IRREGULAR("biennium", "biennia")
IRREGULAR("bigfoot", "bigfeet")
IRREGULAR("bijou", "bijoux")
IRREGULAR("bilbo", "bilboes")
IRREGULAR("bimbo", "bimboes")
IRREGULAR("bingo", "bingoes")
IRREGULAR("biogas", "biogasses")
IRREGULAR("birdlife", "birdlife")
IRREGULAR("birr", "birrotch")
IRREGULAR("biscotto", "biscotti")
IRREGULAR("bisectrix", "bisectrices")
IRREGULAR("bison", "bison")
IRREGULAR("biz", "bizzes")
IRREGULAR("blastoma", "blastomae")
IRREGULAR("blowby", "blowbys")
IRREGULAR("bluecurls", "bluecurls")
IRREGULAR("buffalo", "buffalo")
IRREGULAR("bupkes", "bupkes")
IRREGULAR("bupkis", "bupkis")
IRREGULAR("bupkus", "bupkus")
IRREGULAR("bureau", "bureaux")
IRREGULAR("bus", "busses")
IRREGULAR("buttinski", "buttinskies")
IRREGULAR("by", "bys")
IRREGULAR("cactus", "cacti")
IRREGULAR("cacumen", "cacumina")
IRREGULAR("caduceus", "caducei")
IRREGULAR("cafetorium", "cafetoria")
IRREGULAR("cajon", "cajones")
IRREGULAR("calculus", "calculi")
IRREGULAR("calf", "calves")
IRREGULAR("calico", "calicoes")
IRREGULAR("calix", "calices")
IRREGULAR("calx", "calces")
IRREGULAR("calypso", "calypsoes")
IRREGULAR("calyx", "calyces")
IRREGULAR("calzone", "calzoni")
IRREGULAR("camaieu", "camaieux")
IRREGULAR("campo", "campi")
IRREGULAR("canful", "cansful")
IRREGULAR("canula", "canulae")
IRREGULAR("capo", "capi")
IRREGULAR("caput", "capita")
IRREGULAR("cargoose", "cargeese")
IRREGULAR("carina", "carinae")
IRREGULAR("carpale", "carpalia")
IRREGULAR("casino", "casini")
IRREGULAR("castrato", "castrati")
IRREGULAR("casus", "casus")
IRREGULAR("catalysis", "catalyses")
IRREGULAR("cattalo", "cattaloes")
IRREGULAR("cattle", "cattle")
IRREGULAR("causa", "causae")
IRREGULAR("cecum", "ceca")
IRREGULAR("cello", "celli")
IRREGULAR("centesimo", "centesimi")
IRREGULAR("cento", "centones")
IRREGULAR("centu", "centu")
IRREGULAR("cervix", "cervices")
IRREGULAR("chablis", "chablis")
IRREGULAR("chalah", "chalot")
IRREGULAR("challah", "challot")
IRREGULAR("chalutz", "chalutzim")
IRREGULAR("chamois", "chamoix")
IRREGULAR("chapeau", "chapeaux")
IRREGULAR("charisma", "charismata")
IRREGULAR("chateau", "chateaux")
IRREGULAR("chazan", "chazanim")
IRREGULAR("chazzan", "chazzanim")
IRREGULAR("chazzen", "chazzenim")
IRREGULAR("cheder", "chadarim")
IRREGULAR("cherub", "cherubim")
IRREGULAR("chiao", "chiao")
IRREGULAR("chiarezza", "chiarezze")
IRREGULAR("child", "children")
IRREGULAR("chou", "choux")
IRREGULAR("chrismon", "chrisma")
IRREGULAR("chrysalis", "chrysalides")
IRREGULAR("chumash", "chumashim")
IRREGULAR("chuppah", "chuppot")
IRREGULAR("cicada", "cicadae")
IRREGULAR("cimex", "cimices")
IRREGULAR("cirrhosis", "cirrhoses")
IRREGULAR("cirrus", "cirri")
IRREGULAR("cisco", "ciscoes")
IRREGULAR("clarino", "clarini")
IRREGULAR("clitoris", "clitorides")
IRREGULAR("cloaca", "cloacae")
IRREGULAR("coccyx", "coccyges")
IRREGULAR("cochlea", "cochleae")
IRREGULAR("codex", "codices")
IRREGULAR("cognomen", "cognomina")
IRREGULAR("colby", "colbys")
IRREGULAR("commando", "commandoes")
IRREGULAR("compendium", "compendia")
IRREGULAR("conceptus", "concepti")
IRREGULAR("conch", "conches")
IRREGULAR("confetto", "confetti")
IRREGULAR("congo", "congoes")
IRREGULAR("consortium", "consortia")
IRREGULAR("contagium", "contagia")
IRREGULAR("copula", "copulae")
IRREGULAR("corf", "corves")
IRREGULAR("cornea", "corneae")
IRREGULAR("corno", "corni")
IRREGULAR("corps", "corps")
IRREGULAR("corpus", "corpora")
IRREGULAR("cortex", "cortices")
IRREGULAR("costa", "costae")
IRREGULAR("coulis", "coulis")
IRREGULAR("coxa", "coxae")
IRREGULAR("coz", "cozzes")
IRREGULAR("crambo", "cramboes")
IRREGULAR("cranium", "crania")
IRREGULAR("creepmouse", "creepmice")
IRREGULAR("crescendo", "crescendi")
IRREGULAR("crisis", "crises")
IRREGULAR("criterion", "criteria")
IRREGULAR("crocus", "croci")
IRREGULAR("croquis", "croquis")
IRREGULAR("crowfoot", "crowfeet")
IRREGULAR("crowsfoot", "crowsfeet")
IRREGULAR("cruor", "cruores")
IRREGULAR("crusado", "crusadoes")
IRREGULAR("crux", "cruces")
IRREGULAR("cubitus", "cubiti")
IRREGULAR("culmen", "culmina")
IRREGULAR("culpa", "culpae")
IRREGULAR("cupula", "cupulae")
IRREGULAR("curia", "curiae")
IRREGULAR("curriculum", "curricula")
IRREGULAR("cuz", "cuzzes")
IRREGULAR("cyclops", "cyclopes")
IRREGULAR("cylix", "cylices")
IRREGULAR("cymbalo", "cymbaloes")
IRREGULAR("databus", "databusses")
IRREGULAR("datum", "data")
IRREGULAR("decennium", "decennia")
IRREGULAR("deer", "deer")
IRREGULAR("delf", "delves")
IRREGULAR("denar", "denari")
IRREGULAR("desperado", "desperadoes")
IRREGULAR("detritus", "detritus")
IRREGULAR("deus", "dei")
IRREGULAR("diagnosis", "diagnoses")
IRREGULAR("dialysis", "dialyses")
IRREGULAR("diazo", "diazoes")
IRREGULAR("dictatrix", "dictatrices")
IRREGULAR("dictum", "dicta")
IRREGULAR("dido", "didoes")
IRREGULAR("die", "dice")
IRREGULAR("dildo", "dildoes")
IRREGULAR("diluvium", "diluvia")
IRREGULAR("diminuendo", "diminuendoes")
IRREGULAR("dingo", "dingoes")
IRREGULAR("diploma", "diplomata")
IRREGULAR("directrix", "directrices")
IRREGULAR("discus", "disci")
IRREGULAR("distaff", "distaves")
IRREGULAR("djinni", "djinn")
IRREGULAR("doblon", "doblones")
IRREGULAR("dochimus", "dochmii")
IRREGULAR("dodo", "dodoes")
IRREGULAR("dogma", "dogmata")
IRREGULAR("domino", "dominoes")
IRREGULAR("dormouse", "dormice")
IRREGULAR("dosa", "dosai")
IRREGULAR("drachma", "drachmae")
IRREGULAR("dry", "drys")
IRREGULAR("dryad", "dryades")
IRREGULAR("duce", "duci")
IRREGULAR("duello", "duelli")
IRREGULAR("duetto", "duetti")
IRREGULAR("dumka", "dumky")
IRREGULAR("duo", "dui")
IRREGULAR("duodenum", "duodena")
IRREGULAR("duomo", "duomi")
IRREGULAR("dux", "duces")
IRREGULAR("dwarf", "dwarves")
IRREGULAR("dybbuk", "dybbukim")
IRREGULAR("earthwolf", "earthwolves")
IRREGULAR("eau", "eaux")
IRREGULAR("echo", "echoes")
IRREGULAR("edema", "edemata")
IRREGULAR("editrix", "editrices")
IRREGULAR("effluvium", "effluvia")
IRREGULAR("eidolon", "eidola")
IRREGULAR("eidos", "eide")
IRREGULAR("eikon", "eikones")
IRREGULAR("elf", "elves")
IRREGULAR("ellipsis", "ellipses")
IRREGULAR("eluvium", "eluvia")
IRREGULAR("emacs", "emacsen")
IRREGULAR("emblema", "emblemata")
IRREGULAR("emerita", "emeritae")
IRREGULAR("emesis", "emeses")
IRREGULAR("emphasis", "emphases")
IRREGULAR("emporium", "emporia")
IRREGULAR("endleaf", "endleaves")
IRREGULAR("enema", "enemata")
IRREGULAR("enigma", "enigmata")
IRREGULAR("ens", "entia")
IRREGULAR("entremes", "entremes")
IRREGULAR("entremets", "entremets")
IRREGULAR("enuresis", "enureses")
IRREGULAR("ephemera", "ephemerae")
IRREGULAR("epoch", "epochs")
IRREGULAR("erf", "erven")
IRREGULAR("eringo", "eringoes")
IRREGULAR("erratum", "errata")
IRREGULAR("esophagus", "esophagi")
IRREGULAR("excerptum", "excerpta")
IRREGULAR("executrix", "executrices")
IRREGULAR("exegesis", "exegeses")
IRREGULAR("exodus", "exodoi")
IRREGULAR("eyetooth", "eyeteeth")
IRREGULAR("eyrir", "aurar")
IRREGULAR("facia", "faciae")
IRREGULAR("facies", "facies")
IRREGULAR("factum", "facta")
IRREGULAR("facula", "faculae")
IRREGULAR("fagotto", "fagotti")
IRREGULAR("falaj", "aflaj")
IRREGULAR("falcula", "falculae")
IRREGULAR("falx", "falces")
IRREGULAR("fandango", "fandangoes")
IRREGULAR("farmwife", "farmwives")
IRREGULAR("farrago", "farragoes")
IRREGULAR("fasces", "fasces")
IRREGULAR("fatso", "fatsoes")
IRREGULAR("fauna", "faunae")
IRREGULAR("feminie", "feminie")
IRREGULAR("femur", "femora")
IRREGULAR("fenks", "fenks")
IRREGULAR("fermata", "fermate")
IRREGULAR("fez", "fezzes")
IRREGULAR("fiasco", "fiascoes")
IRREGULAR("fibula", "fibulae")
IRREGULAR("fieldmouse", "fieldmice")
IRREGULAR("fish", "fish")
IRREGULAR("flagellum", "flagella")
IRREGULAR("flagstaff", "flagstaves")
IRREGULAR("flambeau", "flambeaux")
IRREGULAR("flamingo", "flamingoes")
IRREGULAR("flatfoot", "flatfeet")
IRREGULAR("flora", "florae")
IRREGULAR("flyby", "flybys")
IRREGULAR("flyleaf", "flyleaves")
IRREGULAR("focus", "foci")
IRREGULAR("folium", "folia")
IRREGULAR("folklife", "folklives")
IRREGULAR("foot", "feet")
IRREGULAR("forceps", "forcipes")
IRREGULAR("forefoot", "forefeet")
IRREGULAR("forehoof", "forehooves")
IRREGULAR("foretooth", "foreteeth")
IRREGULAR("forkful", "forksful")
IRREGULAR("formula", "formulae")
IRREGULAR("fornix", "fornices")
IRREGULAR("forum", "fora")
IRREGULAR("forzando", "forzandi")
IRREGULAR("fossula", "fossulae")
IRREGULAR("fresco", "frescoes")
IRREGULAR("fulcrum", "fulcra")
IRREGULAR("fumado", "fumadoes")
IRREGULAR("fungo", "fungoes")
IRREGULAR("fungus", "fungi")
IRREGULAR("gaijin", "gaijin")
IRREGULAR("gas", "gasses")
IRREGULAR("gasthaus", "gasthauser")
IRREGULAR("gastritis", "gastritides")
IRREGULAR("gateau", "gateaux")
IRREGULAR("gazebo", "gazeboes")
IRREGULAR("gecko", "geckoes")
IRREGULAR("gemma", "gemmae")
IRREGULAR("genesis", "geneses")
IRREGULAR("genus", "genera")
IRREGULAR("germen", "germina")
IRREGULAR("gestalt", "gestalten")
IRREGULAR("get", "gittin")
IRREGULAR("ghetto", "ghettoes")
IRREGULAR("giga", "gighe")
IRREGULAR("gingko", "gingkoes")
IRREGULAR("ginkgo", "ginkgoes")
IRREGULAR("gladiolus", "gladioli")
IRREGULAR("gleba", "glebae")
IRREGULAR("glissando", "glissandi")
IRREGULAR("globus", "globi")
IRREGULAR("gnosis", "gnoses")
IRREGULAR("go", "goes")
IRREGULAR("gobbo", "gobbi")
IRREGULAR("gobo", "goboes")
IRREGULAR("gonium", "gonia")
IRREGULAR("goodby", "goodbys")
IRREGULAR("goodwife", "goodwives")
IRREGULAR("goose", "geese")
IRREGULAR("gopik", "gopik")
IRREGULAR("gospoda", "gospoda")
IRREGULAR("gospodin", "gospodin")
IRREGULAR("gourami", "gouramies")
IRREGULAR("goy", "goyim")
IRREGULAR("gracilis", "graciles")
IRREGULAR("graffito", "graffiti")
IRREGULAR("granuloma", "granulomata")
IRREGULAR("granum", "grana")
IRREGULAR("grapelouse", "grapelice")
IRREGULAR("grosz", "groszy")
IRREGULAR("grotto", "grottoes")
IRREGULAR("grouse", "grouse")
IRREGULAR("gudewife", "gudewives")
IRREGULAR("gules", "gules")
IRREGULAR("gusto", "gustoes")
IRREGULAR("gymnasium", "gymnasia")
IRREGULAR("gynecium", "gynecia")
IRREGULAR("gyrus", "gyri")
IRREGULAR("hachis", "hachis")
IRREGULAR("haftara", "haftarot")
IRREGULAR("haggada", "haggadot")
IRREGULAR("haik", "haika")
IRREGULAR("halacha", "halachot")
IRREGULAR("halakha", "halakhot")
IRREGULAR("halakhah", "halakhoth")
IRREGULAR("haler", "haleru")
IRREGULAR("half", "halves")
IRREGULAR("halflife", "halflives")
IRREGULAR("halfpence", "halfpence")
IRREGULAR("halier", "halierov")
IRREGULAR("halitosis", "halitoses")
IRREGULAR("hallah", "halloth")
IRREGULAR("hallux", "halluces")
IRREGULAR("halutz", "halutzim")
IRREGULAR("handful", "handsful")
IRREGULAR("handkerchief", "handkerchieves")
IRREGULAR("handstaff", "handstaves")
IRREGULAR("hangul", "hangul")
IRREGULAR("haruspex", "haruspices")
IRREGULAR("hatful", "hatsful")
IRREGULAR("hausfrau", "hausfrauen")
IRREGULAR("hautbois", "hautbois")
IRREGULAR("hazan", "hazanim")
IRREGULAR("hazzan", "hazzanim")
IRREGULAR("headscarf", "headscarves")
IRREGULAR("heder", "hedarim")
IRREGULAR("hegumenos", "hegumenoi")
IRREGULAR("helibus", "helibusses")
IRREGULAR("helix", "helices")
IRREGULAR("hello", "helloes")
IRREGULAR("hematosis", "hematoses")
IRREGULAR("henry", "henrys")
IRREGULAR("herbarium", "herbaria")
IRREGULAR("heretrix", "heretrices")
IRREGULAR("heritrix", "heritrices")
IRREGULAR("hernia", "herniae")
IRREGULAR("hero", "heroes")
IRREGULAR("herpes", "herpes")
IRREGULAR("hexahedron", "hexahedra")
IRREGULAR("hillfolk", "hillfolk")
IRREGULAR("hilum", "hila")
IRREGULAR("hoactzin", "hoactzines")
IRREGULAR("hoatzin", "hoatzines")
IRREGULAR("holohedron", "holohedra")
IRREGULAR("hoof", "hooves")
IRREGULAR("hovercraft", "hovercraft")
IRREGULAR("humerus", "humeri")
IRREGULAR("huppah", "huppot")
IRREGULAR("hurricano", "hurricanoes")
IRREGULAR("hwan", "hwan")
IRREGULAR("hydra", "hydrae")
IRREGULAR("hypnosis", "hypnoses")
IRREGULAR("hypothesis", "hypotheses")
IRREGULAR("iambus", "iambi")
IRREGULAR("ibadah", "ibadat")
IRREGULAR("ibex", "ibices")
IRREGULAR("ignoramus", "ignorami")
IRREGULAR("ikebana", "ikebana")
IRREGULAR("ileum", "ilea")
IRREGULAR("ilex", "ilices")
IRREGULAR("ilium", "ilia")
IRREGULAR("impi", "impies")
IRREGULAR("incubus", "incubi")
IRREGULAR("index", "indices")
IRREGULAR("indigo", "indigoes")
IRREGULAR("inertia", "inertiae")
IRREGULAR("inkosi", "amakosi")
IRREGULAR("inro", "inro")
IRREGULAR("inselberg", "inselberge")
IRREGULAR("insigne", "insignia")
IRREGULAR("insula", "insulae")
IRREGULAR("interleaf", "interleaves")
IRREGULAR("interrex", "interreges")
IRREGULAR("intima", "intimae")
IRREGULAR("inukshuk", "inukshuit")
IRREGULAR("inuksuk", "inuksukit")
IRREGULAR("iris", "irides")
IRREGULAR("ischium", "ischia")
IRREGULAR("isodicon", "isodica")
IRREGULAR("isthmus", "isthmi")
IRREGULAR("jackknife", "jackknives")
IRREGULAR("jambeau", "jambeaux")
IRREGULAR("jansky", "janskys")
IRREGULAR("jarful", "jarsful")
IRREGULAR("jejunum", "jejuna")
IRREGULAR("jesus", "jesus")
IRREGULAR("jeu", "jeux")
IRREGULAR("jilbab", "jalabib")
IRREGULAR("jingo", "jingoes")
IRREGULAR("jiz", "jizzes")
IRREGULAR("jugful", "jugsful")
IRREGULAR("jun", "jun")
IRREGULAR("junco", "juncoes")
IRREGULAR("jus", "jura")
IRREGULAR("kabloona", "kabloonat")
IRREGULAR("kaddish", "kaddishim")
IRREGULAR("kalewife", "kalewives")
IRREGULAR("kapeyka", "kapeek")
IRREGULAR("katana", "katana")
IRREGULAR("kayo", "kayoes")
IRREGULAR("kazachok", "kazachki")
IRREGULAR("kazatski", "kazatskies")
IRREGULAR("kerchief", "kerchieves")
IRREGULAR("ketubah", "ketubot")
IRREGULAR("khazen", "khazenim")
IRREGULAR("kibbutz", "kibbutzim")
IRREGULAR("kiddo", "kiddoes")
IRREGULAR("kielbasa", "kielbasy")
IRREGULAR("klezmer", "klezmorim")
IRREGULAR("knaidel", "knaidlach")
IRREGULAR("knife", "knives")
IRREGULAR("kohen", "kohanim")
IRREGULAR("kongoni", "kongoni")
IRREGULAR("koori", "koories")
IRREGULAR("koruna", "koruny")
IRREGULAR("kreplach", "kreplach")
IRREGULAR("kreplech", "kreplech")
IRREGULAR("krona", "kronor")
IRREGULAR("krone", "kroner")
IRREGULAR("kroon", "krooni")
IRREGULAR("krummholz", "krummholz")
IRREGULAR("kueh", "kueh")
IRREGULAR("kurtosis", "kurtoses")
IRREGULAR("kuvasz", "kuvasok")
IRREGULAR("kylix", "kylices")
IRREGULAR("labium", "labia")
IRREGULAR("lamina", "laminae")
IRREGULAR("lapillus", "lapilli")
IRREGULAR("lapsus", "lapsus")
IRREGULAR("larva", "larvae")
IRREGULAR("larynx", "larynges")
IRREGULAR("lat", "latu")
IRREGULAR("latex", "latices")
IRREGULAR("leaf", "leaves")
IRREGULAR("lebkuchen", "lebkuchen")
IRREGULAR("lek", "leku")
IRREGULAR("lemma", "lemmata")
IRREGULAR("lento", "lenti")
IRREGULAR("lepton", "lepta")
IRREGULAR("leu", "leu")
IRREGULAR("lev", "leva")
IRREGULAR("lex", "leges")
IRREGULAR("lexicon", "lexica")
IRREGULAR("lez", "lezzes")
IRREGULAR("libretto", "libretti")
IRREGULAR("lied", "lieder")
IRREGULAR("life", "lives")
IRREGULAR("lingo", "lingoes")
IRREGULAR("lipa", "lipe")
IRREGULAR("lira", "lire")
IRREGULAR("lis", "lisses")
IRREGULAR("litas", "litu")
IRREGULAR("loaf", "loaves")
IRREGULAR("loch", "lochs")
IRREGULAR("locus", "loci")
IRREGULAR("logos", "logoi")
IRREGULAR("longleaf", "longleaves")
IRREGULAR("louse", "lice")
IRREGULAR("lowlife", "lowlives")
IRREGULAR("lumen", "lumina")
IRREGULAR("lunula", "lunulae")
IRREGULAR("lustrum", "lustra")
IRREGULAR("lux", "luces")
IRREGULAR("lyceum", "lycea")
IRREGULAR("maar", "maare")
IRREGULAR("macaroni", "macaronies")
IRREGULAR("macula", "maculae")
IRREGULAR("madame", "mesdames")
IRREGULAR("maestro", "maestri")
IRREGULAR("magma", "magmata")
IRREGULAR("magus", "magi")
IRREGULAR("mahzor", "mahzorim")
IRREGULAR("mambo", "mamboes")
IRREGULAR("man", "men")
IRREGULAR("manchild", "menchildren")
IRREGULAR("mango", "mangoes")
IRREGULAR("markka", "markkaa")
IRREGULAR("mas", "mas")
IRREGULAR("matrix", "matrices")
IRREGULAR("matzo", "matzoth")
IRREGULAR("mausoleum", "mausolea")
IRREGULAR("means", "means")
IRREGULAR("meatloaf", "meatloaves")
IRREGULAR("mediatrix", "mediatrices")
IRREGULAR("medium", "media")
IRREGULAR("melanoma", "melanomata")
IRREGULAR("memento", "mementoes")
IRREGULAR("memorandum", "memoranda")
IRREGULAR("meshugaas", "meshugaasen")
IRREGULAR("mesteso", "mestesoes")
IRREGULAR("mestino", "mestinoes")
IRREGULAR("mestizo", "mestizoes")
IRREGULAR("metabasis", "metabases")
IRREGULAR("metacarpus", "metacarpi")
IRREGULAR("metapelet", "metaplot")
IRREGULAR("metasoma", "metasomata")
IRREGULAR("metatarsus", "metatarsi")
IRREGULAR("metazoon", "metazoa")
IRREGULAR("methysis", "methyses")
IRREGULAR("metis", "metis")
IRREGULAR("metope", "metopae")
IRREGULAR("mezuzah", "mezuzot")
IRREGULAR("miasma", "miasmata")
IRREGULAR("micella", "micellae")
IRREGULAR("microbus", "microbusses")
IRREGULAR("microlux", "microluces")
IRREGULAR("micron", "micra")
IRREGULAR("middleman", "middlemen")
IRREGULAR("midlife", "midlives")
IRREGULAR("midrash", "midrashim")
IRREGULAR("midwife", "midwives")
IRREGULAR("mikron", "mikra")
IRREGULAR("mikvah", "mikvoth")
IRREGULAR("mikveh", "mikvot")
IRREGULAR("milieu", "milieux")
IRREGULAR("milium", "milia")
IRREGULAR("millennium", "millennia")
IRREGULAR("millihenry", "millihenrys")
IRREGULAR("millilux", "milliluces")
IRREGULAR("mimesis", "mimeses")
IRREGULAR("mimosa", "mimosae")
IRREGULAR("mina", "minae")
IRREGULAR("minibus", "minibusses")
IRREGULAR("minimum", "minima")
IRREGULAR("minuteman", "minutemen")
IRREGULAR("minutia", "minutiae")
IRREGULAR("minyan", "minyanim")
IRREGULAR("miosis", "mioses")
IRREGULAR("mir", "miri")
IRREGULAR("miracidium", "miracidia")
IRREGULAR("mirepoix", "mirepoix")
IRREGULAR("mirligoes", "mirligoes")
IRREGULAR("mishegaas", "mishegaasen")
IRREGULAR("mishegoss", "mishegoss")
IRREGULAR("missa", "missae")
IRREGULAR("mitosis", "mitoses")
IRREGULAR("mitsvah", "mitsvoth")
IRREGULAR("mitzvah", "mitzvoth")
IRREGULAR("miz", "mizzes")
IRREGULAR("moai", "moai")
IRREGULAR("mobsman", "mobsmen")
IRREGULAR("mockado", "mockadoes")
IRREGULAR("modello", "modelli")
IRREGULAR("modicum", "modica")
IRREGULAR("modiolus", "modioli")
IRREGULAR("modius", "modii")
IRREGULAR("modulus", "moduli")
IRREGULAR("modus", "modi")
IRREGULAR("mohel", "mohelim")
IRREGULAR("moira", "moirai")
IRREGULAR("mojo", "mojoes")
IRREGULAR("molluscum", "mollusca")
IRREGULAR("molossus", "molossi")
IRREGULAR("moly", "molys")
IRREGULAR("momento", "momentoes")
IRREGULAR("momentum", "momenta")
IRREGULAR("momus", "momi")
IRREGULAR("momzer", "momzerim")
IRREGULAR("monas", "monades")
IRREGULAR("moner", "monera")
IRREGULAR("moneyman", "moneymen")
IRREGULAR("mongo", "mongoes")
IRREGULAR("mongoose", "mongeese")
IRREGULAR("monilia", "moniliae")
IRREGULAR("monopodium", "monopodia")
IRREGULAR("monopteron", "monoptera")
IRREGULAR("monosis", "monoses")
IRREGULAR("monsieur", "messieurs")
IRREGULAR("mooncalf", "mooncalves")
IRREGULAR("moorman", "moormen")
IRREGULAR("moose", "moose")
IRREGULAR("mootman", "mootmen")
IRREGULAR("mora", "morae")
IRREGULAR("moratorium", "moratoria")
IRREGULAR("morceau", "morceaux")
IRREGULAR("morisco", "moriscoes")
IRREGULAR("morphosis", "morphoses")
IRREGULAR("mortarman", "mortarmen")
IRREGULAR("morula", "morulae")
IRREGULAR("mosasaurus", "mosasauri")
IRREGULAR("moshav", "moshavim")
IRREGULAR("mosquito", "mosquitoes")
IRREGULAR("motorman", "motormen")
IRREGULAR("motoscafo", "motoscafi")
IRREGULAR("motto", "mottoes")
IRREGULAR("mouse", "mice")
IRREGULAR("moz", "mozzes")
IRREGULAR("mozetta", "mozette")
IRREGULAR("mozzetta", "mozzette")
IRREGULAR("mucosa", "mucosae")
IRREGULAR("mulatto", "mulattoes")
IRREGULAR("mumak", "mumakil")
IRREGULAR("mungo", "mungoes")
IRREGULAR("murex", "murexes")
IRREGULAR("musca", "muscae")
IRREGULAR("muscleman", "musclemen")
IRREGULAR("muskox", "muskoxen")
IRREGULAR("mutandum", "mutanda")
IRREGULAR("myasis", "myases")
IRREGULAR("mycelium", "mycelia")
IRREGULAR("mycetoma", "mycetomata")
IRREGULAR("mycosis", "mycoses")
IRREGULAR("mydriasis", "mydriases")
IRREGULAR("myelitis", "myelitides")
IRREGULAR("myeloma", "myelomata")
IRREGULAR("myiasis", "myiases")
IRREGULAR("myocardium", "myocardia")
IRREGULAR("myoma", "myomata")
IRREGULAR("myosis", "myoses")
IRREGULAR("myrmidon", "myrmidones")
IRREGULAR("mythos", "mythoi")
IRREGULAR("mythus", "mythi")
IRREGULAR("myxameba", "myxamebae")
IRREGULAR("myxamoeba", "myxamoebae")
IRREGULAR("myxoma", "myxomata")
IRREGULAR("nachas", "nachas")
IRREGULAR("naevus", "naevi")
IRREGULAR("naiad", "naiades")
IRREGULAR("naos", "naoi")
IRREGULAR("narcissus", "narcissi")
IRREGULAR("narcoma", "narcomata")
IRREGULAR("narcosis", "narcoses")
IRREGULAR("naris", "nares")
IRREGULAR("natatorium", "natatoria")
IRREGULAR("natis", "nates")
IRREGULAR("natura", "naturae")
IRREGULAR("nauplius", "nauplii")
IRREGULAR("nautilus", "nautili")
IRREGULAR("nebula", "nebulae")
IRREGULAR("necropolis", "necropoles")
IRREGULAR("necrosis", "necroses")
IRREGULAR("negro", "negroes")
IRREGULAR("nelies", "nelies")
IRREGULAR("nelis", "nelis")
IRREGULAR("nemesis", "nemeses")
IRREGULAR("neocortex", "neocortices")
IRREGULAR("nephridium", "nephridia")
IRREGULAR("nephritis", "nephritides")
IRREGULAR("nephrosis", "nephroses")
IRREGULAR("nereid", "nereides")
IRREGULAR("nereis", "nereides")
IRREGULAR("neuritis", "neuritides")
IRREGULAR("neuroma", "neuromata")
IRREGULAR("neurosis", "neuroses")
IRREGULAR("neurula", "neurulae")
IRREGULAR("nevus", "nevi")
IRREGULAR("newsman", "newsmen")
IRREGULAR("newswoman", "newswomen")
IRREGULAR("ngwee", "ngwee")
IRREGULAR("nidamentum", "nidamenta")
IRREGULAR("nidus", "nidi")
IRREGULAR("niello", "nielli")
IRREGULAR("nightlife", "nightlives")
IRREGULAR("nimbus", "nimbi")
IRREGULAR("nineholes", "nineholes")
IRREGULAR("nisus", "nisus")
IRREGULAR("nix", "nixe")
IRREGULAR("no", "noes")
IRREGULAR("nobleman", "noblemen")
IRREGULAR("nodus", "nodi")
IRREGULAR("noesis", "noeses")
IRREGULAR("nogaku", "nogaku")
IRREGULAR("noh", "noh")
IRREGULAR("nomen", "nomina")
IRREGULAR("nomos", "nomoi")
IRREGULAR("noncrisis", "noncrises")
IRREGULAR("nones", "nones")
IRREGULAR("nonetto", "nonetti")
IRREGULAR("nonhero", "nonheroes")
IRREGULAR("nonlife", "nonlives")
IRREGULAR("nonman", "nonmen")
IRREGULAR("nonself", "nonselves")
IRREGULAR("nostos", "nostoi")
IRREGULAR("notandum", "notanda")
IRREGULAR("notitia", "notitiae")
IRREGULAR("notturno", "notturni")
IRREGULAR("notum", "nota")
IRREGULAR("noumenon", "noumena")
IRREGULAR("nouveau", "nouveaux")
IRREGULAR("nova", "novae")
IRREGULAR("novella", "novelle")
IRREGULAR("novena", "novenae")
IRREGULAR("noyau", "noyaux")
IRREGULAR("nubecula", "nubeculae")
IRREGULAR("nucellus", "nucelli")
IRREGULAR("nucha", "nuchae")
IRREGULAR("nucleolus", "nucleoli")
IRREGULAR("nucleus", "nuclei")
IRREGULAR("numen", "numina")
IRREGULAR("nunatak", "nunataker")
IRREGULAR("nuraghe", "nuraghi")
IRREGULAR("nympha", "nymphae")
IRREGULAR("nymphaeum", "nymphaea")
IRREGULAR("oaf", "oaves")
IRREGULAR("oarsman", "oarsmen")
IRREGULAR("oarswoman", "oarswomen")
IRREGULAR("oasis", "oases")
IRREGULAR("obbligato", "obbligati")
IRREGULAR("obelus", "obeli")
IRREGULAR("oblast", "oblasti")
IRREGULAR("obligato", "obligati")
IRREGULAR("obolus", "oboli")
IRREGULAR("occiput", "occipita")
IRREGULAR("oceanarium", "oceanaria")
IRREGULAR("oceanid", "oceanides")
IRREGULAR("ocellus", "ocelli")
IRREGULAR("ochrea", "ochreae")
IRREGULAR("ocrea", "ocreae")
IRREGULAR("octahedron", "octahedra")
IRREGULAR("octohedron", "octohedra")
IRREGULAR("octonarius", "octonarii")
IRREGULAR("octopod", "octopodes")
IRREGULAR("octopus", "octopodes")
IRREGULAR("oculus", "oculi")
IRREGULAR("oddsman", "oddsmen")
IRREGULAR("odeum", "odea")
IRREGULAR("odontoma", "odontomata")
IRREGULAR("oedema", "oedemata")
IRREGULAR("oesophagus", "oesophagi")
IRREGULAR("offspring", "offspring")
IRREGULAR("oidium", "oidia")
IRREGULAR("oilman", "oilmen")
IRREGULAR("oldwife", "oldwives")
IRREGULAR("oleum", "olea")
IRREGULAR("olpe", "olpae")
IRREGULAR("omasum", "omasa")
IRREGULAR("ombudsman", "ombudsmen")
IRREGULAR("omentum", "omenta")
IRREGULAR("ommateum", "ommatea")
IRREGULAR("ommatidium", "ommatidia")
IRREGULAR("omnibus", "omnibusses")
IRREGULAR("omophorion", "omophoria")
IRREGULAR("omphalos", "omphaloi")
IRREGULAR("onager", "onagri")
IRREGULAR("oncolysis", "oncolyses")
IRREGULAR("oncomouse", "oncomice")
IRREGULAR("oncostman", "oncostmen")
IRREGULAR("oogenesis", "oogeneses")
IRREGULAR("oogonium", "oogonia")
IRREGULAR("ootheca", "oothecae")
IRREGULAR("operculum", "opercula")
IRREGULAR("opponens", "opponens")
IRREGULAR("optimum", "optima")
IRREGULAR("opus", "opera")
IRREGULAR("opusculum", "opuscula")
IRREGULAR("orarium", "oraria")
IRREGULAR("oratrix", "oratrices")
IRREGULAR("orchesis", "orcheses")
IRREGULAR("ordo", "ordines")
IRREGULAR("organum", "organa")
IRREGULAR("origami", "origami")
IRREGULAR("orleans", "orleans")
IRREGULAR("ornis", "ornithes")
IRREGULAR("orraman", "orramen")
IRREGULAR("orthoaxis", "orthoaxes")
IRREGULAR("orthosis", "orthoses")
IRREGULAR("os", "ora")
IRREGULAR("osculum", "oscula")
IRREGULAR("osmeterium", "osmeteria")
IRREGULAR("osmosis", "osmoses")
IRREGULAR("osteitis", "osteitides")
IRREGULAR("osteoma", "osteomata")
IRREGULAR("osteosis", "osteoses")
IRREGULAR("ostinato", "ostinati")
IRREGULAR("ostium", "ostia")
IRREGULAR("ostosis", "ostoses")
IRREGULAR("ostracon", "ostraca")
IRREGULAR("ostrakon", "ostraka")
IRREGULAR("otitis", "otitides")
IRREGULAR("ou", "ouens")
IRREGULAR("ourself", "ourselves")
IRREGULAR("ovaritis", "ovaritides")
IRREGULAR("overman", "overmen")
IRREGULAR("oversman", "oversmen")
IRREGULAR("ovolo", "ovoli")
IRREGULAR("ovotestis", "ovotestes")
IRREGULAR("ovum", "ova")
IRREGULAR("ox", "oxen")
IRREGULAR("oxymoron", "oxymora")
IRREGULAR("oysterman", "oystermen")
IRREGULAR("paceman", "pacemen")
IRREGULAR("packman", "packmen")
IRREGULAR("pactum", "pacta")
IRREGULAR("paderero", "padereroes")
IRREGULAR("padre", "padri")
IRREGULAR("padrone", "padroni")
IRREGULAR("paenula", "paenulae")
IRREGULAR("paesano", "paesani")
IRREGULAR("pailful", "pailsful")
IRREGULAR("pais", "pais")
IRREGULAR("paisa", "paise")
IRREGULAR("palais", "palais")
IRREGULAR("palama", "palamae")
IRREGULAR("palazzo", "palazzi")
IRREGULAR("palea", "paleae")
IRREGULAR("palestra", "palestrae")
IRREGULAR("palla", "pallae")
IRREGULAR("palladium", "palladia")
IRREGULAR("pallium", "pallia")
IRREGULAR("palmetto", "palmettoes")
IRREGULAR("palpebra", "palpebrae")
IRREGULAR("palpus", "palpi")
IRREGULAR("pancratium", "pancratia")
IRREGULAR("pandanus", "pandani")
IRREGULAR("panettone", "panettoni")
IRREGULAR("panino", "panini")
IRREGULAR("panjandrum", "panjandra")
IRREGULAR("panmixis", "panmixes")
IRREGULAR("pantihose", "pantihose")
IRREGULAR("pantryman", "pantrymen")
IRREGULAR("pantyhose", "pantyhose")
IRREGULAR("paolo", "paoli")
IRREGULAR("paparazzo", "paparazzi")
IRREGULAR("papilla", "papillae")
IRREGULAR("papilloma", "papillomata")
IRREGULAR("pappus", "pappi")
IRREGULAR("papula", "papulae")
IRREGULAR("papyrus", "papyri")
IRREGULAR("parabasis", "parabases")
IRREGULAR("parabema", "parabemata")
IRREGULAR("parabola", "parabolae")
IRREGULAR("paracusis", "paracuses")
IRREGULAR("parador", "paradores")
IRREGULAR("paralysis", "paralyses")
IRREGULAR("paramecium", "paramecia")
IRREGULAR("parament", "paramenta")
IRREGULAR("parapodium", "parapodia")
IRREGULAR("parashah", "parashot")
IRREGULAR("parataxis", "parataxes")
IRREGULAR("parazoon", "parazoa")
IRREGULAR("parenesis", "pareneses")
IRREGULAR("parenthesis", "parentheses")
IRREGULAR("parergon", "parerga")
IRREGULAR("paresis", "pareses")
IRREGULAR("pargo", "pargoes")
IRREGULAR("parhelion", "parhelia")
IRREGULAR("parodos", "parodoi")
IRREGULAR("parotis", "parotides")
IRREGULAR("parulis", "parulides")
IRREGULAR("paruresis", "parureses")
IRREGULAR("pas", "pas")
IRREGULAR("passado", "passadoes")
IRREGULAR("passerby", "passersby")
IRREGULAR("passman", "passmen")
IRREGULAR("pasticcio", "pasticci")
IRREGULAR("pastorale", "pastorali")
IRREGULAR("patagium", "patagia")
IRREGULAR("patella", "patellae")
IRREGULAR("patera", "paterae")
IRREGULAR("paterero", "patereroes")
IRREGULAR("patina", "patinae")
IRREGULAR("patois", "patois")
IRREGULAR("patrico", "patricoes")
IRREGULAR("patrolman", "patrolmen")
IRREGULAR("pease", "peasen")
IRREGULAR("peatman", "peatmen")
IRREGULAR("peccadillo", "peccadilloes")
IRREGULAR("pecorino", "pecorini")
IRREGULAR("peculium", "peculia")
IRREGULAR("pedalo", "pedaloes")
IRREGULAR("pederero", "pedereroes")
IRREGULAR("pedesis", "pedeses")
IRREGULAR("pediculus", "pediculi")
IRREGULAR("pedipalpus", "pedipalpi")
IRREGULAR("pedrero", "pedreroes")
IRREGULAR("pelta", "peltae")
IRREGULAR("pelvis", "pelves")
IRREGULAR("pemphigus", "pemphigi")
IRREGULAR("pence", "pence")
IRREGULAR("penicillus", "penicilli")
IRREGULAR("penknife", "penknives")
IRREGULAR("penman", "penmen")
IRREGULAR("penna", "pennae")
IRREGULAR("penni", "pennia")
IRREGULAR("pennill", "penillion")
IRREGULAR("pensione", "pensioni")
IRREGULAR("pentathlum", "pentathla")
IRREGULAR("pentito", "pentiti")
IRREGULAR("penumbra", "penumbrae")
IRREGULAR("penwoman", "penwomen")
IRREGULAR("peon", "peones")
IRREGULAR("peplum", "pepla")
IRREGULAR("peraeon", "peraea")
IRREGULAR("pereion", "pereia")
IRREGULAR("pereon", "perea")
IRREGULAR("periaktos", "periaktoi")
IRREGULAR("peribolos", "periboloi")
IRREGULAR("peribolus", "periboli")
IRREGULAR("pericon", "pericones")
IRREGULAR("pericope", "pericopae")
IRREGULAR("peridinium", "peridinia")
IRREGULAR("peridium", "peridia")
IRREGULAR("perigonium", "perigonia")
IRREGULAR("perihelion", "perihelia")
IRREGULAR("perikaryon", "perikarya")
IRREGULAR("perimysium", "perimysia")
IRREGULAR("perineum", "perinea")
IRREGULAR("periosteum", "periostea")
IRREGULAR("peritoneum", "peritonea")
IRREGULAR("peritus", "periti")
IRREGULAR("pernio", "perniones")
IRREGULAR("perradius", "perradii")
IRREGULAR("persona", "personae")
IRREGULAR("pertussis", "pertusses")
IRREGULAR("pes", "pedes")
IRREGULAR("pessimum", "pessima")
IRREGULAR("petechia", "petechiae")
IRREGULAR("peterman", "petermen")
IRREGULAR("petto", "petti")
IRREGULAR("pfennig", "pfennige")
IRREGULAR("phalanx", "phalanges")
IRREGULAR("phallus", "phalli")
IRREGULAR("phantasma", "phantasmata")
IRREGULAR("pharynx", "pharynges")
IRREGULAR("phasis", "phases")
IRREGULAR("phelonion", "phelonia")
IRREGULAR("phenomenon", "phenomena")
IRREGULAR("pheresis", "phereses")
IRREGULAR("philtrum", "philtra")
IRREGULAR("phimosis", "phimoses")
IRREGULAR("phiz", "phizzes")
IRREGULAR("phlebitis", "phlebitides")
IRREGULAR("phoca", "phocae")
IRREGULAR("pholas", "pholas")
IRREGULAR("phorminx", "phorminges")
IRREGULAR("phosphorus", "phosphori")
IRREGULAR("phraseman", "phrasemen")
IRREGULAR("phrenesis", "phreneses")
IRREGULAR("phrenitis", "phrenitides")
IRREGULAR("phthisis", "phthises")
IRREGULAR("phylaxis", "phylaxises")
IRREGULAR("phyle", "phylae")
IRREGULAR("phylesis", "phyleses")
IRREGULAR("phyllodium", "phyllodia")
IRREGULAR("phylum", "phyla")
IRREGULAR("physis", "physes")
IRREGULAR("phytosis", "phytoses")
IRREGULAR("piano", "piani")
IRREGULAR("piazza", "piazze")
IRREGULAR("picador", "picadores")
IRREGULAR("piccadillo", "piccadilloes")
IRREGULAR("pice", "pice")
IRREGULAR("pickadillo", "pickadilloes")
IRREGULAR("pieman", "piemen")
IRREGULAR("pierogi", "pierogi")
IRREGULAR("pifferaro", "pifferari")
IRREGULAR("pignus", "pignora")
IRREGULAR("pikeman", "pikemen")
IRREGULAR("pikestaff", "pikestaves")
IRREGULAR("pila", "pilae")
IRREGULAR("pileus", "pilei")
IRREGULAR("pilotman", "pilotmen")
IRREGULAR("pilula", "pilulae")
IRREGULAR("pilum", "pila")
IRREGULAR("pinetum", "pineta")
IRREGULAR("pingo", "pingoes")
IRREGULAR("pinko", "pinkoes")
IRREGULAR("pinna", "pinnae")
IRREGULAR("pinnula", "pinnulae")
IRREGULAR("pinon", "pinones")
IRREGULAR("pintado", "pintadoes")
IRREGULAR("pinto", "pintoes")
IRREGULAR("pirog", "pirogen")
IRREGULAR("piroghi", "pirogi")
IRREGULAR("pirogi", "pirogies")
IRREGULAR("pirozhok", "pirozhki")
IRREGULAR("piscina", "piscinae")
IRREGULAR("pitchman", "pitchmen")
IRREGULAR("pithos", "pithoi")
IRREGULAR("pitman", "pitmen")
IRREGULAR("pivotman", "pivotmen")
IRREGULAR("pizzicato", "pizzicati")
IRREGULAR("placebo", "placeboes")
IRREGULAR("placeman", "placemen")
IRREGULAR("placenta", "placentae")
IRREGULAR("placitum", "placita")
IRREGULAR("plaidman", "plaidmen")
IRREGULAR("plainsman", "plainsmen")
IRREGULAR("plankton", "plankton")
IRREGULAR("planta", "plantae")
IRREGULAR("plantsman", "plantsmen")
IRREGULAR("planula", "planulae")
IRREGULAR("plasmodium", "plasmodia")
IRREGULAR("plateau", "plateaux")
IRREGULAR("plateful", "platesful")
IRREGULAR("plateman", "platemen")
IRREGULAR("platy", "platys")
IRREGULAR("platypus", "platypi")
IRREGULAR("pleaseman", "pleasemen")
IRREGULAR("plectrum", "plectra")
IRREGULAR("pleiad", "pleiades")
IRREGULAR("plenipo", "plenipoes")
IRREGULAR("plenum", "plena")
IRREGULAR("pleura", "pleurae")
IRREGULAR("plica", "plicae")
IRREGULAR("ploughman", "ploughmen")
IRREGULAR("plowman", "plowmen")
IRREGULAR("plumula", "plumulae")
IRREGULAR("pluteus", "plutei")
IRREGULAR("podium", "podia")
IRREGULAR("poignado", "poignadoes")
IRREGULAR("poinado", "poinadoes")
IRREGULAR("pointman", "pointmen")
IRREGULAR("pointsman", "pointsmen")
IRREGULAR("poisha", "poisha")
IRREGULAR("policeman", "policemen")
IRREGULAR("politico", "politicoes")
IRREGULAR("pollex", "pollices")
IRREGULAR("pollinium", "pollinia")
IRREGULAR("pollman", "pollmen")
IRREGULAR("poltfoot", "poltfeet")
IRREGULAR("poly", "polys")
IRREGULAR("polyanthus", "polyanthi")
IRREGULAR("polyhedron", "polyhedra")
IRREGULAR("polynya", "polynyi")
IRREGULAR("polyparium", "polyparia")
IRREGULAR("polyposis", "polyposes")
IRREGULAR("polypus", "polypi")
IRREGULAR("polyzoon", "polyzoa")
IRREGULAR("pomato", "pomatoes")
IRREGULAR("ponceau", "ponceaux")
IRREGULAR("pongo", "pongoes")
IRREGULAR("pontifex", "pontifices")
IRREGULAR("popliteus", "poplitei")
IRREGULAR("porosis", "poroses")
IRREGULAR("portico", "porticoes")
IRREGULAR("portman", "portmen")
IRREGULAR("portolano", "portolani")
IRREGULAR("postcava", "postcavae")
IRREGULAR("postman", "postmen")
IRREGULAR("postulatum", "postulata")
IRREGULAR("postwoman", "postwomen")
IRREGULAR("potato", "potatoes")
IRREGULAR("potman", "potmen")
IRREGULAR("praeludium", "praeludia")
IRREGULAR("praenomen", "praenomina")
IRREGULAR("praeses", "praeses")
IRREGULAR("praesidium", "praesidia")
IRREGULAR("praxis", "praxes")
IRREGULAR("precava", "precavae")
IRREGULAR("precieux", "precieux")
IRREGULAR("precis", "precis")
IRREGULAR("predella", "predelle")
IRREGULAR("prehallux", "prehalluces")
IRREGULAR("prelife", "prelives")
IRREGULAR("preludio", "preludi")
IRREGULAR("preman", "premen")
IRREGULAR("premium", "premia")
IRREGULAR("prenomen", "prenomina")
IRREGULAR("prepollex", "prepollices")
IRREGULAR("prepubis", "prepubes")
IRREGULAR("prepupa", "prepupae")
IRREGULAR("presa", "prese")
IRREGULAR("prescutum", "prescuta")
IRREGULAR("preses", "preses")
IRREGULAR("presidium", "presidia")
IRREGULAR("pressman", "pressmen")
IRREGULAR("presternum", "presterna")
IRREGULAR("priapus", "priapi")
IRREGULAR("priedieu", "priedieux")
IRREGULAR("primo", "primi")
IRREGULAR("primordium", "primordia")
IRREGULAR("principe", "principi")
IRREGULAR("principium", "principia")
IRREGULAR("privado", "privadoes")
IRREGULAR("prizeman", "prizemen")
IRREGULAR("proboscis", "proboscides")
IRREGULAR("procambium", "procambia")
IRREGULAR("proclisis", "proclises")
IRREGULAR("proctitis", "proctitides")
IRREGULAR("proctodeum", "proctodea")
IRREGULAR("prodrome", "prodromata")
IRREGULAR("prodromus", "prodromi")
IRREGULAR("prognosis", "prognoses")
IRREGULAR("prolepsis", "prolepses")
IRREGULAR("promuscis", "promusces")
IRREGULAR("pronaos", "pronaoi")
IRREGULAR("pronator", "pronatores")
IRREGULAR("pronephros", "pronephra")
IRREGULAR("pronotum", "pronota")
IRREGULAR("pronucleus", "pronuclei")
IRREGULAR("propagulum", "propagula")
IRREGULAR("propman", "propmen")
IRREGULAR("propositus", "propositi")
IRREGULAR("proprium", "propria")
IRREGULAR("proptosis", "proptoses")
IRREGULAR("propylaeum", "propylaea")
IRREGULAR("propylon", "propyla")
IRREGULAR("proscenium", "proscenia")
IRREGULAR("proseman", "prosemen")
IRREGULAR("prosoma", "prosomata")
IRREGULAR("prosternum", "prosterna")
IRREGULAR("prostomium", "prostomia")
IRREGULAR("protasis", "protases")
IRREGULAR("proteus", "protei")
IRREGULAR("prothallus", "prothalli")
IRREGULAR("prothesis", "protheses")
IRREGULAR("prothorax", "prothoraces")
IRREGULAR("protonema", "protonemata")
IRREGULAR("protozoon", "protozoa")
IRREGULAR("proviso", "provisoes")
IRREGULAR("pruta", "prutot")
IRREGULAR("prutah", "prutoth")
IRREGULAR("prytaneum", "prytanea")
IRREGULAR("psalterium", "psalteria")
IRREGULAR("pseudaxis", "pseudaxes")
IRREGULAR("psilosis", "psiloses")
IRREGULAR("psoas", "psoae")
IRREGULAR("psoriasis", "psoriases")
IRREGULAR("psychosis", "psychoses")
IRREGULAR("pterion", "pteria")
IRREGULAR("pterygium", "pterygia")
IRREGULAR("pteryla", "pterylae")
IRREGULAR("ptilosis", "ptiloses")
IRREGULAR("ptosis", "ptoses")
IRREGULAR("ptyxis", "ptyxes")
IRREGULAR("pudendum", "pudenda")
IRREGULAR("puerpera", "puerperae")
IRREGULAR("puerperium", "puerperia")
IRREGULAR("pul", "puli")
IRREGULAR("puli", "pulik")
IRREGULAR("pullus", "pulli")
IRREGULAR("pulmo", "pulmones")
IRREGULAR("pulvinus", "pulvini")
IRREGULAR("punctum", "puncta")
IRREGULAR("pundonor", "pundonores")
IRREGULAR("puntsman", "puntsmen")
IRREGULAR("pupa", "pupae")
IRREGULAR("puparium", "puparia")
IRREGULAR("purlieu", "purlieux")
IRREGULAR("putamen", "putamina")
IRREGULAR("putois", "putois")
IRREGULAR("putto", "putti")
IRREGULAR("pycnidium", "pycnidia")
IRREGULAR("pycnosis", "pycnoses")
IRREGULAR("pygidium", "pygidia")
IRREGULAR("pyknosis", "pyknoses")
IRREGULAR("pylorus", "pylori")
IRREGULAR("pyosis", "pyoses")
IRREGULAR("pyramidion", "pyramidia")
IRREGULAR("pyramis", "pyramides")
IRREGULAR("pyrolysis", "pyrolyses")
IRREGULAR("pyrosis", "pyroses")
IRREGULAR("pysanka", "pysanky")
IRREGULAR("pyxidium", "pyxidia")
IRREGULAR("pyxis", "pyxides")
IRREGULAR("qindar", "qindarka")
IRREGULAR("qintar", "qintarka")
IRREGULAR("quadratus", "quadrati")
IRREGULAR("quadriga", "quadrigae")
IRREGULAR("quadrivium", "quadrivia")
IRREGULAR("quaich", "quaichs")
IRREGULAR("quale", "qualia")
IRREGULAR("quantum", "quanta")
IRREGULAR("quarryman", "quarrymen")
IRREGULAR("quartetto", "quartetti")
IRREGULAR("quillman", "quillmen")
IRREGULAR("quintetto", "quintetti")
IRREGULAR("quiz", "quizzes")
IRREGULAR("qwerty", "qwertys")
IRREGULAR("rabato", "rabatoes")
IRREGULAR("rachilla", "rachillae")
IRREGULAR("rachis", "rachides")
IRREGULAR("rachitis", "rachitises")
IRREGULAR("raddleman", "raddlemen")
IRREGULAR("radiale", "radialia")
IRREGULAR("radioman", "radiomen")
IRREGULAR("radius", "radii")
IRREGULAR("radix", "radices")
IRREGULAR("radula", "radulae")
IRREGULAR("raftman", "raftmen")
IRREGULAR("raftsman", "raftsmen")
IRREGULAR("ragman", "ragmen")
IRREGULAR("railbus", "railbusses")
IRREGULAR("railman", "railmen")
IRREGULAR("railwoman", "railwomen")
IRREGULAR("ramentum", "ramenta")
IRREGULAR("rampsman", "rampsmen")
IRREGULAR("ramulus", "ramuli")
IRREGULAR("ranchman", "ranchmen")
IRREGULAR("ranunculus", "ranunculi")
IRREGULAR("ranzelman", "ranzelmen")
IRREGULAR("raphe", "raphae")
IRREGULAR("raphis", "raphides")
IRREGULAR("rappen", "rappen")
IRREGULAR("rearmouse", "rearmice")
IRREGULAR("rebato", "rebatoes")
IRREGULAR("rectrix", "rectrices")
IRREGULAR("rectum", "recta")
IRREGULAR("rectus", "recti")
IRREGULAR("reddendum", "reddenda")
IRREGULAR("reddleman", "reddlemen")
IRREGULAR("redia", "rediae")
IRREGULAR("reedman", "reedmen")
IRREGULAR("reelman", "reelmen")
IRREGULAR("referendum", "referenda")
IRREGULAR("reformado", "reformadoes")
IRREGULAR("refugium", "refugia")
IRREGULAR("regina", "reginae")
IRREGULAR("regma", "regmata")
IRREGULAR("regnum", "regna")
IRREGULAR("regula", "regulae")
IRREGULAR("regulus", "reguli")
IRREGULAR("reinsman", "reinsmen")
IRREGULAR("rejon", "rejones")
IRREGULAR("relatum", "relata")
IRREGULAR("religieux", "religieux")
IRREGULAR("remex", "remiges")
IRREGULAR("renegado", "renegadoes")
IRREGULAR("repairman", "repairmen")
IRREGULAR("replum", "repla")
IRREGULAR("repoman", "repomen")
IRREGULAR("reptilium", "reptilia")
IRREGULAR("reremouse", "reremice")
IRREGULAR("reseau", "reseaux")
IRREGULAR("residuum", "residua")
IRREGULAR("resinosis", "resinoses")
IRREGULAR("responsum", "responsa")
IRREGULAR("rete", "retia")
IRREGULAR("retiarius", "retiarii")
IRREGULAR("reticulum", "reticula")
IRREGULAR("retina", "retinae")
IRREGULAR("retinitis", "retinitides")
IRREGULAR("retinula", "retinulae")
IRREGULAR("reverso", "reversi")
IRREGULAR("rex", "reges")
IRREGULAR("rez", "rezzes")
IRREGULAR("rhachis", "rhachides")
IRREGULAR("rhaphe", "rhaphae")
IRREGULAR("rhaphis", "rhaphides")
IRREGULAR("rheotaxis", "rheotaxes")
IRREGULAR("rhexis", "rhexes")
IRREGULAR("rhinitis", "rhinitides")
IRREGULAR("rhinoceros", "rhinoceri")
IRREGULAR("rhizobium", "rhizobia")
IRREGULAR("rhizoma", "rhizomata")
IRREGULAR("rhizopus", "rhizopi")
IRREGULAR("rhombos", "rhomboi")
IRREGULAR("rhombus", "rhombi")
IRREGULAR("rhonchus", "rhonchi")
IRREGULAR("rhythmus", "rhythmi")
IRREGULAR("rhyton", "rhyta")
IRREGULAR("ribes", "ribes")
IRREGULAR("ricercare", "ricercari")
IRREGULAR("rifleman", "riflemen")
IRREGULAR("rikishi", "rikishi")
IRREGULAR("rilievo", "rilievi")
IRREGULAR("rima", "rimae")
IRREGULAR("ringman", "ringmen")
IRREGULAR("ripieno", "ripieni")
IRREGULAR("risorius", "risorii")
IRREGULAR("rispetto", "rispetti")
IRREGULAR("riverman", "rivermen")
IRREGULAR("roadman", "roadmen")
IRREGULAR("roadsman", "roadsmen")
IRREGULAR("rodman", "rodmen")
IRREGULAR("rodsman", "rodsmen")
IRREGULAR("rokkaku", "rokkaku")
IRREGULAR("rom", "roma")
IRREGULAR("rondeau", "rondeaux")
IRREGULAR("rooibos", "rooibos")
IRREGULAR("rosarium", "rosaria")
IRREGULAR("rostellum", "rostella")
IRREGULAR("rostrum", "rostra")
IRREGULAR("rotator", "rotatores")
IRREGULAR("rotl", "artal")
IRREGULAR("rotula", "rotulae")
IRREGULAR("rouleau", "rouleaux")
IRREGULAR("roundsman", "roundsmen")
IRREGULAR("routeman", "routemen")
IRREGULAR("roux", "roux")
IRREGULAR("rubai", "rubaiyat")
IRREGULAR("rubato", "rubati")
IRREGULAR("rubel", "rubli")
IRREGULAR("ruckman", "ruckmen")
IRREGULAR("ruddleman", "ruddlemen")
IRREGULAR("ruga", "rugae")
IRREGULAR("rumen", "rumina")
IRREGULAR("russula", "russulae")
IRREGULAR("rype", "ryper")
IRREGULAR("saccos", "saccoi")
IRREGULAR("sacculus", "sacculi")
IRREGULAR("sacellum", "sacella")
IRREGULAR("sackful", "sacksful")
IRREGULAR("sacrarium", "sacraria")
IRREGULAR("sacrum", "sacra")
IRREGULAR("saddo", "saddoes")
IRREGULAR("saeculum", "saecula")
IRREGULAR("safetyman", "safetymen")
IRREGULAR("sagaman", "sagamen")
IRREGULAR("sakkos", "sakkoi")
IRREGULAR("salaryman", "salarymen")
IRREGULAR("salesman", "salesmen")
IRREGULAR("salicetum", "saliceta")
IRREGULAR("salix", "salices")
IRREGULAR("salmis", "salmis")
IRREGULAR("salmon", "salmon")
IRREGULAR("salpa", "salpae")
IRREGULAR("salpinx", "salpinges")
IRREGULAR("sambo", "samboes")
IRREGULAR("samurai", "samurai")
IRREGULAR("sanatorium", "sanatoria")
IRREGULAR("sanctum", "sancta")
IRREGULAR("sandman", "sandmen")
IRREGULAR("sanitarium", "sanitaria")
IRREGULAR("sanitorium", "sanitoria")
IRREGULAR("santims", "santimi")
IRREGULAR("santimu", "santimu")
IRREGULAR("sapego", "sapegoes")
IRREGULAR("saphena", "saphenae")
IRREGULAR("sarcina", "sarcinae")
IRREGULAR("sarcoma", "sarcomata")
IRREGULAR("sargasso", "sargassa")
IRREGULAR("sarmentum", "sarmenta")
IRREGULAR("sartorius", "sartorii")
IRREGULAR("sashimi", "sashimi")
IRREGULAR("sastruga", "sastrugi")
IRREGULAR("sau", "sau")
IRREGULAR("sawtooth", "sawteeth")
IRREGULAR("saxman", "saxmen")
IRREGULAR("saz", "sazzes")
IRREGULAR("sbirro", "sbirri")
IRREGULAR("scala", "scalae")
IRREGULAR("scaldino", "scaldini")
IRREGULAR("scalenus", "scaleni")
IRREGULAR("scampi", "scampies")
IRREGULAR("scapula", "scapulae")
IRREGULAR("scapus", "scapi")
IRREGULAR("scarabaeus", "scarabaei")
IRREGULAR("scarf", "scarves")
IRREGULAR("scarpetto", "scarpetti")
IRREGULAR("sceat", "sceattas")
IRREGULAR("sceatt", "sceattas")
IRREGULAR("schema", "schemata")
IRREGULAR("scherzo", "scherzi")
IRREGULAR("schliere", "schlieren")
IRREGULAR("schnecke", "schnecken")
IRREGULAR("schnoz", "schnozzes")
IRREGULAR("scholium", "scholia")
IRREGULAR("schoolman", "schoolmen")
IRREGULAR("schul", "schuln")
IRREGULAR("scirrhus", "scirrhi")
IRREGULAR("sclera", "sclerae")
IRREGULAR("scleroma", "scleromata")
IRREGULAR("sclerosis", "scleroses")
IRREGULAR("sclerotium", "sclerotia")
IRREGULAR("scolex", "scoleces")
IRREGULAR("scolion", "scolia")
IRREGULAR("scoliosis", "scolioses")
IRREGULAR("scoopful", "scoopsful")
IRREGULAR("scop", "scopas")
IRREGULAR("scopa", "scopae")
IRREGULAR("scopula", "scopulae")
IRREGULAR("scoria", "scoriae")
IRREGULAR("scotoma", "scotomata")
IRREGULAR("scrotum", "scrota")
IRREGULAR("scudo", "scudi")
IRREGULAR("scungile", "scungili")
IRREGULAR("scungille", "scungilli")
IRREGULAR("scutellum", "scutella")
IRREGULAR("scutum", "scuta")
IRREGULAR("scybalum", "scybala")
IRREGULAR("scyphus", "scyphi")
IRREGULAR("scytheman", "scythemen")
IRREGULAR("seaman", "seamen")
IRREGULAR("seaquarium", "seaquaria")
IRREGULAR("seawife", "seawives")
IRREGULAR("seawoman", "seawomen")
IRREGULAR("secondo", "secondi")
IRREGULAR("seculum", "secula")
IRREGULAR("seder", "sedarim")
IRREGULAR("sedes", "sedes")
IRREGULAR("sedile", "sedilia")
IRREGULAR("seedman", "seedmen")
IRREGULAR("seedsman", "seedsmen")
IRREGULAR("sefer", "sifrei")
IRREGULAR("segno", "segni")
IRREGULAR("selectman", "selectmen")
IRREGULAR("selenosis", "selenoses")
IRREGULAR("self", "selves")
IRREGULAR("sella", "sellae")
IRREGULAR("semantron", "semantra")
IRREGULAR("semeion", "semeia")
IRREGULAR("semen", "semina")
IRREGULAR("semidwarf", "semidwarves")
IRREGULAR("semihobo", "semihoboes")
IRREGULAR("seminoma", "seminomata")
IRREGULAR("semiosis", "semioses")
IRREGULAR("semuncia", "semunciae")
IRREGULAR("sen", "sen")
IRREGULAR("senarius", "senarii")
IRREGULAR("senhor", "senhores")
IRREGULAR("senor", "senores")
IRREGULAR("senryu", "senryu")
IRREGULAR("sensilla", "sensillae")
IRREGULAR("sensorium", "sensoria")
IRREGULAR("sensum", "sensa")
IRREGULAR("senti", "senti")
IRREGULAR("separatum", "separata")
IRREGULAR("sepsis", "sepses")
IRREGULAR("septarium", "septaria")
IRREGULAR("septennium", "septennia")
IRREGULAR("septum", "septa")
IRREGULAR("sequela", "sequelae")
IRREGULAR("sequestrum", "sequestra")
IRREGULAR("seraph", "seraphin")
IRREGULAR("series", "series")
IRREGULAR("serosa", "serosae")
IRREGULAR("serpigo", "serpigoes")
IRREGULAR("serpula", "serpulae")
IRREGULAR("serra", "serrae")
IRREGULAR("serratus", "serrati")
IRREGULAR("serum", "sera")
IRREGULAR("sestertium", "sestertia")
IRREGULAR("sestertius", "sestertii")
IRREGULAR("seta", "setae")
IRREGULAR("sextarius", "sextarii")
IRREGULAR("sforzando", "sforzandi")
IRREGULAR("sforzato", "sforzati")
IRREGULAR("sgraffito", "sgraffiti")
IRREGULAR("shacko", "shackoes")
IRREGULAR("shako", "shakoes")
IRREGULAR("shammas", "shammasim")
IRREGULAR("shammash", "shammashim")
IRREGULAR("shammes", "shammosim")
IRREGULAR("shammos", "shammosim")
IRREGULAR("shamois", "shamois")
IRREGULAR("shamos", "shamosim")
IRREGULAR("shantyman", "shantymen")
IRREGULAR("shareman", "sharemen")
IRREGULAR("sharesman", "sharesmen")
IRREGULAR("sharif", "ashraf")
IRREGULAR("shearman", "shearmen")
IRREGULAR("sheep", "sheep")
IRREGULAR("sheepman", "sheepmen")
IRREGULAR("shegetz", "shkotzim")
IRREGULAR("shekel", "shekalim")
IRREGULAR("sheqel", "sheqalim")
IRREGULAR("shero", "sheroes")
IRREGULAR("shigella", "shigellae")
IRREGULAR("shilingi", "shilingi")
IRREGULAR("shindy", "shindys")
IRREGULAR("shinleaf", "shinleaves")
IRREGULAR("shipman", "shipmen")
IRREGULAR("shireman", "shiremen")
IRREGULAR("shiur", "shiurim")
IRREGULAR("shmo", "shmoes")
IRREGULAR("shochet", "shochetim")
IRREGULAR("shoe", "shoon")
IRREGULAR("shofar", "shofroth")
IRREGULAR("shojo", "shojo")
IRREGULAR("shophar", "shophroth")
IRREGULAR("shopman", "shopmen")
IRREGULAR("shoreman", "shoremen")
IRREGULAR("shoresman", "shoresmen")
IRREGULAR("showman", "showmen")
IRREGULAR("shrewmouse", "shrewmice")
IRREGULAR("shrimp", "shrimp")
IRREGULAR("shtetl", "shtetlach")
IRREGULAR("shul", "shuln")
IRREGULAR("siciliana", "siciliane")
IRREGULAR("sickleman", "sicklemen")
IRREGULAR("siddur", "siddurim")
IRREGULAR("sideman", "sidemen")
IRREGULAR("siderosis", "sideroses")
IRREGULAR("sidesman", "sidesmen")
IRREGULAR("sightsman", "sightsmen")
IRREGULAR("sigisbeo", "sigisbei")
IRREGULAR("siglos", "sigloi")
IRREGULAR("signalman", "signalmen")
IRREGULAR("signior", "signiori")
IRREGULAR("signore", "signori")
IRREGULAR("signorina", "signorine")
IRREGULAR("signorino", "signorini")
IRREGULAR("silenus", "sileni")
IRREGULAR("silicosis", "silicoses")
IRREGULAR("silicula", "siliculae")
IRREGULAR("siliqua", "siliquae")
IRREGULAR("silphium", "silphia")
IRREGULAR("silva", "silvae")
IRREGULAR("simplex", "simplices")
IRREGULAR("simulacrum", "simulacra")
IRREGULAR("sinciput", "sincipita")
IRREGULAR("sinfonia", "sinfonie")
IRREGULAR("sinopia", "sinopie")
IRREGULAR("siriasis", "siriases")
IRREGULAR("sistrum", "sistra")
IRREGULAR("situla", "situlae")
IRREGULAR("skeo", "skeoes")
IRREGULAR("skio", "skioes")
IRREGULAR("skiwear", "skiwear")
IRREGULAR("skolion", "skolia")
IRREGULAR("skyman", "skymen")
IRREGULAR("skyphos", "skyphoi")
IRREGULAR("smalto", "smalti")
IRREGULAR("snowman", "snowmen")
IRREGULAR("sockman", "sockmen")
IRREGULAR("socman", "socmen")
IRREGULAR("sokaiya", "sokaiya")
IRREGULAR("sokeman", "sokemen")
IRREGULAR("solarium", "solaria")
IRREGULAR("solatium", "solatia")
IRREGULAR("soldado", "soldadoes")
IRREGULAR("soldo", "soldi")
IRREGULAR("soleus", "solei")
IRREGULAR("solfeggio", "solfeggi")
IRREGULAR("solidus", "solidi")
IRREGULAR("solo", "soli")
IRREGULAR("som", "somy")
IRREGULAR("soma", "somata")
IRREGULAR("sonarman", "sonarmen")
IRREGULAR("sonatina", "sonatine")
IRREGULAR("songman", "songmen")
IRREGULAR("sopranino", "sopranini")
IRREGULAR("soprano", "soprani")
IRREGULAR("sordino", "sordini")
IRREGULAR("soredium", "soredia")
IRREGULAR("sorites", "sorites")
IRREGULAR("sorosis", "soroses")
IRREGULAR("sortes", "sortes")
IRREGULAR("sorus", "sori")
IRREGULAR("sostenuto", "sostenuti")
IRREGULAR("soundman", "soundmen")
IRREGULAR("sovkhoz", "sovkhozy")
IRREGULAR("spacecraft", "spacecraft")
IRREGULAR("spaceman", "spacemen")
IRREGULAR("spademan", "spademen")
IRREGULAR("spadesman", "spadesmen")
IRREGULAR("spadix", "spadices")
IRREGULAR("spado", "spadoes")
IRREGULAR("spaeman", "spaemen")
IRREGULAR("spaewife", "spaewives")
IRREGULAR("spatlese", "spatlesen")
IRREGULAR("spaz", "spazzes")
IRREGULAR("spearman", "spearmen")
IRREGULAR("species", "species")
IRREGULAR("spectrum", "spectra")
IRREGULAR("speculum", "specula")
IRREGULAR("spermarium", "spermaria")
IRREGULAR("spermatium", "spermatia")
IRREGULAR("sphinx", "sphinges")
IRREGULAR("spica", "spicae")
IRREGULAR("spicula", "spiculae")
IRREGULAR("spiderman", "spidermen")
IRREGULAR("spina", "spinae")
IRREGULAR("spinone", "spinoni")
IRREGULAR("spinula", "spinulae")
IRREGULAR("spiraculum", "spiracula")
IRREGULAR("spirillum", "spirilla")
IRREGULAR("spirula", "spirulae")
IRREGULAR("spirulina", "spirulinae")
IRREGULAR("splayfoot", "splayfeet")
IRREGULAR("splenium", "splenia")
IRREGULAR("splenius", "splenii")
IRREGULAR("spoilsman", "spoilsmen")
IRREGULAR("spokesman", "spokesmen")
IRREGULAR("spondulix", "spondulix")
IRREGULAR("spoonful", "spoonsful")
IRREGULAR("sporangium", "sporangia")
IRREGULAR("sporidium", "sporidia")
IRREGULAR("sporozoon", "sporozoa")
IRREGULAR("sportsman", "sportsmen")
IRREGULAR("sputum", "sputa")
IRREGULAR("squama", "squamae")
IRREGULAR("squawman", "squawmen")
IRREGULAR("squid", "squid")
IRREGULAR("squilla", "squillae")
IRREGULAR("stableman", "stablemen")
IRREGULAR("staccato", "staccati")
IRREGULAR("staff", "staves")
IRREGULAR("staffman", "staffmen")
IRREGULAR("stalko", "stalkoes")
IRREGULAR("stallman", "stallmen")
IRREGULAR("stamnos", "stamnoi")
IRREGULAR("stanzo", "stanzoes")
IRREGULAR("stapedius", "stapedii")
IRREGULAR("stapes", "stapedes")
IRREGULAR("starets", "startsy")
IRREGULAR("stasimon", "stasima")
IRREGULAR("stasis", "stases")
IRREGULAR("statesman", "statesmen")
IRREGULAR("stearsman", "stearsmen")
IRREGULAR("steatosis", "steatoses")
IRREGULAR("steelman", "steelmen")
IRREGULAR("steersman", "steersmen")
IRREGULAR("stegnosis", "stegnoses")
IRREGULAR("stela", "stelae")
IRREGULAR("stemma", "stemmata")
IRREGULAR("stenosis", "stenoses")
IRREGULAR("sterigma", "sterigmata")
IRREGULAR("sternum", "sterna")
IRREGULAR("sticcado", "sticcadoes")
IRREGULAR("sticcato", "sticcatoes")
IRREGULAR("sticharion", "sticharia")
IRREGULAR("sticheron", "stichera")
IRREGULAR("stichidium", "stichidia")
IRREGULAR("stichos", "stichoi")
IRREGULAR("stickman", "stickmen")
IRREGULAR("stigma", "stigmata")
IRREGULAR("stillman", "stillmen")
IRREGULAR("stimulus", "stimuli")
IRREGULAR("stipes", "stipites")
IRREGULAR("stoa", "stoae")
IRREGULAR("stoccado", "stoccadoes")
IRREGULAR("stockman", "stockmen")
IRREGULAR("stoma", "stomata")
IRREGULAR("stomium", "stomia")
IRREGULAR("stomodaeum", "stomodaea")
IRREGULAR("stomodeum", "stomodea")
IRREGULAR("storeman", "storemen")
IRREGULAR("stornello", "stornelli")
IRREGULAR("stotin", "stotinov")
IRREGULAR("stotinka", "stotinki")
IRREGULAR("stratum", "strata")
IRREGULAR("stratus", "strati")
IRREGULAR("strelitz", "strelitzi")
IRREGULAR("stretta", "strette")
IRREGULAR("stretto", "stretti")
IRREGULAR("stria", "striae")
IRREGULAR("striatum", "striata")
IRREGULAR("striga", "strigae")
IRREGULAR("strobila", "strobilae")
IRREGULAR("strobilus", "strobili")
IRREGULAR("stroma", "stromata")
IRREGULAR("strongman", "strongmen")
IRREGULAR("strophulus", "strophuli")
IRREGULAR("struma", "strumae")
IRREGULAR("stucco", "stuccoes")
IRREGULAR("stuntman", "stuntmen")
IRREGULAR("stylus", "styli")
IRREGULAR("subcortex", "subcortices")
IRREGULAR("subcosta", "subcostae")
IRREGULAR("subcutis", "subcutes")
IRREGULAR("subecho", "subechoes")
IRREGULAR("subgenus", "subgenera")
IRREGULAR("subimago", "subimagoes")
IRREGULAR("subindex", "subindices")
IRREGULAR("subman", "submen")
IRREGULAR("submatrix", "submatrices")
IRREGULAR("submentum", "submenta")
IRREGULAR("subnucleus", "subnuclei")
IRREGULAR("subphylum", "subphyla")
IRREGULAR("subschema", "subschemata")
IRREGULAR("subsellium", "subsellia")
IRREGULAR("substratum", "substrata")
IRREGULAR("subtaxon", "subtaxa")
IRREGULAR("succah", "succot")
IRREGULAR("succes", "succes")
IRREGULAR("succos", "succos")
IRREGULAR("succuba", "succubae")
IRREGULAR("succubus", "succubi")
IRREGULAR("succus", "succi")
IRREGULAR("sudamen", "sudamina")
IRREGULAR("sudarium", "sudaria")
IRREGULAR("sudatorium", "sudatoria")
IRREGULAR("sugarloaf", "sugarloaves")
IRREGULAR("sukkah", "sukkot")
IRREGULAR("sukkos", "sukkos")
IRREGULAR("sulcus", "sulci")
IRREGULAR("sum", "sumy")
IRREGULAR("summa", "summae")
IRREGULAR("sundrops", "sundrops")
IRREGULAR("superhero", "superheroes")
IRREGULAR("superman", "supermen")
IRREGULAR("supernova", "supernovae")
IRREGULAR("superwife", "superwives")
IRREGULAR("suppeago", "suppeagoes")
IRREGULAR("supremum", "suprema")
IRREGULAR("surculus", "surculi")
IRREGULAR("surfman", "surfmen")
IRREGULAR("sushi", "sushi")
IRREGULAR("swagman", "swagmen")
IRREGULAR("swagsman", "swagsmen")
IRREGULAR("sweetman", "sweetmen")
IRREGULAR("swine", "swine")
IRREGULAR("swingby", "swingbys")
IRREGULAR("swingman", "swingmen")
IRREGULAR("switchman", "switchmen")
IRREGULAR("swiz", "swizzes")
IRREGULAR("swordman", "swordmen")
IRREGULAR("swordsman", "swordsmen")
IRREGULAR("syconium", "syconia")
IRREGULAR("sycosis", "sycoses")
IRREGULAR("syllabus", "syllabi")
IRREGULAR("syllepsis", "syllepses")
IRREGULAR("sylva", "sylvae")
IRREGULAR("symbiosis", "symbioses")
IRREGULAR("symphysis", "symphyses")
IRREGULAR("sympodium", "sympodia")
IRREGULAR("symposium", "symposia")
IRREGULAR("symptosis", "symptoses")
IRREGULAR("synandrium", "synandria")
IRREGULAR("synangium", "synangia")
IRREGULAR("synapsis", "synapses")
IRREGULAR("synaxarion", "synaxaria")
IRREGULAR("synaxis", "synaxes")
IRREGULAR("synchysis", "synchyses")
IRREGULAR("syncytium", "syncytia")
IRREGULAR("syndesis", "syndeses")
IRREGULAR("synedrion", "synedria")
IRREGULAR("synedrium", "synedria")
IRREGULAR("syneresis", "synereses")
IRREGULAR("synesis", "syneses")
IRREGULAR("syngas", "syngasses")
IRREGULAR("synizesis", "synizeses")
IRREGULAR("synkaryon", "synkarya")
IRREGULAR("synodsman", "synodsmen")
IRREGULAR("synopsis", "synopses")
IRREGULAR("syntagma", "syntagmata")
IRREGULAR("synthesis", "syntheses")
IRREGULAR("synthronus", "synthroni")
IRREGULAR("synura", "synurae")
IRREGULAR("syphiloma", "syphilomata")
IRREGULAR("syrinx", "syringes")
IRREGULAR("syrtis", "syrtes")
IRREGULAR("tableau", "tableaux")
IRREGULAR("tableful", "tablesful")
IRREGULAR("tabula", "tabulae")
IRREGULAR("tacksman", "tacksmen")
IRREGULAR("taenia", "taeniae")
IRREGULAR("taeniasis", "taeniases")
IRREGULAR("tagma", "tagmata")
IRREGULAR("taiglach", "taiglach")
IRREGULAR("talea", "taleae")
IRREGULAR("talesman", "talesmen")
IRREGULAR("talipes", "talipes")
IRREGULAR("tallis", "tallisim")
IRREGULAR("tallit", "tallitot")
IRREGULAR("tallith", "tallithim")
IRREGULAR("tallyho", "tallyhoes")
IRREGULAR("tallyman", "tallymen")
IRREGULAR("talpa", "talpae")
IRREGULAR("talus", "tali")
IRREGULAR("tambala", "matambala")
IRREGULAR("tamis", "tamis")
IRREGULAR("tapetum", "tapeta")
IRREGULAR("tapis", "tapis")
IRREGULAR("tapsman", "tapsmen")
IRREGULAR("tarsus", "tarsi")
IRREGULAR("tartufo", "tartufi")
IRREGULAR("tatami", "tatami")
IRREGULAR("taxi", "taxies")
IRREGULAR("taximan", "taximen")
IRREGULAR("taxis", "taxes")
IRREGULAR("taxman", "taxmen")
IRREGULAR("taxon", "taxa")
IRREGULAR("taxus", "taxus")
IRREGULAR("tazza", "tazze")
IRREGULAR("teargas", "teargasses")
IRREGULAR("tectrix", "tectrices")
IRREGULAR("tectum", "tecta")
IRREGULAR("tefillah", "tefillin")
IRREGULAR("tegmen", "tegmina")
IRREGULAR("tegmentum", "tegmenta")
IRREGULAR("tegula", "tegulae")
IRREGULAR("tegumen", "tegumina")
IRREGULAR("teiglach", "teiglach")
IRREGULAR("tela", "telae")
IRREGULAR("teleman", "telemen")
IRREGULAR("telesis", "teleses")
IRREGULAR("telium", "telia")
IRREGULAR("telly", "tellys")
IRREGULAR("telos", "teloi")
IRREGULAR("telotaxis", "telotaxes")
IRREGULAR("temblor", "temblores")
IRREGULAR("temenos", "temene")
IRREGULAR("tempo", "tempi")
IRREGULAR("tenaculum", "tenacula")
IRREGULAR("tendenz", "tendenzen")
IRREGULAR("tenia", "teniae")
IRREGULAR("teniasis", "teniases")
IRREGULAR("tenne", "tennesi")
IRREGULAR("tenorino", "tenorini")
IRREGULAR("tenorman", "tenormen")
IRREGULAR("tentaculum", "tentacula")
IRREGULAR("tentorium", "tentoria")
IRREGULAR("tenuis", "tenues")
IRREGULAR("tenuto", "tenuti")
IRREGULAR("tephillah", "tephillin")
IRREGULAR("tepidarium", "tepidaria")
IRREGULAR("teraph", "teraphim")
IRREGULAR("teras", "terata")
IRREGULAR("teratoma", "teratomata")
IRREGULAR("terebra", "terebrae")
IRREGULAR("teredo", "teredines")
IRREGULAR("teres", "teretes")
IRREGULAR("tergum", "terga")
IRREGULAR("terminus", "termini")
IRREGULAR("terra", "terrae")
IRREGULAR("terrarium", "terraria")
IRREGULAR("terts", "terts")
IRREGULAR("terzetto", "terzetti")
IRREGULAR("tessella", "tessellae")
IRREGULAR("tessera", "tesserae")
IRREGULAR("tessitura", "tessiture")
IRREGULAR("testa", "testae")
IRREGULAR("testatrix", "testatrices")
IRREGULAR("testis", "testes")
IRREGULAR("thalamus", "thalami")
IRREGULAR("thallus", "thalli")
IRREGULAR("theca", "thecae")
IRREGULAR("thelf", "thelves")
IRREGULAR("thema", "themata")
IRREGULAR("theotokos", "theotokoi")
IRREGULAR("thesaurus", "thesauri")
IRREGULAR("thesis", "theses")
IRREGULAR("thew", "thewes")
IRREGULAR("thickleaf", "thickleaves")
IRREGULAR("thicko", "thickoes")
IRREGULAR("thief", "thieves")
IRREGULAR("thirdsman", "thirdsmen")
IRREGULAR("thlipsis", "thlipses")
IRREGULAR("tholos", "tholoi")
IRREGULAR("tholus", "tholi")
IRREGULAR("thorax", "thoraces")
IRREGULAR("thrombus", "thrombi")
IRREGULAR("thylosis", "thyloses")
IRREGULAR("thymoma", "thymomata")
IRREGULAR("thymus", "thymi")
IRREGULAR("thyrsus", "thyrsi")
IRREGULAR("tibia", "tibiae")
IRREGULAR("tibialis", "tibiales")
IRREGULAR("tidesman", "tidesmen")
IRREGULAR("tifoso", "tifosi")
IRREGULAR("tillerman", "tillermen")
IRREGULAR("timberman", "timbermen")
IRREGULAR("timpano", "timpani")
IRREGULAR("timpanum", "timpana")
IRREGULAR("tinman", "tinmen")
IRREGULAR("tipstaff", "tipstaves")
IRREGULAR("tirewoman", "tirewomen")
IRREGULAR("tiro", "tiroes")
IRREGULAR("titman", "titmen")
IRREGULAR("titmouse", "titmice")
IRREGULAR("titulus", "tituli")
IRREGULAR("tmesis", "tmeses")
IRREGULAR("tobacco", "tobaccoes")
IRREGULAR("toccata", "toccate")
IRREGULAR("toga", "togae")
IRREGULAR("tolar", "tolarjev")
IRREGULAR("tollman", "tollmen")
IRREGULAR("tomatillo", "tomatilloes")
IRREGULAR("tomato", "tomatoes")
IRREGULAR("tomentum", "tomenta")
IRREGULAR("tomium", "tomia")
IRREGULAR("tondino", "tondini")
IRREGULAR("tondo", "tondi")
IRREGULAR("tongman", "tongmen")
IRREGULAR("tonneau", "tonneaux")
IRREGULAR("tooth", "teeth")
IRREGULAR("toolman", "toolmen")
IRREGULAR("tophus", "tophi")
IRREGULAR("topman", "topmen")
IRREGULAR("topos", "topoi")
IRREGULAR("topsman", "topsmen")
IRREGULAR("torah", "torot")
IRREGULAR("torii", "torii")
IRREGULAR("tormentum", "tormenta")
IRREGULAR("tornado", "tornadoes")
IRREGULAR("torpedo", "torpedoes")
IRREGULAR("torso", "torsi")
IRREGULAR("torte", "torten")
IRREGULAR("tortrix", "tortrices")
IRREGULAR("torula", "torulae")
IRREGULAR("torulosis", "toruloses")
IRREGULAR("torulus", "toruli")
IRREGULAR("torus", "tori")
IRREGULAR("tournedos", "tournedos")
IRREGULAR("townsman", "townsmen")
IRREGULAR("toxicosis", "toxicoses")
IRREGULAR("toyman", "toymen")
IRREGULAR("toywoman", "toywomen")
IRREGULAR("trachea", "tracheae")
IRREGULAR("trackman", "trackmen")
IRREGULAR("tractrix", "tractrices")
IRREGULAR("tradesman", "tradesmen")
IRREGULAR("traditor", "traditores")
IRREGULAR("tragus", "tragi")
IRREGULAR("trainman", "trainmen")
IRREGULAR("trapezium", "trapezia")
IRREGULAR("trapezius", "trapezii")
IRREGULAR("trashman", "trashmen")
IRREGULAR("trattoria", "trattorie")
IRREGULAR("trauma", "traumata")
IRREGULAR("treponema", "treponemata")
IRREGULAR("trewsman", "trewsmen")
IRREGULAR("tribesman", "tribesmen")
IRREGULAR("trichina", "trichinae")
IRREGULAR("trichosis", "trichoses")
IRREGULAR("triclinium", "triclinia")
IRREGULAR("triennium", "triennia")
IRREGULAR("triens", "trientes")
IRREGULAR("triforium", "triforia")
IRREGULAR("trigeminus", "trigemini")
IRREGULAR("trihedron", "trihedra")
IRREGULAR("trilby", "trilbys")
IRREGULAR("trillo", "trilloes")
IRREGULAR("tripman", "tripmen")
IRREGULAR("tripsis", "tripses")
IRREGULAR("tripudium", "tripudia")
IRREGULAR("triquetra", "triquetrae")
IRREGULAR("triskelion", "triskelia")
IRREGULAR("triumvir", "triumviri")
IRREGULAR("trochilus", "trochili")
IRREGULAR("trochlea", "trochleae")
IRREGULAR("trochus", "trochi")
IRREGULAR("tromino", "trominoes")
IRREGULAR("tropaeolum", "tropaeola")
IRREGULAR("troparion", "troparia")
IRREGULAR("trout", "trout")
IRREGULAR("truchman", "truchmen")
IRREGULAR("truckman", "truckmen")
IRREGULAR("trueman", "truemen")
IRREGULAR("trumeau", "trumeaux")
IRREGULAR("tryma", "trymata")
IRREGULAR("tsaddik", "tsaddikim")
IRREGULAR("tsaddiq", "tsaddiqim")
IRREGULAR("tsooris", "tsooris")
IRREGULAR("tsores", "tsores")
IRREGULAR("tsoris", "tsoris")
IRREGULAR("tsorris", "tsorris")
IRREGULAR("tsouris", "tsouris")
IRREGULAR("tuberculum", "tubercula")
IRREGULAR("tufoli", "tufoli")
IRREGULAR("tumulus", "tumuli")
IRREGULAR("tuna", "tuna")
IRREGULAR("tunica", "tunicae")
IRREGULAR("turf", "turves")
IRREGULAR("turfman", "turfmen")
IRREGULAR("turquois", "turquois")
IRREGULAR("tussis", "tusses")
IRREGULAR("tutman", "tutmen")
IRREGULAR("tutrix", "tutrices")
IRREGULAR("tuxedo", "tuxedoes")
IRREGULAR("tyiyn", "tyiyn")
IRREGULAR("tylosis", "tyloses")
IRREGULAR("tympano", "tympani")
IRREGULAR("tympanum", "tympana")
IRREGULAR("tyro", "tyroes")
IRREGULAR("tzaddik", "tzaddikim")
IRREGULAR("tzaddiq", "tzaddiqim")
IRREGULAR("ulex", "ulices")
IRREGULAR("ulna", "ulnae")
IRREGULAR("ulnare", "ulnaria")
IRREGULAR("ulosis", "uloses")
IRREGULAR("ulpan", "ulpanim")
IRREGULAR("ultimatum", "ultimata")
IRREGULAR("umbilicus", "umbilici")
IRREGULAR("umbo", "umbones")
IRREGULAR("umbra", "umbrae")
IRREGULAR("umbraculum", "umbracula")
IRREGULAR("umbrello", "umbrelloes")
IRREGULAR("uncia", "unciae")
IRREGULAR("uncinus", "uncini")
IRREGULAR("unco", "uncoes")
IRREGULAR("uncus", "unci")
IRREGULAR("undead", "undead")
IRREGULAR("underleaf", "underleaves")
IRREGULAR("underman", "undermen")
IRREGULAR("underself", "underselves")
IRREGULAR("unfreeman", "unfreemen")
IRREGULAR("unguentum", "unguenta")
IRREGULAR("unguis", "ungues")
IRREGULAR("ungula", "ungulae")
IRREGULAR("unicum", "unica")
IRREGULAR("urachus", "urachi")
IRREGULAR("uraeus", "uraei")
IRREGULAR("uraniscus", "uranisci")
IRREGULAR("urceolus", "urceoli")
IRREGULAR("uredinium", "uredinia")
IRREGULAR("uredium", "uredia")
IRREGULAR("uredo", "uredines")
IRREGULAR("uredosorus", "uredosori")
IRREGULAR("uresis", "ureses")
IRREGULAR("urethra", "urethrae")
IRREGULAR("uropygium", "uropygia")
IRREGULAR("urosis", "uroses")
IRREGULAR("ursa", "ursae")
IRREGULAR("urtext", "urtexte")
IRREGULAR("uterus", "uteri")
IRREGULAR("utriculus", "utriculi")
IRREGULAR("uva", "uvae")
IRREGULAR("uvula", "uvulae")
IRREGULAR("vacuum", "vacua")
IRREGULAR("vagina", "vaginae")
IRREGULAR("vaginosis", "vaginoses")
IRREGULAR("vaginula", "vaginulae")
IRREGULAR("vagus", "vagi")
IRREGULAR("valvula", "valvulae")
IRREGULAR("vanman", "vanmen")
IRREGULAR("vaporetto", "vaporetti")
IRREGULAR("varicosis", "varicoses")
IRREGULAR("varix", "varices")
IRREGULAR("vas", "vasa")
IRREGULAR("vasculum", "vascula")
IRREGULAR("vatman", "vatmen")
IRREGULAR("vaudoux", "vaudoux")
IRREGULAR("veduta", "vedute")
IRREGULAR("vedutista", "vedutisti")
IRREGULAR("vehm", "vehme")
IRREGULAR("velamen", "velamina")
IRREGULAR("velarium", "velaria")
IRREGULAR("velours", "velours")
IRREGULAR("velum", "vela")
IRREGULAR("vena", "venae")
IRREGULAR("venireman", "veniremen")
IRREGULAR("vermis", "vermes")
IRREGULAR("verruca", "verrucae")
IRREGULAR("vers", "vers")
IRREGULAR("verseman", "versemen")
IRREGULAR("vertebra", "vertebrae")
IRREGULAR("vertex", "vertices")
IRREGULAR("vertigo", "vertigoes")
IRREGULAR("vesica", "vesicae")
IRREGULAR("vesicula", "vesiculae")
IRREGULAR("vestibulum", "vestibula")
IRREGULAR("vestigium", "vestigia")
IRREGULAR("vestryman", "vestrymen")
IRREGULAR("vetturino", "vetturini")
IRREGULAR("vexillum", "vexilla")
IRREGULAR("via", "viae")
IRREGULAR("viaticum", "viatica")
IRREGULAR("viator", "viatores")
IRREGULAR("vibex", "vibices")
IRREGULAR("vibraculum", "vibracula")
IRREGULAR("vibriosis", "vibrioses")
IRREGULAR("vibrissa", "vibrissae")
IRREGULAR("videndum", "videnda")
IRREGULAR("viliaco", "viliacoes")
IRREGULAR("viliago", "viliagoes")
IRREGULAR("villa", "villae")
IRREGULAR("villagio", "villagioes")
IRREGULAR("villiaco", "villiacoes")
IRREGULAR("villiago", "villiagoes")
IRREGULAR("villus", "villi")
IRREGULAR("vimen", "vimina")
IRREGULAR("vinculum", "vincula")
IRREGULAR("virago", "viragoes")
IRREGULAR("virga", "virgae")
IRREGULAR("virosis", "viroses")
IRREGULAR("virtuosa", "virtuose")
IRREGULAR("virtuoso", "virtuosi")
IRREGULAR("vis", "vires")
IRREGULAR("viscus", "viscera")
IRREGULAR("vita", "vitae")
IRREGULAR("vitellus", "vitelli")
IRREGULAR("viticetum", "viticeta")
IRREGULAR("vitrail", "vitraux")
IRREGULAR("vitta", "vittae")
IRREGULAR("vivarium", "vivaria")
IRREGULAR("vola", "volae")
IRREGULAR("volcano", "volcanoes")
IRREGULAR("volkslied", "volkslieder")
IRREGULAR("volva", "volvae")
IRREGULAR("volvulus", "volvuli")
IRREGULAR("vomica", "vomicae")
IRREGULAR("vomitorium", "vomitoria")
IRREGULAR("vorago", "voragoes")
IRREGULAR("vortex", "vortices")
IRREGULAR("vox", "voces")
IRREGULAR("vulsella", "vulsellae")
IRREGULAR("vulsellum", "vulsella")
IRREGULAR("vulva", "vulvae")
IRREGULAR("wacko", "wackoes")
IRREGULAR("wakeman", "wakemen")
IRREGULAR("waldo", "waldoes")
IRREGULAR("warman", "warmen")
IRREGULAR("warwolf", "warwolves")
IRREGULAR("washerman", "washermen")
IRREGULAR("washwoman", "washwomen")
IRREGULAR("wasserman", "wassermen")
IRREGULAR("watchman", "watchmen")
IRREGULAR("waterbus", "waterbusses")
IRREGULAR("watercraft", "watercraft")
IRREGULAR("waterman", "watermen")
IRREGULAR("wealsman", "wealsmen")
IRREGULAR("webfoot", "webfeet")
IRREGULAR("weighman", "weighmen")
IRREGULAR("weirdo", "weirdoes")
IRREGULAR("wendigo", "wendigoes")
IRREGULAR("werewolf", "werewolves")
IRREGULAR("werwolf", "werwolves")
IRREGULAR("whacko", "whackoes")
IRREGULAR("whaleman", "whalemen")
IRREGULAR("wharf", "wharves")
IRREGULAR("wheelman", "wheelmen")
IRREGULAR("wheelsman", "wheelsmen")
IRREGULAR("wherryman", "wherrymen")
IRREGULAR("whiz", "whizzes")
IRREGULAR("why", "whys")
IRREGULAR("widowman", "widowmen")
IRREGULAR("wife", "wives")
IRREGULAR("winchman", "winchmen")
IRREGULAR("windigo", "windigoes")
IRREGULAR("wingman", "wingmen")
IRREGULAR("wino", "winoes")
IRREGULAR("wireman", "wiremen")
IRREGULAR("wisewoman", "wisewomen")
IRREGULAR("wiz", "wizzes")
IRREGULAR("wolf", "wolves")
IRREGULAR("woman", "women")
IRREGULAR("woodlouse", "woodlice")
IRREGULAR("woodman", "woodmen")
IRREGULAR("woodmouse", "woodmice")
IRREGULAR("woodsman", "woodsmen")
IRREGULAR("woolman", "woolmen")
IRREGULAR("workman", "workmen")
IRREGULAR("workwoman", "workwomen")
IRREGULAR("worryguts", "worryguts")
IRREGULAR("wunderkind", "wunderkinder")
IRREGULAR("xanthoma", "xanthomata")
IRREGULAR("xenium", "xenia")
IRREGULAR("xeransis", "xeranses")
IRREGULAR("xeroma", "xeromata")
IRREGULAR("xerosis", "xeroses")
IRREGULAR("xerostoma", "xerostomata")
IRREGULAR("xerotes", "xerotes")
IRREGULAR("xiphopagus", "xiphopagi")
IRREGULAR("xoanon", "xoana")
IRREGULAR("xu", "xu")
IRREGULAR("xyloma", "xylomata")
IRREGULAR("xystos", "xystoi")
IRREGULAR("xystus", "xysti")
IRREGULAR("yachtman", "yachtmen")
IRREGULAR("yachtsman", "yachtsmen")
IRREGULAR("yakuza", "yakuza")
IRREGULAR("yardman", "yardmen")
IRREGULAR("yarraman", "yarramen")
IRREGULAR("yaws", "yaws")
IRREGULAR("yeggman", "yeggmen")
IRREGULAR("yeoman", "yeomen")
IRREGULAR("yersinia", "yersiniae")
IRREGULAR("yeshiva", "yeshivoth")
IRREGULAR("yobbo", "yobboes")
IRREGULAR("yom", "yomim")
IRREGULAR("yourself", "yourselves")
IRREGULAR("zaddick", "zaddikim")
IRREGULAR("zaddik", "zaddikim")
IRREGULAR("zaibatsu", "zaibatsu")
IRREGULAR("zakouska", "zakouski")
IRREGULAR("zakuska", "zakuski")
IRREGULAR("zampone", "zamponi")
IRREGULAR("zastruga", "zastrugi")
IRREGULAR("zecchino", "zecchini")
IRREGULAR("zelatrix", "zelatrices")
IRREGULAR("zemstvo", "zemstva")
IRREGULAR("zeppole", "zeppoli")
IRREGULAR("zero", "zeroes")
IRREGULAR("zingano", "zingani")
IRREGULAR("zingara", "zingare")
IRREGULAR("zingaro", "zingari")
IRREGULAR("zloty", "zlote")
IRREGULAR("zoaea", "zoaeae")
IRREGULAR("zoarium", "zoaria")
IRREGULAR("zoea", "zoeae")
IRREGULAR("zoecium", "zoecia")
IRREGULAR("zona", "zonae")
IRREGULAR("zonula", "zonulae")
IRREGULAR("zoocytium", "zoocytia")
IRREGULAR("zooea", "zooeae")
IRREGULAR("zooecium", "zooecia")
IRREGULAR("zooglea", "zoogleae")
IRREGULAR("zoogloea", "zoogloeae")
IRREGULAR("zoon", "zoa")
IRREGULAR("zoonosis", "zoonoses")
IRREGULAR("zoophorus", "zoophori")
IRREGULAR("zoothecium", "zoothecia")
IRREGULAR("zucchetto", "zucchetti")
IRREGULAR("zuffolo", "zuffoli")
IRREGULAR("zufolo", "zufoli")
IRREGULAR("zuz", "zuzim")
IRREGULAR("zygantrum", "zygantra")
IRREGULAR("zygocactus", "zygocacti")
IRREGULAR("zygoma", "zygomata")
IRREGULAR("zygon", "zyga")
IRREGULAR("zygosis", "zygoses")
IRREGULAR("zymolysis", "zymolyses")
IRREGULAR("zymosis", "zymoses")
};

#undef	IRREGULAR

/*** words that can come before -man and -woman ***/
static const char* __man_woman_prefix[] =
{
"ad",		"aid",		"air",		"alder",	"alms",		"arts",		"ash",		"auto",
"axe",		"ax",		"bad",		"bands",	"banks",	"barge",	"bar",		"base",
"bat",		"bats",		"bead",		"beads",	"bell",		"belt",		"bill",		"bin",
"bird",		"birlie",	"blues",	"board",	"boat",		"body",		"bogey",	"bog",
"bogy",		"bonds",	"booger",	"boogey",	"boogie",	"boogy",	"book",		"bow",
"brake",	"brakes",	"bride",	"brides",	"brink",	"bushel",	"bush",		"bus",
"butty",	"byre",		"cab",		"camera",	"candy",	"canoe",	"car",		"case",
"cattle",	"cave",		"cellar",	"chain",	"chair",	"chap",		"char",		"chess",
"china",	"choir",	"chore",	"church",	"clans",	"class",	"clergy",	"club",
"coach",	"coal",		"cockle",	"cocks",	"color",	"colour",	"con",		"corner",
"corps",	"cow",		"cracks",	"crafts",	"crags",	"crew",		"cup",		"dairy",
"dales",	"days",		"dead",		"deaths",	"desk",		"dog",		"dogger",	"dooms",
"door",		"doors",	"drafts",	"drago",	"drags",	"dray",		"dutch",	"ealdor",
"earth",	"every",	"excise",	"face",		"fellow",	"ferry",	"fields",	"fire",	
"fisher",	"flag",		"flugel",	"fly",		"foe",		"fog",		"foils",	"foot",
"fore",		"forge",	"frauds",	"free",		"fresh",	"frog",		"front",	"fugle",
"funny",	"gad",		"gads",		"gag",		"gangs",	"garage",	"gas",		"gate",
"gavel",	"gentle",	"gig",		"gilds",	"glass",	"glee",		"goads",	"gown",
"gowns",	"grants",	"grooms",	"ground",	"guards",	"gude",		"guilds",	"gun",
"hack",		"hammer",	"handy",	"hang",		"hard",		"head",		"heads",	"heli",
"helms",	"herd",		"herds",	"high",		"hit",		"hoast",	"hoist",	"hood",
"horse",	"hose",		"hotel",	"house",	"hunts",	"ice",		"iron",		"isle",
"jack",		"jark",		"jazz",		"junk",		"jury",		"keel",		"kennel",	"kins",
"kirk",		"klooch",	"klootch",	"knife",	"land",		"lands",	"law",		"lay",
"lead",		"leads",	"leg",		"length",	"lens",		"letter",	"liege",	"lift",
"line",		"lines",	"link",		"links",	"livery",	"lock",		"locks",	"lodes",
"lofts",	"lumber",	"mad",		"mags",		"mail",		"malt",		"march",	"mark",
"marks",	"mash",		"meat",		"meres",	"mer",		"merry",	"mess",		"middle",
"milk",		"minute",	"mobs",		"money",	"moor",		"moot",		"mortar",	"motor",
"muscle",	"news",		"noble",	"non",		"oars",		"odds",		"oil",		"ombuds",
"oncost",	"orra",		"over",		"overs",	"pace",		"pack",		"pantry",	"pass",
"patrol",	"peat",		"pen",		"peter",	"phrase",	"pie",		"pike",		"pilot",
"pitch",	"pit",		"pivot",	"place",	"plaid",	"plains",	"plants",	"plate",
"please",	"plough",	"plow",		"point",	"points",	"police",	"poll",		"port",
"post",		"pot",		"pre",		"press",	"prize",	"prop",		"prose",	"punts",	
"quarry",	"quill",	"raddle",	"radio",	"raft",		"rafts",	"rag",		"rail",
"ramps",	"ranch",	"ranzel",	"reddle",	"reed",		"reel",		"reins",	"repair",
"repo",		"rifle",	"ring",		"river",	"road",		"roads",	"rod",		"rods",
"rounds",	"route",	"ruck",		"ruddle",	"safety",	"saga",		"salary",	"sales",
"sand",		"sax",		"school",	"scythe",	"sea",		"seed",		"seeds",	"select",
"shanty",	"share",	"shares",	"shear",	"sheep",	"ship",		"shire",	"shop",
"shore",	"shores",	"show",		"sickle",	"side",		"sides",	"sights",	"signal",
"sky",		"snow",		"sock",		"soc",		"soke",		"sonar",	"song",		"sound",
"space",	"spade",	"spades",	"spae",		"spear",	"spider",	"spoils",	"spokes",
"sports",	"squaw",	"stable",	"staff",	"stall",	"states",	"stears",	"steel",
"steers",	"stick",	"still",	"stock",	"store",	"strong",	"stunt",	"sub",
"super",	"surf",		"swag",		"swags",	"sweet",	"swing",	"switch",	"sword",
"swords",	"synods",	"tacks",	"tales",	"tally",	"taps",		"taxi",		"tax",
"tele",		"tenor",	"thirds",	"tides",	"tiller",	"timber",	"tin",		"tire",
"tit",		"toll",		"tong",		"tool",		"top",		"tops",		"towns",	"toy",
"track",	"trades",	"train",	"trash",	"trews",	"tribes",	"trip",		"truch",
"truck",	"true",		"turf",		"tut",		"under",	"unfree",	"van",		"vat",
"venire",	"verse",	"vestry",	"wake",		"war",		"washer",	"wasser",	"watch",
"water",	"weals",	"weigh",	"whale",	"wheel",	"wheels",	"wherry",	"widow",
"winch",	"wing",		"wire",		"wise",		"wood",		"woods",	"wool",		"work",
"yacht",	"yachts",	"yard",		"yarra",	"yeo",		
NULL
};

static char __retbuf[16][256];
static u32 __wret = 0;

int __irregular_comp(const void* v1, const void* v2) {
	const char* s1 = (const char*)v1;
	const char* s2 = ((const char**)v2)[0];

	return(__stricmp(s1, s2));
}

static int _irregular_binary_search(const char* search_for) {
	char** c;

	c = (char**)asearch(search_for, __irregular_plurals, array_size(__irregular_plurals), __irregular_comp);

	if (is_null(c))
		return(-1);

	return ((c - (char**)__irregular_plurals) >> 1);
}

static int _irregular_linear_search(const char* search_for) {
	int la = array_size(__irregular_plurals);
	int e;

	--la;
	for (e = la; e >= 0; --e) {
		if (!__stricmp(search_for, __irregular_plurals[e][1]))
			return(e);
	}

	return(-1);
}

/*** Might want to call this after modifying the irregular plurals array to verify the sort. ***/
void debug_verify_plural_sort(void) {
	int la = array_size(__irregular_plurals);
	int e;

	la -= 2;
	for (e = la; e >= 0; --e) {
		if (strcmp(__irregular_plurals[e][0], __irregular_plurals[e + 1][0]) >= 0) {
			printf("Bad sort: %d %s, %d %s\n", e, __irregular_plurals[e][0],
				(e + 1), __irregular_plurals[e + 1][0]);
		}
	}
}

void match_capitalization(char* retbuf, const char* match_word) {
	bool isup = true;
	while (*retbuf) {
		if (*match_word != '\000') {
			isup = isupper(*match_word);
			++match_word;

		}
		*retbuf = (isup ? toupper(*retbuf) : tolower(*retbuf));
		++retbuf;
	}
}

/*** Note that for the purposes of this function, 'y' is not a vowel. ***/
bool is_english_vowel(const char cc) {
	switch (cc) {
	default:
		break;
		
	case 'a':
	case 'e':
	case 'i':
	case 'o':
	case 'u':
	case 'A':
	case 'E':
	case 'I':
	case 'O':
	case 'U':
		/* so many more vowel sounds than this */
		return(true);
	}
	return(false);
}

const char* english_plural(const char* singular_word) {
	const char* __es_endings[] =
		{ "s", "x", "z", "ch", "sh", NULL };
	unsigned int l = strlen(singular_word);
	const char* w;
	if (l > 250)
		return(NULL);

	char* retbuf = __retbuf[__wret];
	__wret++;
	__wret &= 15;
	
	/* first, search for an exact match in our irregular plurals array */
	int imatch = _irregular_binary_search(singular_word);
	if (imatch >= 0) {
		strcpy(retbuf, __irregular_plurals[imatch][1]);
		goto LDone;
	}
	
	/* hyphens: in a case like "mother-in-law" we should pluralize the
		first word, but in the case of "tractor-trailer" we should pluralize
		the second -- look for a preposition */
	w = strchr(singular_word, '-');
	if (not_null(w)) {
		// TODO: implement this
	}
		
	/* look for -man or -woman ending */
	if (l > 3 && __stricmp(singular_word + l - 3, "man") == 0) {
		bool iswoman = (l > 5 && (__stricmp(singular_word + l - 5, "woman") == 0));
		imatch = 0;
		while (not_null(__man_woman_prefix[imatch])) {
			int ll = strlen(__man_woman_prefix[imatch]);
			if (ll + 3 + (iswoman ? 2 : 0) == l) {
				if (!__strnicmp(singular_word, __man_woman_prefix[imatch], ll))
					break;
			}
			++imatch;
		}
		if (not_null(__man_woman_prefix[imatch])) {
			strcpy(retbuf, __man_woman_prefix[imatch]);
			strcat(retbuf, (iswoman ? "women" : "men"));
			goto LDone;
		}
	}

	/* okay, go ahead and try to make a regular plural out of this */

	/* If the word ends in -S, -X, -Z, -CH, -SH, add -ES. There are exceptions (EPOCH, LOCH), but those 
		should be in the irregular plurals array. */
	imatch = 0;
	while (__es_endings[imatch]) {
		if (!__stricmp(singular_word + l - strlen(__es_endings[imatch]), __es_endings[imatch])) {
			strcpy(retbuf, singular_word);
			strcat(retbuf, "es");
			goto LDone;
		}
		++imatch;
	}
		
	/* If the word ends in -Y not preceded by vowel, change the ending -Y to -IES. */
	if (l >= 2 && tolower(singular_word[l - 1]) == 'y' && !is_english_vowel(singular_word[l - 2])) {
		strcpy(retbuf, singular_word);
		strcpy(retbuf + l - 1, "ies");
		goto LDone;
	}
	
	/* Else, just add an S. */
	strcpy(retbuf, singular_word);
	retbuf[l] = 's';
	retbuf[++l] = '\000';

LDone:
	/* Now normalize capitalization and return our result. */
	match_capitalization(retbuf, singular_word);
	return((const char*)retbuf);
}

const char* plural_phrase(const char* singular_phrase) {
	// NYI
	// TODO: implement
	assert(false);
	return(NULL);
}

/*** I should ideally have another alphabetized array that's easy
	to search. Instead I'll do a linear search here. This is probably
	by far the less likely case. ***/





// TODO: build a dictionary structure.

const char* english_singular(const char* plural_word) {
	// NYI
	// TODO: implement
	assert(false);
	return(NULL);
}

int is_english_plural(const char* word) {
	// NYI
	// TODO: implement
	assert(false);
	return(0);
}

const char* english_singular_or_plural(const char* singular_form, int count) {
	if (1 == count)
		return(singular_form);
	return(english_plural(singular_form));
}

/*** end plurals.cpp ***/
